module.exports = [
  { mpioCode: '05002', mpioName: 'ABEJORRAL', deptoName: 'ANTIOQUIA' },
  { mpioCode: '54003', mpioName: 'ÁBREGO', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '05004', mpioName: 'ABRIAQUÍ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '50006', mpioName: 'ACACÍAS', deptoName: 'META' },
  { mpioCode: '27006', mpioName: 'ACANDÍ', deptoName: 'CHOCÓ' },
  { mpioCode: '41006', mpioName: 'ACEVEDO', deptoName: 'HUILA' },
  { mpioCode: '13006', mpioName: 'ACHÍ', deptoName: 'BOLÍVAR' },
  { mpioCode: '41013', mpioName: 'AGRADO', deptoName: 'HUILA' },
  { mpioCode: '25001', mpioName: 'AGUA DE DIOS', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '20011', mpioName: 'AGUACHICA', deptoName: 'CESAR' },
  { mpioCode: '68013', mpioName: 'AGUADA', deptoName: 'SANTANDER' },
  { mpioCode: '17013', mpioName: 'AGUADAS', deptoName: 'CALDAS' },
  { mpioCode: '85010', mpioName: 'AGUAZUL', deptoName: 'CASANARE' },
  { mpioCode: '20013', mpioName: 'AGUSTÍN CODAZZI', deptoName: 'CESAR' },
  { mpioCode: '41016', mpioName: 'AIPE', deptoName: 'HUILA' },
  { mpioCode: '25019', mpioName: 'ALBÁN', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52019', mpioName: 'ALBÁN', deptoName: 'NARIÑO' },
  { mpioCode: '18029', mpioName: 'ALBANIA', deptoName: 'CAQUETÁ' },
  { mpioCode: '44035', mpioName: 'ALBANIA', deptoName: 'LA GUAJIRA' },
  { mpioCode: '68020', mpioName: 'ALBANIA', deptoName: 'SANTANDER' },
  { mpioCode: '76020', mpioName: 'ALCALÁ', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '52022', mpioName: 'ALDANA', deptoName: 'NARIÑO' },
  { mpioCode: '05021', mpioName: 'ALEJANDRÍA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '47030', mpioName: 'ALGARROBO', deptoName: 'MAGDALENA' },
  { mpioCode: '41020', mpioName: 'ALGECIRAS', deptoName: 'HUILA' },
  { mpioCode: '19022', mpioName: 'ALMAGUER', deptoName: 'CAUCA' },
  { mpioCode: '15022', mpioName: 'ALMEIDA', deptoName: 'BOYACÁ' },
  { mpioCode: '73024', mpioName: 'ALPUJARRA', deptoName: 'TOLIMA' },
  { mpioCode: '41026', mpioName: 'ALTAMIRA', deptoName: 'HUILA' },
  { mpioCode: '27025', mpioName: 'ALTO BAUDÓ', deptoName: 'CHOCÓ' },
  { mpioCode: '13030', mpioName: 'ALTOS DEL ROSARIO', deptoName: 'BOLÍVAR' },
  { mpioCode: '73026', mpioName: 'ALVARADO', deptoName: 'TOLIMA' },
  { mpioCode: '05030', mpioName: 'AMAGÁ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05031', mpioName: 'AMALFI', deptoName: 'ANTIOQUIA' },
  { mpioCode: '73030', mpioName: 'AMBALEMA', deptoName: 'TOLIMA' },
  { mpioCode: '25035', mpioName: 'ANAPOIMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52036', mpioName: 'ANCUYA', deptoName: 'NARIÑO' },
  { mpioCode: '76036', mpioName: 'ANDALUCÍA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '05034', mpioName: 'ANDES', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05036', mpioName: 'ANGELÓPOLIS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05038', mpioName: 'ANGOSTURA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25040', mpioName: 'ANOLAIMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '05040', mpioName: 'ANORÍ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '17042', mpioName: 'ANSERMA', deptoName: 'CALDAS' },
  { mpioCode: '76041', mpioName: 'ANSERMANUEVO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '05044', mpioName: 'ANZÁ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '73043', mpioName: 'ANZOÁTEGUI', deptoName: 'TOLIMA' },
  { mpioCode: '05045', mpioName: 'APARTADÓ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '66045', mpioName: 'APÍA', deptoName: 'RISARALDA' },
  { mpioCode: '25599', mpioName: 'APULO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15047', mpioName: 'AQUITANIA', deptoName: 'BOYACÁ' },
  { mpioCode: '47053', mpioName: 'ARACATACA', deptoName: 'MAGDALENA' },
  { mpioCode: '17050', mpioName: 'ARANZAZU', deptoName: 'CALDAS' },
  { mpioCode: '68051', mpioName: 'ARATOCA', deptoName: 'SANTANDER' },
  { mpioCode: '81001', mpioName: 'ARAUCA', deptoName: 'ARAUCA' },
  { mpioCode: '81065', mpioName: 'ARAUQUITA', deptoName: 'ARAUCA' },
  { mpioCode: '25053', mpioName: 'ARBELÁEZ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52051', mpioName: 'ARBOLEDA', deptoName: 'NARIÑO' },
  { mpioCode: '54051', mpioName: 'ARBOLEDAS', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '05051', mpioName: 'ARBOLETES', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15051', mpioName: 'ARCABUCO', deptoName: 'BOYACÁ' },
  { mpioCode: '13042', mpioName: 'ARENAL', deptoName: 'BOLÍVAR' },
  { mpioCode: '05055', mpioName: 'ARGELIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '19050', mpioName: 'ARGELIA', deptoName: 'CAUCA' },
  { mpioCode: '76054', mpioName: 'ARGELIA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '47058', mpioName: 'ARIGUANÍ', deptoName: 'MAGDALENA' },
  { mpioCode: '13052', mpioName: 'ARJONA', deptoName: 'BOLÍVAR' },
  { mpioCode: '05059', mpioName: 'ARMENIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '63001', mpioName: 'ARMENIA', deptoName: 'QUINDÍO' },
  { mpioCode: '73055', mpioName: 'ARMERO', deptoName: 'TOLIMA' },
  { mpioCode: '13062', mpioName: 'ARROYOHONDO', deptoName: 'BOLÍVAR' },
  { mpioCode: '20032', mpioName: 'ASTREA', deptoName: 'CESAR' },
  { mpioCode: '73067', mpioName: 'ATACO', deptoName: 'TOLIMA' },
  { mpioCode: '27050', mpioName: 'ATRATO', deptoName: 'CHOCÓ' },
  { mpioCode: '23068', mpioName: 'AYAPEL', deptoName: 'CÓRDOBA' },
  { mpioCode: '27073', mpioName: 'BAGADÓ', deptoName: 'CHOCÓ' },
  { mpioCode: '27075', mpioName: 'BAHÍA SOLANO', deptoName: 'CHOCÓ' },
  { mpioCode: '27077', mpioName: 'BAJO BAUDÓ', deptoName: 'CHOCÓ' },
  { mpioCode: '19075', mpioName: 'BALBOA', deptoName: 'CAUCA' },
  { mpioCode: '66075', mpioName: 'BALBOA', deptoName: 'RISARALDA' },
  { mpioCode: '08078', mpioName: 'BARANOA', deptoName: 'ATLÁNTICO' },
  { mpioCode: '41078', mpioName: 'BARAYA', deptoName: 'HUILA' },
  { mpioCode: '52079', mpioName: 'BARBACOAS', deptoName: 'NARIÑO' },
  { mpioCode: '05079', mpioName: 'BARBOSA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68077', mpioName: 'BARBOSA', deptoName: 'SANTANDER' },
  { mpioCode: '68079', mpioName: 'BARICHARA', deptoName: 'SANTANDER' },
  { mpioCode: '50110', mpioName: 'BARRANCA DE UPÍA', deptoName: 'META' },
  { mpioCode: '68081', mpioName: 'BARRANCABERMEJA', deptoName: 'SANTANDER' },
  { mpioCode: '44078', mpioName: 'BARRANCAS', deptoName: 'LA GUAJIRA' },
  { mpioCode: '13074', mpioName: 'BARRANCO DE LOBA', deptoName: 'BOLÍVAR' },
  { mpioCode: '94343', mpioName: 'BARRANCOMINAS', deptoName: 'GUAINÍA' },
  { mpioCode: '08001', mpioName: 'BARRANQUILLA', deptoName: 'ATLÁNTICO' },
  { mpioCode: '20045', mpioName: 'BECERRIL', deptoName: 'CESAR' },
  { mpioCode: '17088', mpioName: 'BELALCÁZAR', deptoName: 'CALDAS' },
  { mpioCode: '15087', mpioName: 'BELÉN', deptoName: 'BOYACÁ' },
  { mpioCode: '52083', mpioName: 'BELÉN', deptoName: 'NARIÑO' },
  { mpioCode: '18094', mpioName: 'BELÉN DE LOS ANDAQUÍES', deptoName: 'CAQUETÁ' },
  { mpioCode: '66088', mpioName: 'BELÉN DE UMBRÍA', deptoName: 'RISARALDA' },
  { mpioCode: '05088', mpioName: 'BELLO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05086', mpioName: 'BELMIRA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25086', mpioName: 'BELTRÁN', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15090', mpioName: 'BERBEO', deptoName: 'BOYACÁ' },
  { mpioCode: '05091', mpioName: 'BETANIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15092', mpioName: 'BETÉITIVA', deptoName: 'BOYACÁ' },
  { mpioCode: '05093', mpioName: 'BETULIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68092', mpioName: 'BETULIA', deptoName: 'SANTANDER' },
  { mpioCode: '25095', mpioName: 'BITUIMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15097', mpioName: 'BOAVITA', deptoName: 'BOYACÁ' },
  { mpioCode: '54099', mpioName: 'BOCHALEMA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '11001', mpioName: 'BOGOTÁ. D.C.', deptoName: 'BOGOTÁ. D.C.' },
  { mpioCode: '25099', mpioName: 'BOJACÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '27099', mpioName: 'BOJAYÁ', deptoName: 'CHOCÓ' },
  { mpioCode: '19100', mpioName: 'BOLÍVAR', deptoName: 'CAUCA' },
  { mpioCode: '68101', mpioName: 'BOLÍVAR', deptoName: 'SANTANDER' },
  { mpioCode: '76100', mpioName: 'BOLÍVAR', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '20060', mpioName: 'BOSCONIA', deptoName: 'CESAR' },
  { mpioCode: '15104', mpioName: 'BOYACÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '05107', mpioName: 'BRICEÑO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15106', mpioName: 'BRICEÑO', deptoName: 'BOYACÁ' },
  { mpioCode: '68001', mpioName: 'BUCARAMANGA', deptoName: 'SANTANDER' },
  { mpioCode: '54109', mpioName: 'BUCARASICA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '76109', mpioName: 'BUENAVENTURA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '15109', mpioName: 'BUENAVISTA', deptoName: 'BOYACÁ' },
  { mpioCode: '23079', mpioName: 'BUENAVISTA', deptoName: 'CÓRDOBA' },
  { mpioCode: '63111', mpioName: 'BUENAVISTA', deptoName: 'QUINDÍO' },
  { mpioCode: '70110', mpioName: 'BUENAVISTA', deptoName: 'SUCRE' },
  { mpioCode: '19110', mpioName: 'BUENOS AIRES', deptoName: 'CAUCA' },
  { mpioCode: '52110', mpioName: 'BUESACO', deptoName: 'NARIÑO' },
  { mpioCode: '76113', mpioName: 'BUGALAGRANDE', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '05113', mpioName: 'BURITICÁ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15114', mpioName: 'BUSBANZÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '25120', mpioName: 'CABRERA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '68121', mpioName: 'CABRERA', deptoName: 'SANTANDER' },
  { mpioCode: '50124', mpioName: 'CABUYARO', deptoName: 'META' },
  { mpioCode: '94886', mpioName: 'CACAHUAL', deptoName: 'GUAINÍA' },
  { mpioCode: '05120', mpioName: 'CÁCERES', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25123', mpioName: 'CACHIPAY', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '54128', mpioName: 'CÁCHIRA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '54125', mpioName: 'CÁCOTA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '05125', mpioName: 'CAICEDO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '76122', mpioName: 'CAICEDONIA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '70124', mpioName: 'CAIMITO', deptoName: 'SUCRE' },
  { mpioCode: '73124', mpioName: 'CAJAMARCA', deptoName: 'TOLIMA' },
  { mpioCode: '19130', mpioName: 'CAJIBÍO', deptoName: 'CAUCA' },
  { mpioCode: '25126', mpioName: 'CAJICÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '13140', mpioName: 'CALAMAR', deptoName: 'BOLÍVAR' },
  { mpioCode: '95015', mpioName: 'CALAMAR', deptoName: 'GUAVIARE' },
  { mpioCode: '63130', mpioName: 'CALARCÁ', deptoName: 'QUINDÍO' },
  { mpioCode: '05129', mpioName: 'CALDAS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15131', mpioName: 'CALDAS', deptoName: 'BOYACÁ' },
  { mpioCode: '19137', mpioName: 'CALDONO', deptoName: 'CAUCA' },
  { mpioCode: '76001', mpioName: 'CALI', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '68132', mpioName: 'CALIFORNIA', deptoName: 'SANTANDER' },
  { mpioCode: '76126', mpioName: 'CALIMA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '19142', mpioName: 'CALOTO', deptoName: 'CAUCA' },
  { mpioCode: '05134', mpioName: 'CAMPAMENTO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '08137', mpioName: 'CAMPO DE LA CRUZ', deptoName: 'ATLÁNTICO' },
  { mpioCode: '41132', mpioName: 'CAMPOALEGRE', deptoName: 'HUILA' },
  { mpioCode: '15135', mpioName: 'CAMPOHERMOSO', deptoName: 'BOYACÁ' },
  { mpioCode: '23090', mpioName: 'CANALETE', deptoName: 'CÓRDOBA' },
  { mpioCode: '08141', mpioName: 'CANDELARIA', deptoName: 'ATLÁNTICO' },
  { mpioCode: '76130', mpioName: 'CANDELARIA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '13160', mpioName: 'CANTAGALLO', deptoName: 'BOLÍVAR' },
  { mpioCode: '05138', mpioName: 'CAÑASGORDAS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25148', mpioName: 'CAPARRAPÍ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '68147', mpioName: 'CAPITANEJO', deptoName: 'SANTANDER' },
  { mpioCode: '25151', mpioName: 'CÁQUEZA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '05142', mpioName: 'CARACOLÍ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05145', mpioName: 'CARAMANTA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68152', mpioName: 'CARCASÍ', deptoName: 'SANTANDER' },
  { mpioCode: '05147', mpioName: 'CAREPA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '73148', mpioName: 'CARMEN DE APICALÁ', deptoName: 'TOLIMA' },
  { mpioCode: '25154', mpioName: 'CARMEN DE CARUPA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '27150', mpioName: 'CARMEN DEL DARIÉN', deptoName: 'CHOCÓ' },
  { mpioCode: '05150', mpioName: 'CAROLINA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '13001', mpioName: 'CARTAGENA DE INDIAS', deptoName: 'BOLÍVAR' },
  { mpioCode: '18150', mpioName: 'CARTAGENA DEL CHAIRÁ', deptoName: 'CAQUETÁ' },
  { mpioCode: '76147', mpioName: 'CARTAGO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '97161', mpioName: 'CARURÚ', deptoName: 'VAUPÉS' },
  { mpioCode: '73152', mpioName: 'CASABIANCA', deptoName: 'TOLIMA' },
  { mpioCode: '50150', mpioName: 'CASTILLA LA NUEVA', deptoName: 'META' },
  { mpioCode: '05154', mpioName: 'CAUCASIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68160', mpioName: 'CEPITÁ', deptoName: 'SANTANDER' },
  { mpioCode: '23162', mpioName: 'CERETÉ', deptoName: 'CÓRDOBA' },
  { mpioCode: '15162', mpioName: 'CERINZA', deptoName: 'BOYACÁ' },
  { mpioCode: '68162', mpioName: 'CERRITO', deptoName: 'SANTANDER' },
  { mpioCode: '47161', mpioName: 'CERRO DE SAN ANTONIO', deptoName: 'MAGDALENA' },
  { mpioCode: '27160', mpioName: 'CÉRTEGUI', deptoName: 'CHOCÓ' },
  { mpioCode: '52240', mpioName: 'CHACHAGÜÍ', deptoName: 'NARIÑO' },
  { mpioCode: '25168', mpioName: 'CHAGUANÍ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '70230', mpioName: 'CHALÁN', deptoName: 'SUCRE' },
  { mpioCode: '85015', mpioName: 'CHÁMEZA', deptoName: 'CASANARE' },
  { mpioCode: '73168', mpioName: 'CHAPARRAL', deptoName: 'TOLIMA' },
  { mpioCode: '68167', mpioName: 'CHARALÁ', deptoName: 'SANTANDER' },
  { mpioCode: '68169', mpioName: 'CHARTA', deptoName: 'SANTANDER' },
  { mpioCode: '25175', mpioName: 'CHÍA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '05172', mpioName: 'CHIGORODÓ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68176', mpioName: 'CHIMA', deptoName: 'SANTANDER' },
  { mpioCode: '23168', mpioName: 'CHIMÁ', deptoName: 'CÓRDOBA' },
  { mpioCode: '20175', mpioName: 'CHIMICHAGUA', deptoName: 'CESAR' },
  { mpioCode: '54172', mpioName: 'CHINÁCOTA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '15172', mpioName: 'CHINAVITA', deptoName: 'BOYACÁ' },
  { mpioCode: '17174', mpioName: 'CHINCHINÁ', deptoName: 'CALDAS' },
  { mpioCode: '23182', mpioName: 'CHINÚ', deptoName: 'CÓRDOBA' },
  { mpioCode: '25178', mpioName: 'CHIPAQUE', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '68179', mpioName: 'CHIPATÁ', deptoName: 'SANTANDER' },
  { mpioCode: '15176', mpioName: 'CHIQUINQUIRÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '15232', mpioName: 'CHÍQUIZA', deptoName: 'BOYACÁ' },
  { mpioCode: '20178', mpioName: 'CHIRIGUANÁ', deptoName: 'CESAR' },
  { mpioCode: '15180', mpioName: 'CHISCAS', deptoName: 'BOYACÁ' },
  { mpioCode: '15183', mpioName: 'CHITA', deptoName: 'BOYACÁ' },
  { mpioCode: '54174', mpioName: 'CHITAGÁ', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '15185', mpioName: 'CHITARAQUE', deptoName: 'BOYACÁ' },
  { mpioCode: '15187', mpioName: 'CHIVATÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '47170', mpioName: 'CHIVOLO', deptoName: 'MAGDALENA' },
  { mpioCode: '15236', mpioName: 'CHIVOR', deptoName: 'BOYACÁ' },
  { mpioCode: '25181', mpioName: 'CHOACHÍ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25183', mpioName: 'CHOCONTÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '13188', mpioName: 'CICUCO', deptoName: 'BOLÍVAR' },
  { mpioCode: '47189', mpioName: 'CIÉNAGA', deptoName: 'MAGDALENA' },
  { mpioCode: '23189', mpioName: 'CIÉNAGA DE ORO', deptoName: 'CÓRDOBA' },
  { mpioCode: '15189', mpioName: 'CIÉNEGA', deptoName: 'BOYACÁ' },
  { mpioCode: '68190', mpioName: 'CIMITARRA', deptoName: 'SANTANDER' },
  { mpioCode: '63190', mpioName: 'CIRCASIA', deptoName: 'QUINDÍO' },
  { mpioCode: '05190', mpioName: 'CISNEROS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05101', mpioName: 'CIUDAD BOLÍVAR', deptoName: 'ANTIOQUIA' },
  { mpioCode: '13222', mpioName: 'CLEMENCIA', deptoName: 'BOLÍVAR' },
  { mpioCode: '05197', mpioName: 'COCORNÁ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '73200', mpioName: 'COELLO', deptoName: 'TOLIMA' },
  { mpioCode: '25200', mpioName: 'COGUA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '41206', mpioName: 'COLOMBIA', deptoName: 'HUILA' },
  { mpioCode: '52203', mpioName: 'COLÓN', deptoName: 'NARIÑO' },
  { mpioCode: '86219', mpioName: 'COLÓN', deptoName: 'PUTUMAYO' },
  { mpioCode: '70204', mpioName: 'COLOSÓ', deptoName: 'SUCRE' },
  { mpioCode: '15204', mpioName: 'CÓMBITA', deptoName: 'BOYACÁ' },
  { mpioCode: '05206', mpioName: 'CONCEPCIÓN', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68207', mpioName: 'CONCEPCIÓN', deptoName: 'SANTANDER' },
  { mpioCode: '05209', mpioName: 'CONCORDIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '47205', mpioName: 'CONCORDIA', deptoName: 'MAGDALENA' },
  { mpioCode: '27205', mpioName: 'CONDOTO', deptoName: 'CHOCÓ' },
  { mpioCode: '68209', mpioName: 'CONFINES', deptoName: 'SANTANDER' },
  { mpioCode: '52207', mpioName: 'CONSACÁ', deptoName: 'NARIÑO' },
  { mpioCode: '52210', mpioName: 'CONTADERO', deptoName: 'NARIÑO' },
  { mpioCode: '68211', mpioName: 'CONTRATACIÓN', deptoName: 'SANTANDER' },
  { mpioCode: '54206', mpioName: 'CONVENCIÓN', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '05212', mpioName: 'COPACABANA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15212', mpioName: 'COPER', deptoName: 'BOYACÁ' },
  { mpioCode: '13212', mpioName: 'CÓRDOBA', deptoName: 'BOLÍVAR' },
  { mpioCode: '52215', mpioName: 'CÓRDOBA', deptoName: 'NARIÑO' },
  { mpioCode: '63212', mpioName: 'CÓRDOBA', deptoName: 'QUINDÍO' },
  { mpioCode: '19212', mpioName: 'CORINTO', deptoName: 'CAUCA' },
  { mpioCode: '68217', mpioName: 'COROMORO', deptoName: 'SANTANDER' },
  { mpioCode: '70215', mpioName: 'COROZAL', deptoName: 'SUCRE' },
  { mpioCode: '15215', mpioName: 'CORRALES', deptoName: 'BOYACÁ' },
  { mpioCode: '25214', mpioName: 'COTA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '23300', mpioName: 'COTORRA', deptoName: 'CÓRDOBA' },
  { mpioCode: '15218', mpioName: 'COVARACHÍA', deptoName: 'BOYACÁ' },
  { mpioCode: '70221', mpioName: 'COVEÑAS', deptoName: 'SUCRE' },
  { mpioCode: '73217', mpioName: 'COYAIMA', deptoName: 'TOLIMA' },
  { mpioCode: '81220', mpioName: 'CRAVO NORTE', deptoName: 'ARAUCA' },
  { mpioCode: '52224', mpioName: 'CUASPUD CARLOSAMA', deptoName: 'NARIÑO' },
  { mpioCode: '15223', mpioName: 'CUBARÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '50223', mpioName: 'CUBARRAL', deptoName: 'META' },
  { mpioCode: '15224', mpioName: 'CUCAITA', deptoName: 'BOYACÁ' },
  { mpioCode: '25224', mpioName: 'CUCUNUBÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '54223', mpioName: 'CUCUTILLA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '15226', mpioName: 'CUÍTIVA', deptoName: 'BOYACÁ' },
  { mpioCode: '50226', mpioName: 'CUMARAL', deptoName: 'META' },
  { mpioCode: '99773', mpioName: 'CUMARIBO', deptoName: 'VICHADA' },
  { mpioCode: '52227', mpioName: 'CUMBAL', deptoName: 'NARIÑO' },
  { mpioCode: '52233', mpioName: 'CUMBITARA', deptoName: 'NARIÑO' },
  { mpioCode: '73226', mpioName: 'CUNDAY', deptoName: 'TOLIMA' },
  { mpioCode: '18205', mpioName: 'CURILLO', deptoName: 'CAQUETÁ' },
  { mpioCode: '68229', mpioName: 'CURITÍ', deptoName: 'SANTANDER' },
  { mpioCode: '20228', mpioName: 'CURUMANÍ', deptoName: 'CESAR' },
  { mpioCode: '05234', mpioName: 'DABEIBA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '76233', mpioName: 'DAGUA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '44090', mpioName: 'DIBULLA', deptoName: 'LA GUAJIRA' },
  { mpioCode: '44098', mpioName: 'DISTRACCIÓN', deptoName: 'LA GUAJIRA' },
  { mpioCode: '73236', mpioName: 'DOLORES', deptoName: 'TOLIMA' },
  { mpioCode: '05237', mpioName: 'DONMATÍAS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '66170', mpioName: 'DOSQUEBRADAS', deptoName: 'RISARALDA' },
  { mpioCode: '15238', mpioName: 'DUITAMA', deptoName: 'BOYACÁ' },
  { mpioCode: '54239', mpioName: 'DURANIA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '05240', mpioName: 'EBÉJICO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '76243', mpioName: 'EL ÁGUILA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '05250', mpioName: 'EL BAGRE', deptoName: 'ANTIOQUIA' },
  { mpioCode: '47245', mpioName: 'EL BANCO', deptoName: 'MAGDALENA' },
  { mpioCode: '76246', mpioName: 'EL CAIRO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '50245', mpioName: 'EL CALVARIO', deptoName: 'META' },
  { mpioCode: '27135', mpioName: 'EL CANTÓN DEL SAN PABLO', deptoName: 'CHOCÓ' },
  { mpioCode: '54245', mpioName: 'EL CARMEN', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '27245', mpioName: 'EL CARMEN DE ATRATO', deptoName: 'CHOCÓ' },
  { mpioCode: '13244', mpioName: 'EL CARMEN DE BOLÍVAR', deptoName: 'BOLÍVAR' },
  { mpioCode: '68235', mpioName: 'EL CARMEN DE CHUCURI', deptoName: 'SANTANDER' },
  { mpioCode: '05148', mpioName: 'EL CARMEN DE VIBORAL', deptoName: 'ANTIOQUIA' },
  { mpioCode: '50251', mpioName: 'EL CASTILLO', deptoName: 'META' },
  { mpioCode: '76248', mpioName: 'EL CERRITO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '52250', mpioName: 'EL CHARCO', deptoName: 'NARIÑO' },
  { mpioCode: '15244', mpioName: 'EL COCUY', deptoName: 'BOYACÁ' },
  { mpioCode: '25245', mpioName: 'EL COLEGIO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '20238', mpioName: 'EL COPEY', deptoName: 'CESAR' },
  { mpioCode: '18247', mpioName: 'EL DONCELLO', deptoName: 'CAQUETÁ' },
  { mpioCode: '50270', mpioName: 'EL DORADO', deptoName: 'META' },
  { mpioCode: '76250', mpioName: 'EL DOVIO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '91263', mpioName: 'EL ENCANTO', deptoName: 'AMAZONAS' },
  { mpioCode: '15248', mpioName: 'EL ESPINO', deptoName: 'BOYACÁ' },
  { mpioCode: '68245', mpioName: 'EL GUACAMAYO', deptoName: 'SANTANDER' },
  { mpioCode: '13248', mpioName: 'EL GUAMO', deptoName: 'BOLÍVAR' },
  { mpioCode: '27250', mpioName: 'EL LITORAL DEL SAN JUAN', deptoName: 'CHOCÓ' },
  { mpioCode: '44110', mpioName: 'EL MOLINO', deptoName: 'LA GUAJIRA' },
  { mpioCode: '20250', mpioName: 'EL PASO', deptoName: 'CESAR' },
  { mpioCode: '18256', mpioName: 'EL PAUJÍL', deptoName: 'CAQUETÁ' },
  { mpioCode: '52254', mpioName: 'EL PEÑOL', deptoName: 'NARIÑO' },
  { mpioCode: '13268', mpioName: 'EL PEÑÓN', deptoName: 'BOLÍVAR' },
  { mpioCode: '25258', mpioName: 'EL PEÑÓN', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '68250', mpioName: 'EL PEÑÓN', deptoName: 'SANTANDER' },
  { mpioCode: '47258', mpioName: 'EL PIÑÓN', deptoName: 'MAGDALENA' },
  { mpioCode: '68255', mpioName: 'EL PLAYÓN', deptoName: 'SANTANDER' },
  { mpioCode: '47268', mpioName: 'EL RETÉN', deptoName: 'MAGDALENA' },
  { mpioCode: '95025', mpioName: 'EL RETORNO', deptoName: 'GUAVIARE' },
  { mpioCode: '70233', mpioName: 'EL ROBLE', deptoName: 'SUCRE' },
  { mpioCode: '25260', mpioName: 'EL ROSAL', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52256', mpioName: 'EL ROSARIO', deptoName: 'NARIÑO' },
  { mpioCode: '05697', mpioName: 'EL SANTUARIO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '52258', mpioName: 'EL TABLÓN DE GÓMEZ', deptoName: 'NARIÑO' },
  { mpioCode: '19256', mpioName: 'EL TAMBO', deptoName: 'CAUCA' },
  { mpioCode: '52260', mpioName: 'EL TAMBO', deptoName: 'NARIÑO' },
  { mpioCode: '54250', mpioName: 'EL TARRA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '54261', mpioName: 'EL ZULIA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '41244', mpioName: 'ELÍAS', deptoName: 'HUILA' },
  { mpioCode: '68264', mpioName: 'ENCINO', deptoName: 'SANTANDER' },
  { mpioCode: '68266', mpioName: 'ENCISO', deptoName: 'SANTANDER' },
  { mpioCode: '05264', mpioName: 'ENTRERRÍOS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05266', mpioName: 'ENVIGADO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '73268', mpioName: 'ESPINAL', deptoName: 'TOLIMA' },
  { mpioCode: '25269', mpioName: 'FACATATIVÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '73270', mpioName: 'FALAN', deptoName: 'TOLIMA' },
  { mpioCode: '17272', mpioName: 'FILADELFIA', deptoName: 'CALDAS' },
  { mpioCode: '63272', mpioName: 'FILANDIA', deptoName: 'QUINDÍO' },
  { mpioCode: '15272', mpioName: 'FIRAVITOBA', deptoName: 'BOYACÁ' },
  { mpioCode: '73275', mpioName: 'FLANDES', deptoName: 'TOLIMA' },
  { mpioCode: '18001', mpioName: 'FLORENCIA', deptoName: 'CAQUETÁ' },
  { mpioCode: '19290', mpioName: 'FLORENCIA', deptoName: 'CAUCA' },
  { mpioCode: '15276', mpioName: 'FLORESTA', deptoName: 'BOYACÁ' },
  { mpioCode: '68271', mpioName: 'FLORIÁN', deptoName: 'SANTANDER' },
  { mpioCode: '76275', mpioName: 'FLORIDA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '68276', mpioName: 'FLORIDABLANCA', deptoName: 'SANTANDER' },
  { mpioCode: '25279', mpioName: 'FÓMEQUE', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '44279', mpioName: 'FONSECA', deptoName: 'LA GUAJIRA' },
  { mpioCode: '81300', mpioName: 'FORTUL', deptoName: 'ARAUCA' },
  { mpioCode: '25281', mpioName: 'FOSCA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52520', mpioName: 'FRANCISCO PIZARRO', deptoName: 'NARIÑO' },
  { mpioCode: '05282', mpioName: 'FREDONIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '73283', mpioName: 'FRESNO', deptoName: 'TOLIMA' },
  { mpioCode: '05284', mpioName: 'FRONTINO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '50287', mpioName: 'FUENTE DE ORO', deptoName: 'META' },
  { mpioCode: '47288', mpioName: 'FUNDACIÓN', deptoName: 'MAGDALENA' },
  { mpioCode: '52287', mpioName: 'FUNES', deptoName: 'NARIÑO' },
  { mpioCode: '25286', mpioName: 'FUNZA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25288', mpioName: 'FÚQUENE', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25290', mpioName: 'FUSAGASUGÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25293', mpioName: 'GACHALÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25295', mpioName: 'GACHANCIPÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15293', mpioName: 'GACHANTIVÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '25297', mpioName: 'GACHETÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '68296', mpioName: 'GALÁN', deptoName: 'SANTANDER' },
  { mpioCode: '08296', mpioName: 'GALAPA', deptoName: 'ATLÁNTICO' },
  { mpioCode: '70235', mpioName: 'GALERAS', deptoName: 'SUCRE' },
  { mpioCode: '25299', mpioName: 'GAMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '20295', mpioName: 'GAMARRA', deptoName: 'CESAR' },
  { mpioCode: '68298', mpioName: 'GÁMBITA', deptoName: 'SANTANDER' },
  { mpioCode: '15296', mpioName: 'GÁMEZA', deptoName: 'BOYACÁ' },
  { mpioCode: '15299', mpioName: 'GARAGOA', deptoName: 'BOYACÁ' },
  { mpioCode: '41298', mpioName: 'GARZÓN', deptoName: 'HUILA' },
  { mpioCode: '63302', mpioName: 'GÉNOVA', deptoName: 'QUINDÍO' },
  { mpioCode: '41306', mpioName: 'GIGANTE', deptoName: 'HUILA' },
  { mpioCode: '76306', mpioName: 'GINEBRA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '05306', mpioName: 'GIRALDO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25307', mpioName: 'GIRARDOT', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '05308', mpioName: 'GIRARDOTA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68307', mpioName: 'GIRÓN', deptoName: 'SANTANDER' },
  { mpioCode: '05310', mpioName: 'GÓMEZ PLATA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '20310', mpioName: 'GONZÁLEZ', deptoName: 'CESAR' },
  { mpioCode: '54313', mpioName: 'GRAMALOTE', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '05313', mpioName: 'GRANADA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25312', mpioName: 'GRANADA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '50313', mpioName: 'GRANADA', deptoName: 'META' },
  { mpioCode: '68318', mpioName: 'GUACA', deptoName: 'SANTANDER' },
  { mpioCode: '15317', mpioName: 'GUACAMAYAS', deptoName: 'BOYACÁ' },
  { mpioCode: '76318', mpioName: 'GUACARÍ', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '19300', mpioName: 'GUACHENÉ', deptoName: 'CAUCA' },
  { mpioCode: '25317', mpioName: 'GUACHETÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52317', mpioName: 'GUACHUCAL', deptoName: 'NARIÑO' },
  { mpioCode: '76111', mpioName: 'GUADALAJARA DE BUGA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '05315', mpioName: 'GUADALUPE', deptoName: 'ANTIOQUIA' },
  { mpioCode: '41319', mpioName: 'GUADALUPE', deptoName: 'HUILA' },
  { mpioCode: '68320', mpioName: 'GUADALUPE', deptoName: 'SANTANDER' },
  { mpioCode: '25320', mpioName: 'GUADUAS', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52320', mpioName: 'GUAITARILLA', deptoName: 'NARIÑO' },
  { mpioCode: '52323', mpioName: 'GUALMATÁN', deptoName: 'NARIÑO' },
  { mpioCode: '47318', mpioName: 'GUAMAL', deptoName: 'MAGDALENA' },
  { mpioCode: '50318', mpioName: 'GUAMAL', deptoName: 'META' },
  { mpioCode: '73319', mpioName: 'GUAMO', deptoName: 'TOLIMA' },
  { mpioCode: '19318', mpioName: 'GUAPI', deptoName: 'CAUCA' },
  { mpioCode: '68322', mpioName: 'GUAPOTÁ', deptoName: 'SANTANDER' },
  { mpioCode: '70265', mpioName: 'GUARANDA', deptoName: 'SUCRE' },
  { mpioCode: '05318', mpioName: 'GUARNE', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25322', mpioName: 'GUASCA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '05321', mpioName: 'GUATAPÉ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25324', mpioName: 'GUATAQUÍ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25326', mpioName: 'GUATAVITA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15322', mpioName: 'GUATEQUE', deptoName: 'BOYACÁ' },
  { mpioCode: '66318', mpioName: 'GUÁTICA', deptoName: 'RISARALDA' },
  { mpioCode: '68324', mpioName: 'GUAVATÁ', deptoName: 'SANTANDER' },
  { mpioCode: '25328', mpioName: 'GUAYABAL DE SÍQUIMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25335', mpioName: 'GUAYABETAL', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15325', mpioName: 'GUAYATÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '68327', mpioName: 'GÜEPSA', deptoName: 'SANTANDER' },
  { mpioCode: '15332', mpioName: 'GÜICÁN DE LA SIERRA', deptoName: 'BOYACÁ' },
  { mpioCode: '25339', mpioName: 'GUTIÉRREZ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '54344', mpioName: 'HACARÍ', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '13300', mpioName: 'HATILLO DE LOBA', deptoName: 'BOLÍVAR' },
  { mpioCode: '68344', mpioName: 'HATO', deptoName: 'SANTANDER' },
  { mpioCode: '85125', mpioName: 'HATO COROZAL', deptoName: 'CASANARE' },
  { mpioCode: '44378', mpioName: 'HATONUEVO', deptoName: 'LA GUAJIRA' },
  { mpioCode: '05347', mpioName: 'HELICONIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '54347', mpioName: 'HERRÁN', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '73347', mpioName: 'HERVEO', deptoName: 'TOLIMA' },
  { mpioCode: '05353', mpioName: 'HISPANIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '41349', mpioName: 'HOBO', deptoName: 'HUILA' },
  { mpioCode: '73349', mpioName: 'HONDA', deptoName: 'TOLIMA' },
  { mpioCode: '73001', mpioName: 'IBAGUÉ', deptoName: 'TOLIMA' },
  { mpioCode: '73352', mpioName: 'ICONONZO', deptoName: 'TOLIMA' },
  { mpioCode: '52352', mpioName: 'ILES', deptoName: 'NARIÑO' },
  { mpioCode: '52354', mpioName: 'IMUÉS', deptoName: 'NARIÑO' },
  { mpioCode: '94001', mpioName: 'INÍRIDA', deptoName: 'GUAINÍA' },
  { mpioCode: '19355', mpioName: 'INZÁ', deptoName: 'CAUCA' },
  { mpioCode: '52356', mpioName: 'IPIALES', deptoName: 'NARIÑO' },
  { mpioCode: '41357', mpioName: 'ÍQUIRA', deptoName: 'HUILA' },
  { mpioCode: '41359', mpioName: 'ISNOS', deptoName: 'HUILA' },
  { mpioCode: '27361', mpioName: 'ISTMINA', deptoName: 'CHOCÓ' },
  { mpioCode: '05360', mpioName: 'ITAGÜÍ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05361', mpioName: 'ITUANGO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15362', mpioName: 'IZA', deptoName: 'BOYACÁ' },
  { mpioCode: '19364', mpioName: 'JAMBALÓ', deptoName: 'CAUCA' },
  { mpioCode: '76364', mpioName: 'JAmpioNameDÍ', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '05364', mpioName: 'JARDÍN', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15367', mpioName: 'JENESANO', deptoName: 'BOYACÁ' },
  { mpioCode: '05368', mpioName: 'JERICÓ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15368', mpioName: 'JERICÓ', deptoName: 'BOYACÁ' },
  { mpioCode: '25368', mpioName: 'JERUSALÉN', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '68368', mpioName: 'JESÚS MARÍA', deptoName: 'SANTANDER' },
  { mpioCode: '68370', mpioName: 'JORDÁN', deptoName: 'SANTANDER' },
  { mpioCode: '08372', mpioName: 'JUAN DE ACOSTA', deptoName: 'ATLÁNTICO' },
  { mpioCode: '25372', mpioName: 'JUNÍN', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '27372', mpioName: 'JURADÓ', deptoName: 'CHOCÓ' },
  { mpioCode: '23350', mpioName: 'LA APARTADA', deptoName: 'CÓRDOBA' },
  { mpioCode: '41378', mpioName: 'LA ARGENTINA', deptoName: 'HUILA' },
  { mpioCode: '68377', mpioName: 'LA BELLEZA', deptoName: 'SANTANDER' },
  { mpioCode: '25377', mpioName: 'LA CALERA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15380', mpioName: 'LA CAPILLA', deptoName: 'BOYACÁ' },
  { mpioCode: '05376', mpioName: 'LA CEJA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '66383', mpioName: 'LA CELIA', deptoName: 'RISARALDA' },
  { mpioCode: '91405', mpioName: 'LA CHORRERA', deptoName: 'AMAZONAS' },
  { mpioCode: '52378', mpioName: 'LA CRUZ', deptoName: 'NARIÑO' },
  { mpioCode: '76377', mpioName: 'LA CUMBRE', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '17380', mpioName: 'LA DORADA', deptoName: 'CALDAS' },
  { mpioCode: '54385', mpioName: 'LA ESPERANZA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '05380', mpioName: 'LA ESTRELLA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '52381', mpioName: 'LA FLORIDA', deptoName: 'NARIÑO' },
  { mpioCode: '20383', mpioName: 'LA GLORIA', deptoName: 'CESAR' },
  { mpioCode: '94885', mpioName: 'LA GUADALUPE', deptoName: 'GUAINÍA' },
  { mpioCode: '20400', mpioName: 'LA JAGUA DE IBIRICO', deptoName: 'CESAR' },
  { mpioCode: '44420', mpioName: 'LA JAGUA DEL PILAR', deptoName: 'LA GUAJIRA' },
  { mpioCode: '52385', mpioName: 'LA LLANADA', deptoName: 'NARIÑO' },
  { mpioCode: '50350', mpioName: 'LA MACARENA', deptoName: 'META' },
  { mpioCode: '17388', mpioName: 'LA MERCED', deptoName: 'CALDAS' },
  { mpioCode: '25386', mpioName: 'LA MESA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '18410', mpioName: 'LA MONTAÑITA', deptoName: 'CAQUETÁ' },
  { mpioCode: '25394', mpioName: 'LA PALMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '20621', mpioName: 'LA PAZ', deptoName: 'CESAR' },
  { mpioCode: '68397', mpioName: 'LA PAZ', deptoName: 'SANTANDER' },
  { mpioCode: '91407', mpioName: 'LA PEDRERA', deptoName: 'AMAZONAS' },
  { mpioCode: '25398', mpioName: 'LA PEÑA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '05390', mpioName: 'LA PINTADA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '41396', mpioName: 'LA PLATA', deptoName: 'HUILA' },
  { mpioCode: '54398', mpioName: 'LA PLAYA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '99524', mpioName: 'LA PRIMAVERA', deptoName: 'VICHADA' },
  { mpioCode: '85136', mpioName: 'LA SALINA', deptoName: 'CASANARE' },
  { mpioCode: '19392', mpioName: 'LA SIERRA', deptoName: 'CAUCA' },
  { mpioCode: '63401', mpioName: 'LA TEBAIDA', deptoName: 'QUINDÍO' },
  { mpioCode: '52390', mpioName: 'LA TOLA', deptoName: 'NARIÑO' },
  { mpioCode: '05400', mpioName: 'LA UNIÓN', deptoName: 'ANTIOQUIA' },
  { mpioCode: '52399', mpioName: 'LA UNIÓN', deptoName: 'NARIÑO' },
  { mpioCode: '70400', mpioName: 'LA UNIÓN', deptoName: 'SUCRE' },
  { mpioCode: '76400', mpioName: 'LA UNIÓN', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '15403', mpioName: 'LA UVITA', deptoName: 'BOYACÁ' },
  { mpioCode: '19397', mpioName: 'LA VEGA', deptoName: 'CAUCA' },
  { mpioCode: '25402', mpioName: 'LA VEGA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '91430', mpioName: 'LA VICTORIA', deptoName: 'AMAZONAS' },
  { mpioCode: '15401', mpioName: 'LA VICTORIA', deptoName: 'BOYACÁ' },
  { mpioCode: '76403', mpioName: 'LA VICTORIA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '66400', mpioName: 'LA VIRGINIA', deptoName: 'RISARALDA' },
  { mpioCode: '54377', mpioName: 'LABATECA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '15377', mpioName: 'LABRANZAGRANDE', deptoName: 'BOYACÁ' },
  { mpioCode: '68385', mpioName: 'LANDÁZURI', deptoName: 'SANTANDER' },
  { mpioCode: '68406', mpioName: 'LEBRIJA', deptoName: 'SANTANDER' },
  { mpioCode: '52405', mpioName: 'LEIVA', deptoName: 'NARIÑO' },
  { mpioCode: '50400', mpioName: 'LEJANÍAS', deptoName: 'META' },
  { mpioCode: '25407', mpioName: 'LENGUAZAQUE', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '73408', mpioName: 'LÉRIDA', deptoName: 'TOLIMA' },
  { mpioCode: '91001', mpioName: 'LETICIA', deptoName: 'AMAZONAS' },
  { mpioCode: '73411', mpioName: 'LÍBANO', deptoName: 'TOLIMA' },
  { mpioCode: '05411', mpioName: 'LIBORINA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '52411', mpioName: 'LINARES', deptoName: 'NARIÑO' },
  { mpioCode: '27413', mpioName: 'LLORÓ', deptoName: 'CHOCÓ' },
  { mpioCode: '19418', mpioName: 'LÓPEZ DE MICAY', deptoName: 'CAUCA' },
  { mpioCode: '23417', mpioName: 'LORICA', deptoName: 'CÓRDOBA' },
  { mpioCode: '52418', mpioName: 'LOS ANDES', deptoName: 'NARIÑO' },
  { mpioCode: '23419', mpioName: 'LOS CÓRDOBAS', deptoName: 'CÓRDOBA' },
  { mpioCode: '70418', mpioName: 'LOS PALMITOS', deptoName: 'SUCRE' },
  { mpioCode: '54405', mpioName: 'LOS PATIOS', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '68418', mpioName: 'LOS SANTOS', deptoName: 'SANTANDER' },
  { mpioCode: '54418', mpioName: 'LOURDES', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '08421', mpioName: 'LURUACO', deptoName: 'ATLÁNTICO' },
  { mpioCode: '15425', mpioName: 'MACANAL', deptoName: 'BOYACÁ' },
  { mpioCode: '68425', mpioName: 'MACARAVITA', deptoName: 'SANTANDER' },
  { mpioCode: '05425', mpioName: 'MACEO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25426', mpioName: 'MACHETÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25430', mpioName: 'MADRID', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '13430', mpioName: 'MAGANGUÉ', deptoName: 'BOLÍVAR' },
  { mpioCode: '52427', mpioName: 'MAGÜÍ', deptoName: 'NARIÑO' },
  { mpioCode: '13433', mpioName: 'MAHATES', deptoName: 'BOLÍVAR' },
  { mpioCode: '44430', mpioName: 'MAICAO', deptoName: 'LA GUAJIRA' },
  { mpioCode: '70429', mpioName: 'MAJAGUAL', deptoName: 'SUCRE' },
  { mpioCode: '68432', mpioName: 'MÁLAGA', deptoName: 'SANTANDER' },
  { mpioCode: '08433', mpioName: 'MALAMBO', deptoName: 'ATLÁNTICO' },
  { mpioCode: '52435', mpioName: 'MALLAMA', deptoName: 'NARIÑO' },
  { mpioCode: '08436', mpioName: 'MANATÍ', deptoName: 'ATLÁNTICO' },
  { mpioCode: '44560', mpioName: 'MANAURE', deptoName: 'LA GUAJIRA' },
  { mpioCode: '20443', mpioName: 'MANAURE BALCÓN DEL CESAR', deptoName: 'CESAR' },
  { mpioCode: '85139', mpioName: 'MANÍ', deptoName: 'CASANARE' },
  { mpioCode: '17001', mpioName: 'MANIZALES', deptoName: 'CALDAS' },
  { mpioCode: '25436', mpioName: 'MANTA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '17433', mpioName: 'MANZANARES', deptoName: 'CALDAS' },
  { mpioCode: '50325', mpioName: 'MAPIRIPÁN', deptoName: 'META' },
  { mpioCode: '13440', mpioName: 'MARGARITA', deptoName: 'BOLÍVAR' },
  { mpioCode: '13442', mpioName: 'MARÍA LA BAJA', deptoName: 'BOLÍVAR' },
  { mpioCode: '05440', mpioName: 'MARINILLA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15442', mpioName: 'MARIPÍ', deptoName: 'BOYACÁ' },
  { mpioCode: '17442', mpioName: 'MARMATO', deptoName: 'CALDAS' },
  { mpioCode: '17444', mpioName: 'MARQUETALIA', deptoName: 'CALDAS' },
  { mpioCode: '66440', mpioName: 'MARSELLA', deptoName: 'RISARALDA' },
  { mpioCode: '17446', mpioName: 'MARULANDA', deptoName: 'CALDAS' },
  { mpioCode: '68444', mpioName: 'MATANZA', deptoName: 'SANTANDER' },
  { mpioCode: '05001', mpioName: 'MEDELLÍN', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25438', mpioName: 'MEDINA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '27425', mpioName: 'MEDIO ATRATO', deptoName: 'CHOCÓ' },
  { mpioCode: '27430', mpioName: 'MEDIO BAUDÓ', deptoName: 'CHOCÓ' },
  { mpioCode: '27450', mpioName: 'MEDIO SAN JUAN', deptoName: 'CHOCÓ' },
  { mpioCode: '73449', mpioName: 'MELGAR', deptoName: 'TOLIMA' },
  { mpioCode: '19450', mpioName: 'MERCADERES', deptoName: 'CAUCA' },
  { mpioCode: '50330', mpioName: 'MESETAS', deptoName: 'META' },
  { mpioCode: '18460', mpioName: 'MILÁN', deptoName: 'CAQUETÁ' },
  { mpioCode: '15455', mpioName: 'MIRAFLORES', deptoName: 'BOYACÁ' },
  { mpioCode: '95200', mpioName: 'MIRAFLORES', deptoName: 'GUAVIARE' },
  { mpioCode: '19455', mpioName: 'MIRANDA', deptoName: 'CAUCA' },
  { mpioCode: '91460', mpioName: 'MIRITÍ – PARANÁ', deptoName: 'AMAZONAS' },
  { mpioCode: '66456', mpioName: 'MISTRATÓ', deptoName: 'RISARALDA' },
  { mpioCode: '97001', mpioName: 'MITÚ', deptoName: 'VAUPÉS' },
  { mpioCode: '86001', mpioName: 'MOCOA', deptoName: 'PUTUMAYO' },
  { mpioCode: '68464', mpioName: 'MOGOTES', deptoName: 'SANTANDER' },
  { mpioCode: '68468', mpioName: 'MOLAGAVITA', deptoName: 'SANTANDER' },
  { mpioCode: '23464', mpioName: 'MOMIL', deptoName: 'CÓRDOBA' },
  { mpioCode: '15464', mpioName: 'MONGUA', deptoName: 'BOYACÁ' },
  { mpioCode: '15466', mpioName: 'MONGUÍ', deptoName: 'BOYACÁ' },
  { mpioCode: '15469', mpioName: 'MONIQUIRÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '05467', mpioName: 'MONTEBELLO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '13458', mpioName: 'MONTECRISTO', deptoName: 'BOLÍVAR' },
  { mpioCode: '23466', mpioName: 'MONTELÍBANO', deptoName: 'CÓRDOBA' },
  { mpioCode: '63470', mpioName: 'MONTENEGRO', deptoName: 'QUINDÍO' },
  { mpioCode: '23001', mpioName: 'MONTERÍA', deptoName: 'CÓRDOBA' },
  { mpioCode: '85162', mpioName: 'MONTERREY', deptoName: 'CASANARE' },
  { mpioCode: '23500', mpioName: 'MOÑITOS', deptoName: 'CÓRDOBA' },
  { mpioCode: '13473', mpioName: 'MORALES', deptoName: 'BOLÍVAR' },
  { mpioCode: '19473', mpioName: 'MORALES', deptoName: 'CAUCA' },
  { mpioCode: '18479', mpioName: 'MORELIA', deptoName: 'CAQUETÁ' },
  { mpioCode: '94888', mpioName: 'MORICHAL', deptoName: 'GUAINÍA' },
  { mpioCode: '70473', mpioName: 'MORROA', deptoName: 'SUCRE' },
  { mpioCode: '25473', mpioName: 'MOSQUERA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52473', mpioName: 'MOSQUERA', deptoName: 'NARIÑO' },
  { mpioCode: '15476', mpioName: 'MOTAVITA', deptoName: 'BOYACÁ' },
  { mpioCode: '73461', mpioName: 'MURILLO', deptoName: 'TOLIMA' },
  { mpioCode: '05475', mpioName: 'MURINDÓ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05480', mpioName: 'MUTATÁ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '54480', mpioName: 'MUTISCUA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '15480', mpioName: 'MUZO', deptoName: 'BOYACÁ' },
  { mpioCode: '05483', mpioName: 'NARIÑO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25483', mpioName: 'NARIÑO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52480', mpioName: 'NARIÑO', deptoName: 'NARIÑO' },
  { mpioCode: '41483', mpioName: 'NÁTAGA', deptoName: 'HUILA' },
  { mpioCode: '73483', mpioName: 'NATAGAIMA', deptoName: 'TOLIMA' },
  { mpioCode: '05495', mpioName: 'NECHÍ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05490', mpioName: 'NECOCLÍ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '17486', mpioName: 'NEIRA', deptoName: 'CALDAS' },
  { mpioCode: '41001', mpioName: 'NEIVA', deptoName: 'HUILA' },
  { mpioCode: '25486', mpioName: 'NEMOCÓN', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25488', mpioName: 'NILO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25489', mpioName: 'NIMAIMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15491', mpioName: 'NOBSA', deptoName: 'BOYACÁ' },
  { mpioCode: '25491', mpioName: 'NOCAIMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '17495', mpioName: 'NORCASIA', deptoName: 'CALDAS' },
  { mpioCode: '13490', mpioName: 'NOROSÍ', deptoName: 'BOLÍVAR' },
  { mpioCode: '27491', mpioName: 'NÓVITA', deptoName: 'CHOCÓ' },
  { mpioCode: '47460', mpioName: 'NUEVA GRANADA', deptoName: 'MAGDALENA' },
  { mpioCode: '15494', mpioName: 'NUEVO COLÓN', deptoName: 'BOYACÁ' },
  { mpioCode: '85225', mpioName: 'NUNCHÍA', deptoName: 'CASANARE' },
  { mpioCode: '27495', mpioName: 'NUQUÍ', deptoName: 'CHOCÓ' },
  { mpioCode: '76497', mpioName: 'OBANDO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '68498', mpioName: 'OCAMONTE', deptoName: 'SANTANDER' },
  { mpioCode: '54498', mpioName: 'OCAÑA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '68500', mpioName: 'OIBA', deptoName: 'SANTANDER' },
  { mpioCode: '15500', mpioName: 'OICATÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '05501', mpioName: 'OLAYA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '52490', mpioName: 'OLAYA HERRERA', deptoName: 'NARIÑO' },
  { mpioCode: '68502', mpioName: 'ONZAGA', deptoName: 'SANTANDER' },
  { mpioCode: '41503', mpioName: 'OPORAPA', deptoName: 'HUILA' },
  { mpioCode: '86320', mpioName: 'ORITO', deptoName: 'PUTUMAYO' },
  { mpioCode: '85230', mpioName: 'OROCUÉ', deptoName: 'CASANARE' },
  { mpioCode: '73504', mpioName: 'ORTEGA', deptoName: 'TOLIMA' },
  { mpioCode: '52506', mpioName: 'OSPINA', deptoName: 'NARIÑO' },
  { mpioCode: '15507', mpioName: 'OTANCHE', deptoName: 'BOYACÁ' },
  { mpioCode: '70508', mpioName: 'OVEJAS', deptoName: 'SUCRE' },
  { mpioCode: '15511', mpioName: 'PACHAVITA', deptoName: 'BOYACÁ' },
  { mpioCode: '25513', mpioName: 'PACHO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '97511', mpioName: 'PACOA', deptoName: 'VAUPÉS' },
  { mpioCode: '17513', mpioName: 'PÁCORA', deptoName: 'CALDAS' },
  { mpioCode: '19513', mpioName: 'PADILLA', deptoName: 'CAUCA' },
  { mpioCode: '15514', mpioName: 'PÁEZ', deptoName: 'BOYACÁ' },
  { mpioCode: '19517', mpioName: 'PÁEZ', deptoName: 'CAUCA' },
  { mpioCode: '41518', mpioName: 'PAICOL', deptoName: 'HUILA' },
  { mpioCode: '20517', mpioName: 'PAILITAS', deptoName: 'CESAR' },
  { mpioCode: '25518', mpioName: 'PAIME', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15516', mpioName: 'PAIPA', deptoName: 'BOYACÁ' },
  { mpioCode: '15518', mpioName: 'PAJARITO', deptoName: 'BOYACÁ' },
  { mpioCode: '41524', mpioName: 'PALERMO', deptoName: 'HUILA' },
  { mpioCode: '17524', mpioName: 'PALESTINA', deptoName: 'CALDAS' },
  { mpioCode: '41530', mpioName: 'PALESTINA', deptoName: 'HUILA' },
  { mpioCode: '68522', mpioName: 'PALMAR', deptoName: 'SANTANDER' },
  { mpioCode: '08520', mpioName: 'PALMAR DE VARELA', deptoName: 'ATLÁNTICO' },
  { mpioCode: '68524', mpioName: 'PALMAS DEL SOCORRO', deptoName: 'SANTANDER' },
  { mpioCode: '76520', mpioName: 'PALMIRA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '70523', mpioName: 'PALMITO', deptoName: 'SUCRE' },
  { mpioCode: '73520', mpioName: 'PALOCABILDO', deptoName: 'TOLIMA' },
  { mpioCode: '54518', mpioName: 'PAMPLONA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '54520', mpioName: 'PAMPLONITA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '94887', mpioName: 'PANA PANA', deptoName: 'GUAINÍA' },
  { mpioCode: '25524', mpioName: 'PANDI', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15522', mpioName: 'PANQUEBA', deptoName: 'BOYACÁ' },
  { mpioCode: '97777', mpioName: 'PAPUNAHUA', deptoName: 'VAUPÉS' },
  { mpioCode: '68533', mpioName: 'PÁRAMO', deptoName: 'SANTANDER' },
  { mpioCode: '25530', mpioName: 'PARATEBUENO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25535', mpioName: 'PASCA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52001', mpioName: 'PASTO', deptoName: 'NARIÑO' },
  { mpioCode: '19532', mpioName: 'PATÍA', deptoName: 'CAUCA' },
  { mpioCode: '15531', mpioName: 'PAUNA', deptoName: 'BOYACÁ' },
  { mpioCode: '15533', mpioName: 'PAYA', deptoName: 'BOYACÁ' },
  { mpioCode: '85250', mpioName: 'PAZ DE ARIPORO', deptoName: 'CASANARE' },
  { mpioCode: '15537', mpioName: 'PAZ DE RÍO', deptoName: 'BOYACÁ' },
  { mpioCode: '47541', mpioName: 'PEDRAZA', deptoName: 'MAGDALENA' },
  { mpioCode: '20550', mpioName: 'PELAYA', deptoName: 'CESAR' },
  { mpioCode: '17541', mpioName: 'PENSILVANIA', deptoName: 'CALDAS' },
  { mpioCode: '05541', mpioName: 'PEÑOL', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05543', mpioName: 'PEQUE', deptoName: 'ANTIOQUIA' },
  { mpioCode: '66001', mpioName: 'PEREIRA', deptoName: 'RISARALDA' },
  { mpioCode: '15542', mpioName: 'PESCA', deptoName: 'BOYACÁ' },
  { mpioCode: '19533', mpioName: 'PIAMONTE', deptoName: 'CAUCA' },
  { mpioCode: '68547', mpioName: 'PIEDECUESTA', deptoName: 'SANTANDER' },
  { mpioCode: '73547', mpioName: 'PIEDRAS', deptoName: 'TOLIMA' },
  { mpioCode: '19548', mpioName: 'PIENDAMÓ – TUNÍA', deptoName: 'CAUCA' },
  { mpioCode: '63548', mpioName: 'PIJAO', deptoName: 'QUINDÍO' },
  { mpioCode: '47545', mpioName: 'PIJIÑO DEL CARMEN', deptoName: 'MAGDALENA' },
  { mpioCode: '68549', mpioName: 'PINCHOTE', deptoName: 'SANTANDER' },
  { mpioCode: '13549', mpioName: 'PINILLOS', deptoName: 'BOLÍVAR' },
  { mpioCode: '08549', mpioName: 'PIOJÓ', deptoName: 'ATLÁNTICO' },
  { mpioCode: '15550', mpioName: 'PISBA', deptoName: 'BOYACÁ' },
  { mpioCode: '41548', mpioName: 'PITAL', deptoName: 'HUILA' },
  { mpioCode: '41551', mpioName: 'PITALITO', deptoName: 'HUILA' },
  { mpioCode: '47551', mpioName: 'PIVIJAY', deptoName: 'MAGDALENA' },
  { mpioCode: '73555', mpioName: 'PLANADAS', deptoName: 'TOLIMA' },
  { mpioCode: '23555', mpioName: 'PLANETA RICA', deptoName: 'CÓRDOBA' },
  { mpioCode: '47555', mpioName: 'PLATO', deptoName: 'MAGDALENA' },
  { mpioCode: '52540', mpioName: 'POLICARPA', deptoName: 'NARIÑO' },
  { mpioCode: '08558', mpioName: 'POLONUEVO', deptoName: 'ATLÁNTICO' },
  { mpioCode: '08560', mpioName: 'PONEDERA', deptoName: 'ATLÁNTICO' },
  { mpioCode: '19001', mpioName: 'POPAYÁN', deptoName: 'CAUCA' },
  { mpioCode: '85263', mpioName: 'PORE', deptoName: 'CASANARE' },
  { mpioCode: '52560', mpioName: 'POTOSÍ', deptoName: 'NARIÑO' },
  { mpioCode: '76563', mpioName: 'PRADERA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '73563', mpioName: 'PRADO', deptoName: 'TOLIMA' },
  { mpioCode: '88564', mpioName: 'PROVIDENCIA', deptoName: 'ARCHIPIÉLAGO DE SAN ANDRÉS. PROVIDENCIA Y SANTA CATALINA' },
  { mpioCode: '52565', mpioName: 'PROVIDENCIA', deptoName: 'NARIÑO' },
  { mpioCode: '20570', mpioName: 'PUEBLO BELLO', deptoName: 'CESAR' },
  { mpioCode: '23570', mpioName: 'PUEBLO NUEVO', deptoName: 'CÓRDOBA' },
  { mpioCode: '66572', mpioName: 'PUEBLO RICO', deptoName: 'RISARALDA' },
  { mpioCode: '05576', mpioName: 'PUEBLORRICO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '47570', mpioName: 'PUEBLOVIEJO', deptoName: 'MAGDALENA' },
  { mpioCode: '68572', mpioName: 'PUENTE NACIONAL', deptoName: 'SANTANDER' },
  { mpioCode: '52573', mpioName: 'PUERRES', deptoName: 'NARIÑO' },
  { mpioCode: '91530', mpioName: 'PUERTO ALEGRÍA', deptoName: 'AMAZONAS' },
  { mpioCode: '91536', mpioName: 'PUERTO ARICA', deptoName: 'AMAZONAS' },
  { mpioCode: '86568', mpioName: 'PUERTO ASÍS', deptoName: 'PUTUMAYO' },
  { mpioCode: '05579', mpioName: 'PUERTO BERRÍO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15572', mpioName: 'PUERTO BOYACÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '86569', mpioName: 'PUERTO CAICEDO', deptoName: 'PUTUMAYO' },
  { mpioCode: '99001', mpioName: 'PUERTO CARREÑO', deptoName: 'VICHADA' },
  { mpioCode: '08573', mpioName: 'PUERTO COLOMBIA', deptoName: 'ATLÁNTICO' },
  { mpioCode: '94884', mpioName: 'PUERTO COLOMBIA', deptoName: 'GUAINÍA' },
  { mpioCode: '50450', mpioName: 'PUERTO CONCORDIA', deptoName: 'META' },
  { mpioCode: '23574', mpioName: 'PUERTO ESCONDIDO', deptoName: 'CÓRDOBA' },
  { mpioCode: '50568', mpioName: 'PUERTO GAITÁN', deptoName: 'META' },
  { mpioCode: '86571', mpioName: 'PUERTO GUZMÁN', deptoName: 'PUTUMAYO' },
  { mpioCode: '86573', mpioName: 'PUERTO LEGUÍZAMO', deptoName: 'PUTUMAYO' },
  { mpioCode: '23580', mpioName: 'PUERTO LIBERTADOR', deptoName: 'CÓRDOBA' },
  { mpioCode: '50577', mpioName: 'PUERTO LLERAS', deptoName: 'META' },
  { mpioCode: '50573', mpioName: 'PUERTO LÓPEZ', deptoName: 'META' },
  { mpioCode: '05585', mpioName: 'PUERTO NARE', deptoName: 'ANTIOQUIA' },
  { mpioCode: '91540', mpioName: 'PUERTO NARIÑO', deptoName: 'AMAZONAS' },
  { mpioCode: '68573', mpioName: 'PUERTO PARRA', deptoName: 'SANTANDER' },
  { mpioCode: '18592', mpioName: 'PUERTO RICO', deptoName: 'CAQUETÁ' },
  { mpioCode: '50590', mpioName: 'PUERTO RICO', deptoName: 'META' },
  { mpioCode: '81591', mpioName: 'PUERTO RONDÓN', deptoName: 'ARAUCA' },
  { mpioCode: '25572', mpioName: 'PUERTO SALGAR', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '91669', mpioName: 'PUERTO SANTANDER', deptoName: 'AMAZONAS' },
  { mpioCode: '54553', mpioName: 'PUERTO SANTANDER', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '19573', mpioName: 'PUERTO TEJADA', deptoName: 'CAUCA' },
  { mpioCode: '05591', mpioName: 'PUERTO TRIUNFO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68575', mpioName: 'PUERTO WILCHES', deptoName: 'SANTANDER' },
  { mpioCode: '25580', mpioName: 'PULÍ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52585', mpioName: 'PUPIALES', deptoName: 'NARIÑO' },
  { mpioCode: '19585', mpioName: 'PURACÉ', deptoName: 'CAUCA' },
  { mpioCode: '73585', mpioName: 'PURIFICACIÓN', deptoName: 'TOLIMA' },
  { mpioCode: '23586', mpioName: 'PURÍSIMA DE LA CONCEPCIÓN', deptoName: 'CÓRDOBA' },
  { mpioCode: '25592', mpioName: 'QUEBRADANEGRA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25594', mpioName: 'QUETAME', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '27001', mpioName: 'QUIBDÓ', deptoName: 'CHOCÓ' },
  { mpioCode: '63594', mpioName: 'QUIMBAYA', deptoName: 'QUINDÍO' },
  { mpioCode: '66594', mpioName: 'QUINCHÍA', deptoName: 'RISARALDA' },
  { mpioCode: '15580', mpioName: 'QUÍPAMA', deptoName: 'BOYACÁ' },
  { mpioCode: '25596', mpioName: 'QUIPILE', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '54599', mpioName: 'RAGONVALIA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '15599', mpioName: 'RAMIRIQUÍ', deptoName: 'BOYACÁ' },
  { mpioCode: '15600', mpioName: 'RÁQUIRA', deptoName: 'BOYACÁ' },
  { mpioCode: '85279', mpioName: 'RECETOR', deptoName: 'CASANARE' },
  { mpioCode: '13580', mpioName: 'REGIDOR', deptoName: 'BOLÍVAR' },
  { mpioCode: '05604', mpioName: 'REMEDIOS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '47605', mpioName: 'REMOLINO', deptoName: 'MAGDALENA' },
  { mpioCode: '08606', mpioName: 'REPELÓN', deptoName: 'ATLÁNTICO' },
  { mpioCode: '50606', mpioName: 'RESTREPO', deptoName: 'META' },
  { mpioCode: '76606', mpioName: 'RESTREPO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '05607', mpioName: 'RETIRO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25612', mpioName: 'RICAURTE', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52612', mpioName: 'RICAURTE', deptoName: 'NARIÑO' },
  { mpioCode: '20614', mpioName: 'RÍO DE ORO', deptoName: 'CESAR' },
  { mpioCode: '27580', mpioName: 'RÍO IRÓ', deptoName: 'CHOCÓ' },
  { mpioCode: '27600', mpioName: 'RÍO QUITO', deptoName: 'CHOCÓ' },
  { mpioCode: '13600', mpioName: 'RÍO VIEJO', deptoName: 'BOLÍVAR' },
  { mpioCode: '73616', mpioName: 'RIOBLANCO', deptoName: 'TOLIMA' },
  { mpioCode: '76616', mpioName: 'RIOFRÍO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '44001', mpioName: 'RIOHACHA', deptoName: 'LA GUAJIRA' },
  { mpioCode: '05615', mpioName: 'RIONEGRO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68615', mpioName: 'RIONEGRO', deptoName: 'SANTANDER' },
  { mpioCode: '17614', mpioName: 'RIOSUCIO', deptoName: 'CALDAS' },
  { mpioCode: '27615', mpioName: 'RIOSUCIO', deptoName: 'CHOCÓ' },
  { mpioCode: '17616', mpioName: 'RISARALDA', deptoName: 'CALDAS' },
  { mpioCode: '41615', mpioName: 'RIVERA', deptoName: 'HUILA' },
  { mpioCode: '52621', mpioName: 'ROBERTO PAYÁN', deptoName: 'NARIÑO' },
  { mpioCode: '76622', mpioName: 'ROLDANILLO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '73622', mpioName: 'RONCESVALLES', deptoName: 'TOLIMA' },
  { mpioCode: '15621', mpioName: 'RONDÓN', deptoName: 'BOYACÁ' },
  { mpioCode: '19622', mpioName: 'ROSAS', deptoName: 'CAUCA' },
  { mpioCode: '73624', mpioName: 'ROVIRA', deptoName: 'TOLIMA' },
  { mpioCode: '68655', mpioName: 'SABANA DE TORRES', deptoName: 'SANTANDER' },
  { mpioCode: '08634', mpioName: 'SABANAGRANDE', deptoName: 'ATLÁNTICO' },
  { mpioCode: '05628', mpioName: 'SABANALARGA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '08638', mpioName: 'SABANALARGA', deptoName: 'ATLÁNTICO' },
  { mpioCode: '85300', mpioName: 'SABANALARGA', deptoName: 'CASANARE' },
  { mpioCode: '47660', mpioName: 'SABANAS DE SAN ÁNGEL', deptoName: 'MAGDALENA' },
  { mpioCode: '05631', mpioName: 'SABANETA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15632', mpioName: 'SABOYÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '85315', mpioName: 'SÁCAMA', deptoName: 'CASANARE' },
  { mpioCode: '15638', mpioName: 'SÁCHICA', deptoName: 'BOYACÁ' },
  { mpioCode: '23660', mpioName: 'SAHAGÚN', deptoName: 'CÓRDOBA' },
  { mpioCode: '41660', mpioName: 'SALADOBLANCO', deptoName: 'HUILA' },
  { mpioCode: '17653', mpioName: 'SALAMINA', deptoName: 'CALDAS' },
  { mpioCode: '47675', mpioName: 'SALAMINA', deptoName: 'MAGDALENA' },
  { mpioCode: '54660', mpioName: 'SALAZAR', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '73671', mpioName: 'SALDAÑA', deptoName: 'TOLIMA' },
  { mpioCode: '63690', mpioName: 'SALENTO', deptoName: 'QUINDÍO' },
  { mpioCode: '05642', mpioName: 'SALGAR', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15646', mpioName: 'SAMACÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '17662', mpioName: 'SAMANÁ', deptoName: 'CALDAS' },
  { mpioCode: '52678', mpioName: 'SAMANIEGO', deptoName: 'NARIÑO' },
  { mpioCode: '70670', mpioName: 'SAMPUÉS', deptoName: 'SUCRE' },
  { mpioCode: '41668', mpioName: 'SAN AGUSTÍN', deptoName: 'HUILA' },
  { mpioCode: '20710', mpioName: 'SAN ALBERTO', deptoName: 'CESAR' },
  { mpioCode: '88001', mpioName: 'SAN ANDRÉS', deptoName: 'ARCHIPIÉLAGO DE SAN ANDRÉS. PROVIDENCIA Y SANTA CATALINA' },
  { mpioCode: '68669', mpioName: 'SAN ANDRÉS', deptoName: 'SANTANDER' },
  { mpioCode: '05647', mpioName: 'SAN ANDRÉS DE CUERQUÍA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '23670', mpioName: 'SAN ANDRÉS DE SOTAVENTO', deptoName: 'CÓRDOBA' },
  { mpioCode: '52835', mpioName: 'SAN ANDRÉS DE TUMACO', deptoName: 'NARIÑO' },
  { mpioCode: '23672', mpioName: 'SAN ANTERO', deptoName: 'CÓRDOBA' },
  { mpioCode: '73675', mpioName: 'SAN ANTONIO', deptoName: 'TOLIMA' },
  { mpioCode: '25645', mpioName: 'SAN ANTONIO DEL TEQUENDAMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '68673', mpioName: 'SAN BENITO', deptoName: 'SANTANDER' },
  { mpioCode: '70678', mpioName: 'SAN BENITO ABAD', deptoName: 'SUCRE' },
  { mpioCode: '25649', mpioName: 'SAN BERNARDO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52685', mpioName: 'SAN BERNARDO', deptoName: 'NARIÑO' },
  { mpioCode: '23675', mpioName: 'SAN BERNARDO DEL VIENTO', deptoName: 'CÓRDOBA' },
  { mpioCode: '54670', mpioName: 'SAN CALIXTO', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '05649', mpioName: 'SAN CARLOS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '23678', mpioName: 'SAN CARLOS', deptoName: 'CÓRDOBA' },
  { mpioCode: '50680', mpioName: 'SAN CARLOS DE GUAROA', deptoName: 'META' },
  { mpioCode: '25653', mpioName: 'SAN CAYETANO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '54673', mpioName: 'SAN CAYETANO', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '13620', mpioName: 'SAN CRISTÓBAL', deptoName: 'BOLÍVAR' },
  { mpioCode: '20750', mpioName: 'SAN DIEGO', deptoName: 'CESAR' },
  { mpioCode: '15660', mpioName: 'SAN EDUARDO', deptoName: 'BOYACÁ' },
  { mpioCode: '13647', mpioName: 'SAN ESTANISLAO', deptoName: 'BOLÍVAR' },
  { mpioCode: '94883', mpioName: 'SAN FELIPE', deptoName: 'GUAINÍA' },
  { mpioCode: '13650', mpioName: 'SAN FERNANDO', deptoName: 'BOLÍVAR' },
  { mpioCode: '05652', mpioName: 'SAN FRANCISCO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25658', mpioName: 'SAN FRANCISCO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '86755', mpioName: 'SAN FRANCISCO', deptoName: 'PUTUMAYO' },
  { mpioCode: '68679', mpioName: 'SAN GIL', deptoName: 'SANTANDER' },
  { mpioCode: '13654', mpioName: 'SAN JACINTO', deptoName: 'BOLÍVAR' },
  { mpioCode: '13655', mpioName: 'SAN JACINTO DEL CAUCA', deptoName: 'BOLÍVAR' },
  { mpioCode: '05656', mpioName: 'SAN JERÓNIMO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68682', mpioName: 'SAN JOAQUÍN', deptoName: 'SANTANDER' },
  { mpioCode: '17665', mpioName: 'SAN JOSÉ', deptoName: 'CALDAS' },
  { mpioCode: '54001', mpioName: 'SAN JOSÉ DE CÚCUTA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '05658', mpioName: 'SAN JOSÉ DE LA MONTAÑA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68684', mpioName: 'SAN JOSÉ DE MIRANDA', deptoName: 'SANTANDER' },
  { mpioCode: '15664', mpioName: 'SAN JOSÉ DE PARE', deptoName: 'BOYACÁ' },
  { mpioCode: '70823', mpioName: 'SAN JOSÉ DE TOLUVIEJO', deptoName: 'SUCRE' },
  { mpioCode: '23682', mpioName: 'SAN JOSÉ DE URÉ', deptoName: 'CÓRDOBA' },
  { mpioCode: '18610', mpioName: 'SAN JOSÉ DEL FRAGUA', deptoName: 'CAQUETÁ' },
  { mpioCode: '95001', mpioName: 'SAN JOSÉ DEL GUAVIARE', deptoName: 'GUAVIARE' },
  { mpioCode: '27660', mpioName: 'SAN JOSÉ DEL PALMAR', deptoName: 'CHOCÓ' },
  { mpioCode: '50683', mpioName: 'SAN JUAN DE ARAMA', deptoName: 'META' },
  { mpioCode: '70702', mpioName: 'SAN JUAN DE BETULIA', deptoName: 'SUCRE' },
  { mpioCode: '25662', mpioName: 'SAN JUAN DE RIOSECO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '05659', mpioName: 'SAN JUAN DE URABÁ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '44650', mpioName: 'SAN JUAN DEL CESAR', deptoName: 'LA GUAJIRA' },
  { mpioCode: '13657', mpioName: 'SAN JUAN NEPOMUCENO', deptoName: 'BOLÍVAR' },
  { mpioCode: '50686', mpioName: 'SAN JUANITO', deptoName: 'META' },
  { mpioCode: '52687', mpioName: 'SAN LORENZO', deptoName: 'NARIÑO' },
  { mpioCode: '05660', mpioName: 'SAN LUIS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '73678', mpioName: 'SAN LUIS', deptoName: 'TOLIMA' },
  { mpioCode: '15667', mpioName: 'SAN LUIS DE GACENO', deptoName: 'BOYACÁ' },
  { mpioCode: '85325', mpioName: 'SAN LUIS DE PALENQUE', deptoName: 'CASANARE' },
  { mpioCode: '70742', mpioName: 'SAN LUIS DE SINCÉ', deptoName: 'SUCRE' },
  { mpioCode: '70708', mpioName: 'SAN MARCOS', deptoName: 'SUCRE' },
  { mpioCode: '20770', mpioName: 'SAN MARTÍN', deptoName: 'CESAR' },
  { mpioCode: '50689', mpioName: 'SAN MARTÍN', deptoName: 'META' },
  { mpioCode: '13667', mpioName: 'SAN MARTÍN DE LOBA', deptoName: 'BOLÍVAR' },
  { mpioCode: '15673', mpioName: 'SAN MATEO', deptoName: 'BOYACÁ' },
  { mpioCode: '86757', mpioName: 'SAN MIGUEL', deptoName: 'PUTUMAYO' },
  { mpioCode: '68686', mpioName: 'SAN MIGUEL', deptoName: 'SANTANDER' },
  { mpioCode: '15676', mpioName: 'SAN MIGUEL DE SEMA', deptoName: 'BOYACÁ' },
  { mpioCode: '70713', mpioName: 'SAN ONOFRE', deptoName: 'SUCRE' },
  { mpioCode: '13670', mpioName: 'SAN PABLO', deptoName: 'BOLÍVAR' },
  { mpioCode: '52693', mpioName: 'SAN PABLO', deptoName: 'NARIÑO' },
  { mpioCode: '15681', mpioName: 'SAN PABLO DE BORBUR', deptoName: 'BOYACÁ' },
  { mpioCode: '70717', mpioName: 'SAN PEDRO', deptoName: 'SUCRE' },
  { mpioCode: '76670', mpioName: 'SAN PEDRO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '52694', mpioName: 'SAN PEDRO DE CARTAGO', deptoName: 'NARIÑO' },
  { mpioCode: '05664', mpioName: 'SAN PEDRO DE LOS MILAGROS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05665', mpioName: 'SAN PEDRO DE URABÁ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '23686', mpioName: 'SAN PELAYO', deptoName: 'CÓRDOBA' },
  { mpioCode: '05667', mpioName: 'SAN RAFAEL', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05670', mpioName: 'SAN ROQUE', deptoName: 'ANTIOQUIA' },
  { mpioCode: '19693', mpioName: 'SAN SEBASTIÁN', deptoName: 'CAUCA' },
  { mpioCode: '47692', mpioName: 'SAN SEBASTIÁN DE BUENAVISTA', deptoName: 'MAGDALENA' },
  { mpioCode: '73443', mpioName: 'SAN SEBASTIÁN DE MARIQUITA', deptoName: 'TOLIMA' },
  { mpioCode: '68689', mpioName: 'SAN VICENTE DE CHUCURÍ', deptoName: 'SANTANDER' },
  { mpioCode: '18753', mpioName: 'SAN VICENTE DEL CAGUÁN', deptoName: 'CAQUETÁ' },
  { mpioCode: '05674', mpioName: 'SAN VICENTE FERRER', deptoName: 'ANTIOQUIA' },
  { mpioCode: '47703', mpioName: 'SAN ZENÓN', deptoName: 'MAGDALENA' },
  { mpioCode: '52683', mpioName: 'SANDONÁ', deptoName: 'NARIÑO' },
  { mpioCode: '47707', mpioName: 'SANTA ANA', deptoName: 'MAGDALENA' },
  { mpioCode: '05679', mpioName: 'SANTA BÁRBARA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '52696', mpioName: 'SANTA BÁRBARA', deptoName: 'NARIÑO' },
  { mpioCode: '68705', mpioName: 'SANTA BÁRBARA', deptoName: 'SANTANDER' },
  { mpioCode: '47720', mpioName: 'SANTA BÁRBARA DE PINTO', deptoName: 'MAGDALENA' },
  { mpioCode: '13673', mpioName: 'SANTA CATALINA', deptoName: 'BOLÍVAR' },
  { mpioCode: '13468', mpioName: 'SANTA CRUZ DE MOMPOX', deptoName: 'BOLÍVAR' },
  { mpioCode: '05042', mpioName: 'SANTA FÉ DE ANTIOQUIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68720', mpioName: 'SANTA HELENA DEL OPÓN', deptoName: 'SANTANDER' },
  { mpioCode: '73686', mpioName: 'SANTA ISABEL', deptoName: 'TOLIMA' },
  { mpioCode: '08675', mpioName: 'SANTA LUCÍA', deptoName: 'ATLÁNTICO' },
  { mpioCode: '15690', mpioName: 'SANTA MARÍA', deptoName: 'BOYACÁ' },
  { mpioCode: '41676', mpioName: 'SANTA MARÍA', deptoName: 'HUILA' },
  { mpioCode: '47001', mpioName: 'SANTA MARTA', deptoName: 'MAGDALENA' },
  { mpioCode: '13683', mpioName: 'SANTA ROSA', deptoName: 'BOLÍVAR' },
  { mpioCode: '19701', mpioName: 'SANTA ROSA', deptoName: 'CAUCA' },
  { mpioCode: '66682', mpioName: 'SANTA ROSA DE CABAL', deptoName: 'RISARALDA' },
  { mpioCode: '05686', mpioName: 'SANTA ROSA DE OSOS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15693', mpioName: 'SANTA ROSA DE VITERBO', deptoName: 'BOYACÁ' },
  { mpioCode: '13688', mpioName: 'SANTA ROSA DEL SUR', deptoName: 'BOLÍVAR' },
  { mpioCode: '99624', mpioName: 'SANTA ROSALÍA', deptoName: 'VICHADA' },
  { mpioCode: '15696', mpioName: 'SANTA SOFÍA', deptoName: 'BOYACÁ' },
  { mpioCode: '52699', mpioName: 'SANTACRUZ', deptoName: 'NARIÑO' },
  { mpioCode: '15686', mpioName: 'SANTANA', deptoName: 'BOYACÁ' },
  { mpioCode: '19698', mpioName: 'SANTANDER DE QUILICHAO', deptoName: 'CAUCA' },
  { mpioCode: '54680', mpioName: 'SANTIAGO', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '86760', mpioName: 'SANTIAGO', deptoName: 'PUTUMAYO' },
  { mpioCode: '70820', mpioName: 'SANTIAGO DE TOLÚ', deptoName: 'SUCRE' },
  { mpioCode: '05690', mpioName: 'SANTO DOMINGO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '08685', mpioName: 'SANTO TOMÁS', deptoName: 'ATLÁNTICO' },
  { mpioCode: '66687', mpioName: 'SANTUARIO', deptoName: 'RISARALDA' },
  { mpioCode: '52720', mpioName: 'SAPUYES', deptoName: 'NARIÑO' },
  { mpioCode: '81736', mpioName: 'SARAVENA', deptoName: 'ARAUCA' },
  { mpioCode: '54720', mpioName: 'SARDINATA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '25718', mpioName: 'SASAIMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15720', mpioName: 'SATIVANORTE', deptoName: 'BOYACÁ' },
  { mpioCode: '15723', mpioName: 'SATIVASUR', deptoName: 'BOYACÁ' },
  { mpioCode: '05736', mpioName: 'SEGOVIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25736', mpioName: 'SESQUILÉ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '76736', mpioName: 'SEVILLA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '15740', mpioName: 'SIACHOQUE', deptoName: 'BOYACÁ' },
  { mpioCode: '25740', mpioName: 'SIBATÉ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '86749', mpioName: 'SIBUNDOY', deptoName: 'PUTUMAYO' },
  { mpioCode: '54743', mpioName: 'SILOS', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '25743', mpioName: 'SILVANIA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '19743', mpioName: 'SILVIA', deptoName: 'CAUCA' },
  { mpioCode: '68745', mpioName: 'SIMACOTA', deptoName: 'SANTANDER' },
  { mpioCode: '25745', mpioName: 'SIMIJACA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '13744', mpioName: 'SIMITÍ', deptoName: 'BOLÍVAR' },
  { mpioCode: '70001', mpioName: 'SINCELEJO', deptoName: 'SUCRE' },
  { mpioCode: '27745', mpioName: 'SIPÍ', deptoName: 'CHOCÓ' },
  { mpioCode: '47745', mpioName: 'SITIONUEVO', deptoName: 'MAGDALENA' },
  { mpioCode: '25754', mpioName: 'SOACHA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15753', mpioName: 'SOATÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '15757', mpioName: 'SOCHA', deptoName: 'BOYACÁ' },
  { mpioCode: '68755', mpioName: 'SOCORRO', deptoName: 'SANTANDER' },
  { mpioCode: '15755', mpioName: 'SOCOTÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '15759', mpioName: 'SOGAMOSO', deptoName: 'BOYACÁ' },
  { mpioCode: '18756', mpioName: 'SOLANO', deptoName: 'CAQUETÁ' },
  { mpioCode: '08758', mpioName: 'SOLEDAD', deptoName: 'ATLÁNTICO' },
  { mpioCode: '18785', mpioName: 'SOLITA', deptoName: 'CAQUETÁ' },
  { mpioCode: '15761', mpioName: 'SOMONDOCO', deptoName: 'BOYACÁ' },
  { mpioCode: '05756', mpioName: 'SONSÓN', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05761', mpioName: 'SOPETRÁN', deptoName: 'ANTIOQUIA' },
  { mpioCode: '13760', mpioName: 'SOPLAVIENTO', deptoName: 'BOLÍVAR' },
  { mpioCode: '25758', mpioName: 'SOPÓ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15762', mpioName: 'SORA', deptoName: 'BOYACÁ' },
  { mpioCode: '15764', mpioName: 'SORACÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '15763', mpioName: 'SOTAQUIRÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '19760', mpioName: 'SOTARÁ PAISPAMBA', deptoName: 'CAUCA' },
  { mpioCode: '68770', mpioName: 'SUAITA', deptoName: 'SANTANDER' },
  { mpioCode: '08770', mpioName: 'SUAN', deptoName: 'ATLÁNTICO' },
  { mpioCode: '19780', mpioName: 'SUÁREZ', deptoName: 'CAUCA' },
  { mpioCode: '73770', mpioName: 'SUÁREZ', deptoName: 'TOLIMA' },
  { mpioCode: '41770', mpioName: 'SUAZA', deptoName: 'HUILA' },
  { mpioCode: '25769', mpioName: 'SUBACHOQUE', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '19785', mpioName: 'SUCRE', deptoName: 'CAUCA' },
  { mpioCode: '68773', mpioName: 'SUCRE', deptoName: 'SANTANDER' },
  { mpioCode: '70771', mpioName: 'SUCRE', deptoName: 'SUCRE' },
  { mpioCode: '25772', mpioName: 'SUESCA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25777', mpioName: 'SUPATÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '17777', mpioName: 'SUPÍA', deptoName: 'CALDAS' },
  { mpioCode: '68780', mpioName: 'SURATÁ', deptoName: 'SANTANDER' },
  { mpioCode: '25779', mpioName: 'SUSA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15774', mpioName: 'SUSACÓN', deptoName: 'BOYACÁ' },
  { mpioCode: '15776', mpioName: 'SUTAMARCHÁN', deptoName: 'BOYACÁ' },
  { mpioCode: '25781', mpioName: 'SUTATAUSA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15778', mpioName: 'SUTATENZA', deptoName: 'BOYACÁ' },
  { mpioCode: '25785', mpioName: 'TABIO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '27787', mpioName: 'TADÓ', deptoName: 'CHOCÓ' },
  { mpioCode: '13780', mpioName: 'TALAIGUA NUEVO', deptoName: 'BOLÍVAR' },
  { mpioCode: '20787', mpioName: 'TAMALAMEQUE', deptoName: 'CESAR' },
  { mpioCode: '85400', mpioName: 'TÁMARA', deptoName: 'CASANARE' },
  { mpioCode: '81794', mpioName: 'TAME', deptoName: 'ARAUCA' },
  { mpioCode: '05789', mpioName: 'TÁMESIS', deptoName: 'ANTIOQUIA' },
  { mpioCode: '52786', mpioName: 'TAMINANGO', deptoName: 'NARIÑO' },
  { mpioCode: '52788', mpioName: 'TANGUA', deptoName: 'NARIÑO' },
  { mpioCode: '97666', mpioName: 'TARAIRA', deptoName: 'VAUPÉS' },
  { mpioCode: '91798', mpioName: 'TARAPACÁ', deptoName: 'AMAZONAS' },
  { mpioCode: '05790', mpioName: 'TARAZÁ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '41791', mpioName: 'TARQUI', deptoName: 'HUILA' },
  { mpioCode: '05792', mpioName: 'TARSO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15790', mpioName: 'TASCO', deptoName: 'BOYACÁ' },
  { mpioCode: '85410', mpioName: 'TAURAMENA', deptoName: 'CASANARE' },
  { mpioCode: '25793', mpioName: 'TAUSA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '41799', mpioName: 'TELLO', deptoName: 'HUILA' },
  { mpioCode: '25797', mpioName: 'TENA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '47798', mpioName: 'TENERIFE', deptoName: 'MAGDALENA' },
  { mpioCode: '25799', mpioName: 'TENJO', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15798', mpioName: 'TENZA', deptoName: 'BOYACÁ' },
  { mpioCode: '54800', mpioName: 'TEORAMA', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '41801', mpioName: 'TERUEL', deptoName: 'HUILA' },
  { mpioCode: '41797', mpioName: 'TESALIA', deptoName: 'HUILA' },
  { mpioCode: '25805', mpioName: 'TIBACUY', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15804', mpioName: 'TIBANÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '15806', mpioName: 'TIBASOSA', deptoName: 'BOYACÁ' },
  { mpioCode: '25807', mpioName: 'TIBIRITA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '54810', mpioName: 'TIBÚ', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '23807', mpioName: 'TIERRALTA', deptoName: 'CÓRDOBA' },
  { mpioCode: '41807', mpioName: 'TIMANÁ', deptoName: 'HUILA' },
  { mpioCode: '19807', mpioName: 'TIMBÍO', deptoName: 'CAUCA' },
  { mpioCode: '19809', mpioName: 'TIMBIQUÍ', deptoName: 'CAUCA' },
  { mpioCode: '15808', mpioName: 'TINJACÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '15810', mpioName: 'TIPACOQUE', deptoName: 'BOYACÁ' },
  { mpioCode: '13810', mpioName: 'TIQUISIO', deptoName: 'BOLÍVAR' },
  { mpioCode: '05809', mpioName: 'TITIRIBÍ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15814', mpioName: 'TOCA', deptoName: 'BOYACÁ' },
  { mpioCode: '25815', mpioName: 'TOCAIMA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25817', mpioName: 'TOCANCIPÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15816', mpioName: 'TOGÜÍ', deptoName: 'BOYACÁ' },
  { mpioCode: '05819', mpioName: 'TOLEDO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '54820', mpioName: 'TOLEDO', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '68820', mpioName: 'TONA', deptoName: 'SANTANDER' },
  { mpioCode: '15820', mpioName: 'TÓPAGA', deptoName: 'BOYACÁ' },
  { mpioCode: '25823', mpioName: 'TOPAIPÍ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '19821', mpioName: 'TORIBÍO', deptoName: 'CAUCA' },
  { mpioCode: '76823', mpioName: 'TORO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '15822', mpioName: 'TOTA', deptoName: 'BOYACÁ' },
  { mpioCode: '19824', mpioName: 'TOTORÓ', deptoName: 'CAUCA' },
  { mpioCode: '85430', mpioName: 'TRINIDAD', deptoName: 'CASANARE' },
  { mpioCode: '76828', mpioName: 'TRUJILLO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '08832', mpioName: 'TUBARÁ', deptoName: 'ATLÁNTICO' },
  { mpioCode: '23815', mpioName: 'TUCHÍN', deptoName: 'CÓRDOBA' },
  { mpioCode: '76834', mpioName: 'TULUÁ', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '15001', mpioName: 'TUNJA', deptoName: 'BOYACÁ' },
  { mpioCode: '15832', mpioName: 'TUNUNGUÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '52838', mpioName: 'TÚQUERRES', deptoName: 'NARIÑO' },
  { mpioCode: '13836', mpioName: 'TURBACO', deptoName: 'BOLÍVAR' },
  { mpioCode: '13838', mpioName: 'TURBANÁ', deptoName: 'BOLÍVAR' },
  { mpioCode: '05837', mpioName: 'TURBO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '15835', mpioName: 'TURMEQUÉ', deptoName: 'BOYACÁ' },
  { mpioCode: '15837', mpioName: 'TUTA', deptoName: 'BOYACÁ' },
  { mpioCode: '15839', mpioName: 'TUTAZÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '25839', mpioName: 'UBALÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25841', mpioName: 'UBAQUE', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '76845', mpioName: 'ULLOA', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '15842', mpioName: 'ÚMBITA', deptoName: 'BOYACÁ' },
  { mpioCode: '25845', mpioName: 'UNE', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '27800', mpioName: 'UNGUÍA', deptoName: 'CHOCÓ' },
  { mpioCode: '27810', mpioName: 'UNIÓN PANAMERICANA', deptoName: 'CHOCÓ' },
  { mpioCode: '05842', mpioName: 'URAMITA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '50370', mpioName: 'URIBE', deptoName: 'META' },
  { mpioCode: '44847', mpioName: 'URIBIA', deptoName: 'LA GUAJIRA' },
  { mpioCode: '05847', mpioName: 'URRAO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '44855', mpioName: 'URUMITA', deptoName: 'LA GUAJIRA' },
  { mpioCode: '08849', mpioName: 'USIACURÍ', deptoName: 'ATLÁNTICO' },
  { mpioCode: '25851', mpioName: 'ÚTICA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '05854', mpioName: 'VALDIVIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '23855', mpioName: 'VALENCIA', deptoName: 'CÓRDOBA' },
  { mpioCode: '68855', mpioName: 'VALLE DE SAN JOSÉ', deptoName: 'SANTANDER' },
  { mpioCode: '73854', mpioName: 'VALLE DE SAN JUAN', deptoName: 'TOLIMA' },
  { mpioCode: '86865', mpioName: 'VALLE DEL GUAMUEZ', deptoName: 'PUTUMAYO' },
  { mpioCode: '20001', mpioName: 'VALLEDUPAR', deptoName: 'CESAR' },
  { mpioCode: '05856', mpioName: 'VALPARAÍSO', deptoName: 'ANTIOQUIA' },
  { mpioCode: '18860', mpioName: 'VALPARAÍSO', deptoName: 'CAQUETÁ' },
  { mpioCode: '05858', mpioName: 'VEGACHÍ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '68861', mpioName: 'VÉLEZ', deptoName: 'SANTANDER' },
  { mpioCode: '73861', mpioName: 'VENADILLO', deptoName: 'TOLIMA' },
  { mpioCode: '05861', mpioName: 'VENECIA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '25506', mpioName: 'VENECIA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15861', mpioName: 'VENTAQUEMADA', deptoName: 'BOYACÁ' },
  { mpioCode: '25862', mpioName: 'VERGARA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '76863', mpioName: 'VERSALLES', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '68867', mpioName: 'VETAS', deptoName: 'SANTANDER' },
  { mpioCode: '25867', mpioName: 'VIANÍ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '17867', mpioName: 'VICTORIA', deptoName: 'CALDAS' },
  { mpioCode: '05873', mpioName: 'VIGÍA DEL FUERTE', deptoName: 'ANTIOQUIA' },
  { mpioCode: '76869', mpioName: 'VIJES', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '54871', mpioName: 'VILLA CARO', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '15407', mpioName: 'VILLA DE LEYVA', deptoName: 'BOYACÁ' },
  { mpioCode: '25843', mpioName: 'VILLA DE SAN DIEGO DE UBATÉ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '54874', mpioName: 'VILLA DEL ROSARIO', deptoName: 'NORTE DE SANTANDER' },
  { mpioCode: '19845', mpioName: 'VILLA RICA', deptoName: 'CAUCA' },
  { mpioCode: '86885', mpioName: 'VILLAGARZÓN', deptoName: 'PUTUMAYO' },
  { mpioCode: '25871', mpioName: 'VILLAGÓMEZ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '73870', mpioName: 'VILLAHERMOSA', deptoName: 'TOLIMA' },
  { mpioCode: '17873', mpioName: 'VILLAMARÍA', deptoName: 'CALDAS' },
  { mpioCode: '13873', mpioName: 'VILLANUEVA', deptoName: 'BOLÍVAR' },
  { mpioCode: '85440', mpioName: 'VILLANUEVA', deptoName: 'CASANARE' },
  { mpioCode: '44874', mpioName: 'VILLANUEVA', deptoName: 'LA GUAJIRA' },
  { mpioCode: '68872', mpioName: 'VILLANUEVA', deptoName: 'SANTANDER' },
  { mpioCode: '25873', mpioName: 'VILLAPINZÓN', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '73873', mpioName: 'VILLARRICA', deptoName: 'TOLIMA' },
  { mpioCode: '50001', mpioName: 'VILLAVICENCIO', deptoName: 'META' },
  { mpioCode: '41872', mpioName: 'VILLAVIEJA', deptoName: 'HUILA' },
  { mpioCode: '25875', mpioName: 'VILLETA', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25878', mpioName: 'VIOTÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '15879', mpioName: 'VIRACACHÁ', deptoName: 'BOYACÁ' },
  { mpioCode: '50711', mpioName: 'VISTAHERMOSA', deptoName: 'META' },
  { mpioCode: '17877', mpioName: 'VITERBO', deptoName: 'CALDAS' },
  { mpioCode: '25885', mpioName: 'YACOPÍ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '52885', mpioName: 'YACUANQUER', deptoName: 'NARIÑO' },
  { mpioCode: '41885', mpioName: 'YAGUARÁ', deptoName: 'HUILA' },
  { mpioCode: '05885', mpioName: 'YALÍ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05887', mpioName: 'YARUMAL', deptoName: 'ANTIOQUIA' },
  { mpioCode: '97889', mpioName: 'YAVARATÉ', deptoName: 'VAUPÉS' },
  { mpioCode: '05890', mpioName: 'YOLOMBÓ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '05893', mpioName: 'YONDÓ', deptoName: 'ANTIOQUIA' },
  { mpioCode: '85001', mpioName: 'YOPAL', deptoName: 'CASANARE' },
  { mpioCode: '76890', mpioName: 'YOTOCO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '76892', mpioName: 'YUMBO', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '13894', mpioName: 'ZAMBRANO', deptoName: 'BOLÍVAR' },
  { mpioCode: '68895', mpioName: 'ZAPATOCA', deptoName: 'SANTANDER' },
  { mpioCode: '47960', mpioName: 'ZAPAYÁN', deptoName: 'MAGDALENA' },
  { mpioCode: '05895', mpioName: 'ZARAGOZA', deptoName: 'ANTIOQUIA' },
  { mpioCode: '76895', mpioName: 'ZARZAL', deptoName: 'VALLE DEL CAUCA' },
  { mpioCode: '15897', mpioName: 'ZETAQUIRA', deptoName: 'BOYACÁ' },
  { mpioCode: '25898', mpioName: 'ZIPACÓN', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '25899', mpioName: 'ZIPAQUIRÁ', deptoName: 'CUNDINAMARCA' },
  { mpioCode: '47980', mpioName: 'ZONA BANANERA', deptoName: 'MAGDALENA' }
];
