module.exports = [
  { municipCode: '05002', municipName: 'ABEJORRAL', name: 'ANTIOQUIA' },
  { municipCode: '54003', municipName: 'ÁBREGO', name: 'NORTE DE SANTANDER' },
  { municipCode: '05004', municipName: 'ABRIAQUÍ', name: 'ANTIOQUIA' },
  { municipCode: '50006', municipName: 'ACACÍAS', name: 'META' },
  { municipCode: '27006', municipName: 'ACANDÍ', name: 'CHOCÓ' },
  { municipCode: '41006', municipName: 'ACEVEDO', name: 'HUILA' },
  { municipCode: '13006', municipName: 'ACHÍ', name: 'BOLÍVAR' },
  { municipCode: '41013', municipName: 'AGRADO', name: 'HUILA' },
  { municipCode: '25001', municipName: 'AGUA DE DIOS', name: 'CUNDINAMARCA' },
  { municipCode: '20011', municipName: 'AGUACHICA', name: 'CESAR' },
  { municipCode: '68013', municipName: 'AGUADA', name: 'SANTANDER' },
  { municipCode: '17013', municipName: 'AGUADAS', name: 'CALDAS' },
  { municipCode: '85010', municipName: 'AGUAZUL', name: 'CASANARE' },
  { municipCode: '20013', municipName: 'AGUSTÍN CODAZZI', name: 'CESAR' },
  { municipCode: '41016', municipName: 'AIPE', name: 'HUILA' },
  { municipCode: '25019', municipName: 'ALBÁN', name: 'CUNDINAMARCA' },
  { municipCode: '52019', municipName: 'ALBÁN', name: 'NARIÑO' },
  { municipCode: '18029', municipName: 'ALBANIA', name: 'CAQUETÁ' },
  { municipCode: '44035', municipName: 'ALBANIA', name: 'LA GUAJIRA' },
  { municipCode: '68020', municipName: 'ALBANIA', name: 'SANTANDER' },
  { municipCode: '76020', municipName: 'ALCALÁ', name: 'VALLE DEL CAUCA' },
  { municipCode: '52022', municipName: 'ALDANA', name: 'NARIÑO' },
  { municipCode: '05021', municipName: 'ALEJANDRÍA', name: 'ANTIOQUIA' },
  { municipCode: '47030', municipName: 'ALGARROBO', name: 'MAGDALENA' },
  { municipCode: '41020', municipName: 'ALGECIRAS', name: 'HUILA' },
  { municipCode: '19022', municipName: 'ALMAGUER', name: 'CAUCA' },
  { municipCode: '15022', municipName: 'ALMEIDA', name: 'BOYACÁ' },
  { municipCode: '73024', municipName: 'ALPUJARRA', name: 'TOLIMA' },
  { municipCode: '41026', municipName: 'ALTAMIRA', name: 'HUILA' },
  { municipCode: '27025', municipName: 'ALTO BAUDÓ', name: 'CHOCÓ' },
  { municipCode: '13030', municipName: 'ALTOS DEL ROSARIO', name: 'BOLÍVAR' },
  { municipCode: '73026', municipName: 'ALVARADO', name: 'TOLIMA' },
  { municipCode: '05030', municipName: 'AMAGÁ', name: 'ANTIOQUIA' },
  { municipCode: '05031', municipName: 'AMALFI', name: 'ANTIOQUIA' },
  { municipCode: '73030', municipName: 'AMBALEMA', name: 'TOLIMA' },
  { municipCode: '25035', municipName: 'ANAPOIMA', name: 'CUNDINAMARCA' },
  { municipCode: '52036', municipName: 'ANCUYA', name: 'NARIÑO' },
  { municipCode: '76036', municipName: 'ANDALUCÍA', name: 'VALLE DEL CAUCA' },
  { municipCode: '05034', municipName: 'ANDES', name: 'ANTIOQUIA' },
  { municipCode: '05036', municipName: 'ANGELÓPOLIS', name: 'ANTIOQUIA' },
  { municipCode: '05038', municipName: 'ANGOSTURA', name: 'ANTIOQUIA' },
  { municipCode: '25040', municipName: 'ANOLAIMA', name: 'CUNDINAMARCA' },
  { municipCode: '05040', municipName: 'ANORÍ', name: 'ANTIOQUIA' },
  { municipCode: '17042', municipName: 'ANSERMA', name: 'CALDAS' },
  { municipCode: '76041', municipName: 'ANSERMANUEVO', name: 'VALLE DEL CAUCA' },
  { municipCode: '05044', municipName: 'ANZÁ', name: 'ANTIOQUIA' },
  { municipCode: '73043', municipName: 'ANZOÁTEGUI', name: 'TOLIMA' },
  { municipCode: '05045', municipName: 'APARTADÓ', name: 'ANTIOQUIA' },
  { municipCode: '66045', municipName: 'APÍA', name: 'RISARALDA' },
  { municipCode: '25599', municipName: 'APULO', name: 'CUNDINAMARCA' },
  { municipCode: '15047', municipName: 'AQUITANIA', name: 'BOYACÁ' },
  { municipCode: '47053', municipName: 'ARACATACA', name: 'MAGDALENA' },
  { municipCode: '17050', municipName: 'ARANZAZU', name: 'CALDAS' },
  { municipCode: '68051', municipName: 'ARATOCA', name: 'SANTANDER' },
  { municipCode: '81001', municipName: 'ARAUCA', name: 'ARAUCA' },
  { municipCode: '81065', municipName: 'ARAUQUITA', name: 'ARAUCA' },
  { municipCode: '25053', municipName: 'ARBELÁEZ', name: 'CUNDINAMARCA' },
  { municipCode: '52051', municipName: 'ARBOLEDA', name: 'NARIÑO' },
  { municipCode: '54051', municipName: 'ARBOLEDAS', name: 'NORTE DE SANTANDER' },
  { municipCode: '05051', municipName: 'ARBOLETES', name: 'ANTIOQUIA' },
  { municipCode: '15051', municipName: 'ARCABUCO', name: 'BOYACÁ' },
  { municipCode: '13042', municipName: 'ARENAL', name: 'BOLÍVAR' },
  { municipCode: '05055', municipName: 'ARGELIA', name: 'ANTIOQUIA' },
  { municipCode: '19050', municipName: 'ARGELIA', name: 'CAUCA' },
  { municipCode: '76054', municipName: 'ARGELIA', name: 'VALLE DEL CAUCA' },
  { municipCode: '47058', municipName: 'ARIGUANÍ', name: 'MAGDALENA' },
  { municipCode: '13052', municipName: 'ARJONA', name: 'BOLÍVAR' },
  { municipCode: '05059', municipName: 'ARMENIA', name: 'ANTIOQUIA' },
  { municipCode: '63001', municipName: 'ARMENIA', name: 'QUINDÍO' },
  { municipCode: '73055', municipName: 'ARMERO', name: 'TOLIMA' },
  { municipCode: '13062', municipName: 'ARROYOHONDO', name: 'BOLÍVAR' },
  { municipCode: '20032', municipName: 'ASTREA', name: 'CESAR' },
  { municipCode: '73067', municipName: 'ATACO', name: 'TOLIMA' },
  { municipCode: '27050', municipName: 'ATRATO', name: 'CHOCÓ' },
  { municipCode: '23068', municipName: 'AYAPEL', name: 'CÓRDOBA' },
  { municipCode: '27073', municipName: 'BAGADÓ', name: 'CHOCÓ' },
  { municipCode: '27075', municipName: 'BAHÍA SOLANO', name: 'CHOCÓ' },
  { municipCode: '27077', municipName: 'BAJO BAUDÓ', name: 'CHOCÓ' },
  { municipCode: '19075', municipName: 'BALBOA', name: 'CAUCA' },
  { municipCode: '66075', municipName: 'BALBOA', name: 'RISARALDA' },
  { municipCode: '08078', municipName: 'BARANOA', name: 'ATLÁNTICO' },
  { municipCode: '41078', municipName: 'BARAYA', name: 'HUILA' },
  { municipCode: '52079', municipName: 'BARBACOAS', name: 'NARIÑO' },
  { municipCode: '05079', municipName: 'BARBOSA', name: 'ANTIOQUIA' },
  { municipCode: '68077', municipName: 'BARBOSA', name: 'SANTANDER' },
  { municipCode: '68079', municipName: 'BARICHARA', name: 'SANTANDER' },
  { municipCode: '50110', municipName: 'BARRANCA DE UPÍA', name: 'META' },
  { municipCode: '68081', municipName: 'BARRANCABERMEJA', name: 'SANTANDER' },
  { municipCode: '44078', municipName: 'BARRANCAS', name: 'LA GUAJIRA' },
  { municipCode: '13074', municipName: 'BARRANCO DE LOBA', name: 'BOLÍVAR' },
  { municipCode: '94343', municipName: 'BARRANCOMINAS', name: 'GUAINÍA' },
  { municipCode: '08001', municipName: 'BARRANQUILLA', name: 'ATLÁNTICO' },
  { municipCode: '20045', municipName: 'BECERRIL', name: 'CESAR' },
  { municipCode: '17088', municipName: 'BELALCÁZAR', name: 'CALDAS' },
  { municipCode: '15087', municipName: 'BELÉN', name: 'BOYACÁ' },
  { municipCode: '52083', municipName: 'BELÉN', name: 'NARIÑO' },
  { municipCode: '18094', municipName: 'BELÉN DE LOS ANDAQUÍES', name: 'CAQUETÁ' },
  { municipCode: '66088', municipName: 'BELÉN DE UMBRÍA', name: 'RISARALDA' },
  { municipCode: '05088', municipName: 'BELLO', name: 'ANTIOQUIA' },
  { municipCode: '05086', municipName: 'BELMIRA', name: 'ANTIOQUIA' },
  { municipCode: '25086', municipName: 'BELTRÁN', name: 'CUNDINAMARCA' },
  { municipCode: '15090', municipName: 'BERBEO', name: 'BOYACÁ' },
  { municipCode: '05091', municipName: 'BETANIA', name: 'ANTIOQUIA' },
  { municipCode: '15092', municipName: 'BETÉITIVA', name: 'BOYACÁ' },
  { municipCode: '05093', municipName: 'BETULIA', name: 'ANTIOQUIA' },
  { municipCode: '68092', municipName: 'BETULIA', name: 'SANTANDER' },
  { municipCode: '25095', municipName: 'BITUIMA', name: 'CUNDINAMARCA' },
  { municipCode: '15097', municipName: 'BOAVITA', name: 'BOYACÁ' },
  { municipCode: '54099', municipName: 'BOCHALEMA', name: 'NORTE DE SANTANDER' },
  { municipCode: '11001', municipName: 'BOGOTÁ. D.C.', name: 'BOGOTÁ. D.C.' },
  { municipCode: '25099', municipName: 'BOJACÁ', name: 'CUNDINAMARCA' },
  { municipCode: '27099', municipName: 'BOJAYÁ', name: 'CHOCÓ' },
  { municipCode: '19100', municipName: 'BOLÍVAR', name: 'CAUCA' },
  { municipCode: '68101', municipName: 'BOLÍVAR', name: 'SANTANDER' },
  { municipCode: '76100', municipName: 'BOLÍVAR', name: 'VALLE DEL CAUCA' },
  { municipCode: '20060', municipName: 'BOSCONIA', name: 'CESAR' },
  { municipCode: '15104', municipName: 'BOYACÁ', name: 'BOYACÁ' },
  { municipCode: '05107', municipName: 'BRICEÑO', name: 'ANTIOQUIA' },
  { municipCode: '15106', municipName: 'BRICEÑO', name: 'BOYACÁ' },
  { municipCode: '68001', municipName: 'BUCARAMANGA', name: 'SANTANDER' },
  { municipCode: '54109', municipName: 'BUCARASICA', name: 'NORTE DE SANTANDER' },
  { municipCode: '76109', municipName: 'BUENAVENTURA', name: 'VALLE DEL CAUCA' },
  { municipCode: '15109', municipName: 'BUENAVISTA', name: 'BOYACÁ' },
  { municipCode: '23079', municipName: 'BUENAVISTA', name: 'CÓRDOBA' },
  { municipCode: '63111', municipName: 'BUENAVISTA', name: 'QUINDÍO' },
  { municipCode: '70110', municipName: 'BUENAVISTA', name: 'SUCRE' },
  { municipCode: '19110', municipName: 'BUENOS AIRES', name: 'CAUCA' },
  { municipCode: '52110', municipName: 'BUESACO', name: 'NARIÑO' },
  { municipCode: '76113', municipName: 'BUGALAGRANDE', name: 'VALLE DEL CAUCA' },
  { municipCode: '05113', municipName: 'BURITICÁ', name: 'ANTIOQUIA' },
  { municipCode: '15114', municipName: 'BUSBANZÁ', name: 'BOYACÁ' },
  { municipCode: '25120', municipName: 'CABRERA', name: 'CUNDINAMARCA' },
  { municipCode: '68121', municipName: 'CABRERA', name: 'SANTANDER' },
  { municipCode: '50124', municipName: 'CABUYARO', name: 'META' },
  { municipCode: '94886', municipName: 'CACAHUAL', name: 'GUAINÍA' },
  { municipCode: '05120', municipName: 'CÁCERES', name: 'ANTIOQUIA' },
  { municipCode: '25123', municipName: 'CACHIPAY', name: 'CUNDINAMARCA' },
  { municipCode: '54128', municipName: 'CÁCHIRA', name: 'NORTE DE SANTANDER' },
  { municipCode: '54125', municipName: 'CÁCOTA', name: 'NORTE DE SANTANDER' },
  { municipCode: '05125', municipName: 'CAICEDO', name: 'ANTIOQUIA' },
  { municipCode: '76122', municipName: 'CAICEDONIA', name: 'VALLE DEL CAUCA' },
  { municipCode: '70124', municipName: 'CAIMITO', name: 'SUCRE' },
  { municipCode: '73124', municipName: 'CAJAMARCA', name: 'TOLIMA' },
  { municipCode: '19130', municipName: 'CAJIBÍO', name: 'CAUCA' },
  { municipCode: '25126', municipName: 'CAJICÁ', name: 'CUNDINAMARCA' },
  { municipCode: '13140', municipName: 'CALAMAR', name: 'BOLÍVAR' },
  { municipCode: '95015', municipName: 'CALAMAR', name: 'GUAVIARE' },
  { municipCode: '63130', municipName: 'CALARCÁ', name: 'QUINDÍO' },
  { municipCode: '05129', municipName: 'CALDAS', name: 'ANTIOQUIA' },
  { municipCode: '15131', municipName: 'CALDAS', name: 'BOYACÁ' },
  { municipCode: '19137', municipName: 'CALDONO', name: 'CAUCA' },
  { municipCode: '76001', municipName: 'CALI', name: 'VALLE DEL CAUCA' },
  { municipCode: '68132', municipName: 'CALIFORNIA', name: 'SANTANDER' },
  { municipCode: '76126', municipName: 'CALIMA', name: 'VALLE DEL CAUCA' },
  { municipCode: '19142', municipName: 'CALOTO', name: 'CAUCA' },
  { municipCode: '05134', municipName: 'CAMPAMENTO', name: 'ANTIOQUIA' },
  { municipCode: '08137', municipName: 'CAMPO DE LA CRUZ', name: 'ATLÁNTICO' },
  { municipCode: '41132', municipName: 'CAMPOALEGRE', name: 'HUILA' },
  { municipCode: '15135', municipName: 'CAMPOHERMOSO', name: 'BOYACÁ' },
  { municipCode: '23090', municipName: 'CANALETE', name: 'CÓRDOBA' },
  { municipCode: '08141', municipName: 'CANDELARIA', name: 'ATLÁNTICO' },
  { municipCode: '76130', municipName: 'CANDELARIA', name: 'VALLE DEL CAUCA' },
  { municipCode: '13160', municipName: 'CANTAGALLO', name: 'BOLÍVAR' },
  { municipCode: '05138', municipName: 'CAÑASGORDAS', name: 'ANTIOQUIA' },
  { municipCode: '25148', municipName: 'CAPARRAPÍ', name: 'CUNDINAMARCA' },
  { municipCode: '68147', municipName: 'CAPITANEJO', name: 'SANTANDER' },
  { municipCode: '25151', municipName: 'CÁQUEZA', name: 'CUNDINAMARCA' },
  { municipCode: '05142', municipName: 'CARACOLÍ', name: 'ANTIOQUIA' },
  { municipCode: '05145', municipName: 'CARAMANTA', name: 'ANTIOQUIA' },
  { municipCode: '68152', municipName: 'CARCASÍ', name: 'SANTANDER' },
  { municipCode: '05147', municipName: 'CAREPA', name: 'ANTIOQUIA' },
  { municipCode: '73148', municipName: 'CARMEN DE APICALÁ', name: 'TOLIMA' },
  { municipCode: '25154', municipName: 'CARMEN DE CARUPA', name: 'CUNDINAMARCA' },
  { municipCode: '27150', municipName: 'CARMEN DEL DARIÉN', name: 'CHOCÓ' },
  { municipCode: '05150', municipName: 'CAROLINA', name: 'ANTIOQUIA' },
  { municipCode: '13001', municipName: 'CARTAGENA DE INDIAS', name: 'BOLÍVAR' },
  { municipCode: '18150', municipName: 'CARTAGENA DEL CHAIRÁ', name: 'CAQUETÁ' },
  { municipCode: '76147', municipName: 'CARTAGO', name: 'VALLE DEL CAUCA' },
  { municipCode: '97161', municipName: 'CARURÚ', name: 'VAUPÉS' },
  { municipCode: '73152', municipName: 'CASABIANCA', name: 'TOLIMA' },
  { municipCode: '50150', municipName: 'CASTILLA LA NUEVA', name: 'META' },
  { municipCode: '05154', municipName: 'CAUCASIA', name: 'ANTIOQUIA' },
  { municipCode: '68160', municipName: 'CEPITÁ', name: 'SANTANDER' },
  { municipCode: '23162', municipName: 'CERETÉ', name: 'CÓRDOBA' },
  { municipCode: '15162', municipName: 'CERINZA', name: 'BOYACÁ' },
  { municipCode: '68162', municipName: 'CERRITO', name: 'SANTANDER' },
  { municipCode: '47161', municipName: 'CERRO DE SAN ANTONIO', name: 'MAGDALENA' },
  { municipCode: '27160', municipName: 'CÉRTEGUI', name: 'CHOCÓ' },
  { municipCode: '52240', municipName: 'CHACHAGÜÍ', name: 'NARIÑO' },
  { municipCode: '25168', municipName: 'CHAGUANÍ', name: 'CUNDINAMARCA' },
  { municipCode: '70230', municipName: 'CHALÁN', name: 'SUCRE' },
  { municipCode: '85015', municipName: 'CHÁMEZA', name: 'CASANARE' },
  { municipCode: '73168', municipName: 'CHAPARRAL', name: 'TOLIMA' },
  { municipCode: '68167', municipName: 'CHARALÁ', name: 'SANTANDER' },
  { municipCode: '68169', municipName: 'CHARTA', name: 'SANTANDER' },
  { municipCode: '25175', municipName: 'CHÍA', name: 'CUNDINAMARCA' },
  { municipCode: '05172', municipName: 'CHIGORODÓ', name: 'ANTIOQUIA' },
  { municipCode: '68176', municipName: 'CHIMA', name: 'SANTANDER' },
  { municipCode: '23168', municipName: 'CHIMÁ', name: 'CÓRDOBA' },
  { municipCode: '20175', municipName: 'CHIMICHAGUA', name: 'CESAR' },
  { municipCode: '54172', municipName: 'CHINÁCOTA', name: 'NORTE DE SANTANDER' },
  { municipCode: '15172', municipName: 'CHINAVITA', name: 'BOYACÁ' },
  { municipCode: '17174', municipName: 'CHINCHINÁ', name: 'CALDAS' },
  { municipCode: '23182', municipName: 'CHINÚ', name: 'CÓRDOBA' },
  { municipCode: '25178', municipName: 'CHIPAQUE', name: 'CUNDINAMARCA' },
  { municipCode: '68179', municipName: 'CHIPATÁ', name: 'SANTANDER' },
  { municipCode: '15176', municipName: 'CHIQUINQUIRÁ', name: 'BOYACÁ' },
  { municipCode: '15232', municipName: 'CHÍQUIZA', name: 'BOYACÁ' },
  { municipCode: '20178', municipName: 'CHIRIGUANÁ', name: 'CESAR' },
  { municipCode: '15180', municipName: 'CHISCAS', name: 'BOYACÁ' },
  { municipCode: '15183', municipName: 'CHITA', name: 'BOYACÁ' },
  { municipCode: '54174', municipName: 'CHITAGÁ', name: 'NORTE DE SANTANDER' },
  { municipCode: '15185', municipName: 'CHITARAQUE', name: 'BOYACÁ' },
  { municipCode: '15187', municipName: 'CHIVATÁ', name: 'BOYACÁ' },
  { municipCode: '47170', municipName: 'CHIVOLO', name: 'MAGDALENA' },
  { municipCode: '15236', municipName: 'CHIVOR', name: 'BOYACÁ' },
  { municipCode: '25181', municipName: 'CHOACHÍ', name: 'CUNDINAMARCA' },
  { municipCode: '25183', municipName: 'CHOCONTÁ', name: 'CUNDINAMARCA' },
  { municipCode: '13188', municipName: 'CICUCO', name: 'BOLÍVAR' },
  { municipCode: '47189', municipName: 'CIÉNAGA', name: 'MAGDALENA' },
  { municipCode: '23189', municipName: 'CIÉNAGA DE ORO', name: 'CÓRDOBA' },
  { municipCode: '15189', municipName: 'CIÉNEGA', name: 'BOYACÁ' },
  { municipCode: '68190', municipName: 'CIMITARRA', name: 'SANTANDER' },
  { municipCode: '63190', municipName: 'CIRCASIA', name: 'QUINDÍO' },
  { municipCode: '05190', municipName: 'CISNEROS', name: 'ANTIOQUIA' },
  { municipCode: '05101', municipName: 'CIUDAD BOLÍVAR', name: 'ANTIOQUIA' },
  { municipCode: '13222', municipName: 'CLEMENCIA', name: 'BOLÍVAR' },
  { municipCode: '05197', municipName: 'COCORNÁ', name: 'ANTIOQUIA' },
  { municipCode: '73200', municipName: 'COELLO', name: 'TOLIMA' },
  { municipCode: '25200', municipName: 'COGUA', name: 'CUNDINAMARCA' },
  { municipCode: '41206', municipName: 'COLOMBIA', name: 'HUILA' },
  { municipCode: '52203', municipName: 'COLÓN', name: 'NARIÑO' },
  { municipCode: '86219', municipName: 'COLÓN', name: 'PUTUMAYO' },
  { municipCode: '70204', municipName: 'COLOSÓ', name: 'SUCRE' },
  { municipCode: '15204', municipName: 'CÓMBITA', name: 'BOYACÁ' },
  { municipCode: '05206', municipName: 'CONCEPCIÓN', name: 'ANTIOQUIA' },
  { municipCode: '68207', municipName: 'CONCEPCIÓN', name: 'SANTANDER' },
  { municipCode: '05209', municipName: 'CONCORDIA', name: 'ANTIOQUIA' },
  { municipCode: '47205', municipName: 'CONCORDIA', name: 'MAGDALENA' },
  { municipCode: '27205', municipName: 'CONDOTO', name: 'CHOCÓ' },
  { municipCode: '68209', municipName: 'CONFINES', name: 'SANTANDER' },
  { municipCode: '52207', municipName: 'CONSACÁ', name: 'NARIÑO' },
  { municipCode: '52210', municipName: 'CONTADERO', name: 'NARIÑO' },
  { municipCode: '68211', municipName: 'CONTRATACIÓN', name: 'SANTANDER' },
  { municipCode: '54206', municipName: 'CONVENCIÓN', name: 'NORTE DE SANTANDER' },
  { municipCode: '05212', municipName: 'COPACABANA', name: 'ANTIOQUIA' },
  { municipCode: '15212', municipName: 'COPER', name: 'BOYACÁ' },
  { municipCode: '13212', municipName: 'CÓRDOBA', name: 'BOLÍVAR' },
  { municipCode: '52215', municipName: 'CÓRDOBA', name: 'NARIÑO' },
  { municipCode: '63212', municipName: 'CÓRDOBA', name: 'QUINDÍO' },
  { municipCode: '19212', municipName: 'CORINTO', name: 'CAUCA' },
  { municipCode: '68217', municipName: 'COROMORO', name: 'SANTANDER' },
  { municipCode: '70215', municipName: 'COROZAL', name: 'SUCRE' },
  { municipCode: '15215', municipName: 'CORRALES', name: 'BOYACÁ' },
  { municipCode: '25214', municipName: 'COTA', name: 'CUNDINAMARCA' },
  { municipCode: '23300', municipName: 'COTORRA', name: 'CÓRDOBA' },
  { municipCode: '15218', municipName: 'COVARACHÍA', name: 'BOYACÁ' },
  { municipCode: '70221', municipName: 'COVEÑAS', name: 'SUCRE' },
  { municipCode: '73217', municipName: 'COYAIMA', name: 'TOLIMA' },
  { municipCode: '81220', municipName: 'CRAVO NORTE', name: 'ARAUCA' },
  { municipCode: '52224', municipName: 'CUASPUD CARLOSAMA', name: 'NARIÑO' },
  { municipCode: '15223', municipName: 'CUBARÁ', name: 'BOYACÁ' },
  { municipCode: '50223', municipName: 'CUBARRAL', name: 'META' },
  { municipCode: '15224', municipName: 'CUCAITA', name: 'BOYACÁ' },
  { municipCode: '25224', municipName: 'CUCUNUBÁ', name: 'CUNDINAMARCA' },
  { municipCode: '54223', municipName: 'CUCUTILLA', name: 'NORTE DE SANTANDER' },
  { municipCode: '15226', municipName: 'CUÍTIVA', name: 'BOYACÁ' },
  { municipCode: '50226', municipName: 'CUMARAL', name: 'META' },
  { municipCode: '99773', municipName: 'CUMARIBO', name: 'VICHADA' },
  { municipCode: '52227', municipName: 'CUMBAL', name: 'NARIÑO' },
  { municipCode: '52233', municipName: 'CUMBITARA', name: 'NARIÑO' },
  { municipCode: '73226', municipName: 'CUNDAY', name: 'TOLIMA' },
  { municipCode: '18205', municipName: 'CURILLO', name: 'CAQUETÁ' },
  { municipCode: '68229', municipName: 'CURITÍ', name: 'SANTANDER' },
  { municipCode: '20228', municipName: 'CURUMANÍ', name: 'CESAR' },
  { municipCode: '05234', municipName: 'DABEIBA', name: 'ANTIOQUIA' },
  { municipCode: '76233', municipName: 'DAGUA', name: 'VALLE DEL CAUCA' },
  { municipCode: '44090', municipName: 'DIBULLA', name: 'LA GUAJIRA' },
  { municipCode: '44098', municipName: 'DISTRACCIÓN', name: 'LA GUAJIRA' },
  { municipCode: '73236', municipName: 'DOLORES', name: 'TOLIMA' },
  { municipCode: '05237', municipName: 'DONMATÍAS', name: 'ANTIOQUIA' },
  { municipCode: '66170', municipName: 'DOSQUEBRADAS', name: 'RISARALDA' },
  { municipCode: '15238', municipName: 'DUITAMA', name: 'BOYACÁ' },
  { municipCode: '54239', municipName: 'DURANIA', name: 'NORTE DE SANTANDER' },
  { municipCode: '05240', municipName: 'EBÉJICO', name: 'ANTIOQUIA' },
  { municipCode: '76243', municipName: 'EL ÁGUILA', name: 'VALLE DEL CAUCA' },
  { municipCode: '05250', municipName: 'EL BAGRE', name: 'ANTIOQUIA' },
  { municipCode: '47245', municipName: 'EL BANCO', name: 'MAGDALENA' },
  { municipCode: '76246', municipName: 'EL CAIRO', name: 'VALLE DEL CAUCA' },
  { municipCode: '50245', municipName: 'EL CALVARIO', name: 'META' },
  { municipCode: '27135', municipName: 'EL CANTÓN DEL SAN PABLO', name: 'CHOCÓ' },
  { municipCode: '54245', municipName: 'EL CARMEN', name: 'NORTE DE SANTANDER' },
  { municipCode: '27245', municipName: 'EL CARMEN DE ATRATO', name: 'CHOCÓ' },
  { municipCode: '13244', municipName: 'EL CARMEN DE BOLÍVAR', name: 'BOLÍVAR' },
  { municipCode: '68235', municipName: 'EL CARMEN DE CHUCURI', name: 'SANTANDER' },
  { municipCode: '05148', municipName: 'EL CARMEN DE VIBORAL', name: 'ANTIOQUIA' },
  { municipCode: '50251', municipName: 'EL CASTILLO', name: 'META' },
  { municipCode: '76248', municipName: 'EL CERRITO', name: 'VALLE DEL CAUCA' },
  { municipCode: '52250', municipName: 'EL CHARCO', name: 'NARIÑO' },
  { municipCode: '15244', municipName: 'EL COCUY', name: 'BOYACÁ' },
  { municipCode: '25245', municipName: 'EL COLEGIO', name: 'CUNDINAMARCA' },
  { municipCode: '20238', municipName: 'EL COPEY', name: 'CESAR' },
  { municipCode: '18247', municipName: 'EL DONCELLO', name: 'CAQUETÁ' },
  { municipCode: '50270', municipName: 'EL DORADO', name: 'META' },
  { municipCode: '76250', municipName: 'EL DOVIO', name: 'VALLE DEL CAUCA' },
  { municipCode: '91263', municipName: 'EL ENCANTO', name: 'AMAZONAS' },
  { municipCode: '15248', municipName: 'EL ESPINO', name: 'BOYACÁ' },
  { municipCode: '68245', municipName: 'EL GUACAMAYO', name: 'SANTANDER' },
  { municipCode: '13248', municipName: 'EL GUAMO', name: 'BOLÍVAR' },
  { municipCode: '27250', municipName: 'EL LITORAL DEL SAN JUAN', name: 'CHOCÓ' },
  { municipCode: '44110', municipName: 'EL MOLINO', name: 'LA GUAJIRA' },
  { municipCode: '20250', municipName: 'EL PASO', name: 'CESAR' },
  { municipCode: '18256', municipName: 'EL PAUJÍL', name: 'CAQUETÁ' },
  { municipCode: '52254', municipName: 'EL PEÑOL', name: 'NARIÑO' },
  { municipCode: '13268', municipName: 'EL PEÑÓN', name: 'BOLÍVAR' },
  { municipCode: '25258', municipName: 'EL PEÑÓN', name: 'CUNDINAMARCA' },
  { municipCode: '68250', municipName: 'EL PEÑÓN', name: 'SANTANDER' },
  { municipCode: '47258', municipName: 'EL PIÑÓN', name: 'MAGDALENA' },
  { municipCode: '68255', municipName: 'EL PLAYÓN', name: 'SANTANDER' },
  { municipCode: '47268', municipName: 'EL RETÉN', name: 'MAGDALENA' },
  { municipCode: '95025', municipName: 'EL RETORNO', name: 'GUAVIARE' },
  { municipCode: '70233', municipName: 'EL ROBLE', name: 'SUCRE' },
  { municipCode: '25260', municipName: 'EL ROSAL', name: 'CUNDINAMARCA' },
  { municipCode: '52256', municipName: 'EL ROSARIO', name: 'NARIÑO' },
  { municipCode: '05697', municipName: 'EL SANTUARIO', name: 'ANTIOQUIA' },
  { municipCode: '52258', municipName: 'EL TABLÓN DE GÓMEZ', name: 'NARIÑO' },
  { municipCode: '19256', municipName: 'EL TAMBO', name: 'CAUCA' },
  { municipCode: '52260', municipName: 'EL TAMBO', name: 'NARIÑO' },
  { municipCode: '54250', municipName: 'EL TARRA', name: 'NORTE DE SANTANDER' },
  { municipCode: '54261', municipName: 'EL ZULIA', name: 'NORTE DE SANTANDER' },
  { municipCode: '41244', municipName: 'ELÍAS', name: 'HUILA' },
  { municipCode: '68264', municipName: 'ENCINO', name: 'SANTANDER' },
  { municipCode: '68266', municipName: 'ENCISO', name: 'SANTANDER' },
  { municipCode: '05264', municipName: 'ENTRERRÍOS', name: 'ANTIOQUIA' },
  { municipCode: '05266', municipName: 'ENVIGADO', name: 'ANTIOQUIA' },
  { municipCode: '73268', municipName: 'ESPINAL', name: 'TOLIMA' },
  { municipCode: '25269', municipName: 'FACATATIVÁ', name: 'CUNDINAMARCA' },
  { municipCode: '73270', municipName: 'FALAN', name: 'TOLIMA' },
  { municipCode: '17272', municipName: 'FILADELFIA', name: 'CALDAS' },
  { municipCode: '63272', municipName: 'FILANDIA', name: 'QUINDÍO' },
  { municipCode: '15272', municipName: 'FIRAVITOBA', name: 'BOYACÁ' },
  { municipCode: '73275', municipName: 'FLANDES', name: 'TOLIMA' },
  { municipCode: '18001', municipName: 'FLORENCIA', name: 'CAQUETÁ' },
  { municipCode: '19290', municipName: 'FLORENCIA', name: 'CAUCA' },
  { municipCode: '15276', municipName: 'FLORESTA', name: 'BOYACÁ' },
  { municipCode: '68271', municipName: 'FLORIÁN', name: 'SANTANDER' },
  { municipCode: '76275', municipName: 'FLORIDA', name: 'VALLE DEL CAUCA' },
  { municipCode: '68276', municipName: 'FLORIDABLANCA', name: 'SANTANDER' },
  { municipCode: '25279', municipName: 'FÓMEQUE', name: 'CUNDINAMARCA' },
  { municipCode: '44279', municipName: 'FONSECA', name: 'LA GUAJIRA' },
  { municipCode: '81300', municipName: 'FORTUL', name: 'ARAUCA' },
  { municipCode: '25281', municipName: 'FOSCA', name: 'CUNDINAMARCA' },
  { municipCode: '52520', municipName: 'FRANCISCO PIZARRO', name: 'NARIÑO' },
  { municipCode: '05282', municipName: 'FREDONIA', name: 'ANTIOQUIA' },
  { municipCode: '73283', municipName: 'FRESNO', name: 'TOLIMA' },
  { municipCode: '05284', municipName: 'FRONTINO', name: 'ANTIOQUIA' },
  { municipCode: '50287', municipName: 'FUENTE DE ORO', name: 'META' },
  { municipCode: '47288', municipName: 'FUNDACIÓN', name: 'MAGDALENA' },
  { municipCode: '52287', municipName: 'FUNES', name: 'NARIÑO' },
  { municipCode: '25286', municipName: 'FUNZA', name: 'CUNDINAMARCA' },
  { municipCode: '25288', municipName: 'FÚQUENE', name: 'CUNDINAMARCA' },
  { municipCode: '25290', municipName: 'FUSAGASUGÁ', name: 'CUNDINAMARCA' },
  { municipCode: '25293', municipName: 'GACHALÁ', name: 'CUNDINAMARCA' },
  { municipCode: '25295', municipName: 'GACHANCIPÁ', name: 'CUNDINAMARCA' },
  { municipCode: '15293', municipName: 'GACHANTIVÁ', name: 'BOYACÁ' },
  { municipCode: '25297', municipName: 'GACHETÁ', name: 'CUNDINAMARCA' },
  { municipCode: '68296', municipName: 'GALÁN', name: 'SANTANDER' },
  { municipCode: '08296', municipName: 'GALAPA', name: 'ATLÁNTICO' },
  { municipCode: '70235', municipName: 'GALERAS', name: 'SUCRE' },
  { municipCode: '25299', municipName: 'GAMA', name: 'CUNDINAMARCA' },
  { municipCode: '20295', municipName: 'GAMARRA', name: 'CESAR' },
  { municipCode: '68298', municipName: 'GÁMBITA', name: 'SANTANDER' },
  { municipCode: '15296', municipName: 'GÁMEZA', name: 'BOYACÁ' },
  { municipCode: '15299', municipName: 'GARAGOA', name: 'BOYACÁ' },
  { municipCode: '41298', municipName: 'GARZÓN', name: 'HUILA' },
  { municipCode: '63302', municipName: 'GÉNOVA', name: 'QUINDÍO' },
  { municipCode: '41306', municipName: 'GIGANTE', name: 'HUILA' },
  { municipCode: '76306', municipName: 'GINEBRA', name: 'VALLE DEL CAUCA' },
  { municipCode: '05306', municipName: 'GIRALDO', name: 'ANTIOQUIA' },
  { municipCode: '25307', municipName: 'GIRARDOT', name: 'CUNDINAMARCA' },
  { municipCode: '05308', municipName: 'GIRARDOTA', name: 'ANTIOQUIA' },
  { municipCode: '68307', municipName: 'GIRÓN', name: 'SANTANDER' },
  { municipCode: '05310', municipName: 'GÓMEZ PLATA', name: 'ANTIOQUIA' },
  { municipCode: '20310', municipName: 'GONZÁLEZ', name: 'CESAR' },
  { municipCode: '54313', municipName: 'GRAMALOTE', name: 'NORTE DE SANTANDER' },
  { municipCode: '05313', municipName: 'GRANADA', name: 'ANTIOQUIA' },
  { municipCode: '25312', municipName: 'GRANADA', name: 'CUNDINAMARCA' },
  { municipCode: '50313', municipName: 'GRANADA', name: 'META' },
  { municipCode: '68318', municipName: 'GUACA', name: 'SANTANDER' },
  { municipCode: '15317', municipName: 'GUACAMAYAS', name: 'BOYACÁ' },
  { municipCode: '76318', municipName: 'GUACARÍ', name: 'VALLE DEL CAUCA' },
  { municipCode: '19300', municipName: 'GUACHENÉ', name: 'CAUCA' },
  { municipCode: '25317', municipName: 'GUACHETÁ', name: 'CUNDINAMARCA' },
  { municipCode: '52317', municipName: 'GUACHUCAL', name: 'NARIÑO' },
  { municipCode: '76111', municipName: 'GUADALAJARA DE BUGA', name: 'VALLE DEL CAUCA' },
  { municipCode: '05315', municipName: 'GUADALUPE', name: 'ANTIOQUIA' },
  { municipCode: '41319', municipName: 'GUADALUPE', name: 'HUILA' },
  { municipCode: '68320', municipName: 'GUADALUPE', name: 'SANTANDER' },
  { municipCode: '25320', municipName: 'GUADUAS', name: 'CUNDINAMARCA' },
  { municipCode: '52320', municipName: 'GUAITARILLA', name: 'NARIÑO' },
  { municipCode: '52323', municipName: 'GUALMATÁN', name: 'NARIÑO' },
  { municipCode: '47318', municipName: 'GUAMAL', name: 'MAGDALENA' },
  { municipCode: '50318', municipName: 'GUAMAL', name: 'META' },
  { municipCode: '73319', municipName: 'GUAMO', name: 'TOLIMA' },
  { municipCode: '19318', municipName: 'GUAPI', name: 'CAUCA' },
  { municipCode: '68322', municipName: 'GUAPOTÁ', name: 'SANTANDER' },
  { municipCode: '70265', municipName: 'GUARANDA', name: 'SUCRE' },
  { municipCode: '05318', municipName: 'GUARNE', name: 'ANTIOQUIA' },
  { municipCode: '25322', municipName: 'GUASCA', name: 'CUNDINAMARCA' },
  { municipCode: '05321', municipName: 'GUATAPÉ', name: 'ANTIOQUIA' },
  { municipCode: '25324', municipName: 'GUATAQUÍ', name: 'CUNDINAMARCA' },
  { municipCode: '25326', municipName: 'GUATAVITA', name: 'CUNDINAMARCA' },
  { municipCode: '15322', municipName: 'GUATEQUE', name: 'BOYACÁ' },
  { municipCode: '66318', municipName: 'GUÁTICA', name: 'RISARALDA' },
  { municipCode: '68324', municipName: 'GUAVATÁ', name: 'SANTANDER' },
  { municipCode: '25328', municipName: 'GUAYABAL DE SÍQUIMA', name: 'CUNDINAMARCA' },
  { municipCode: '25335', municipName: 'GUAYABETAL', name: 'CUNDINAMARCA' },
  { municipCode: '15325', municipName: 'GUAYATÁ', name: 'BOYACÁ' },
  { municipCode: '68327', municipName: 'GÜEPSA', name: 'SANTANDER' },
  { municipCode: '15332', municipName: 'GÜICÁN DE LA SIERRA', name: 'BOYACÁ' },
  { municipCode: '25339', municipName: 'GUTIÉRREZ', name: 'CUNDINAMARCA' },
  { municipCode: '54344', municipName: 'HACARÍ', name: 'NORTE DE SANTANDER' },
  { municipCode: '13300', municipName: 'HATILLO DE LOBA', name: 'BOLÍVAR' },
  { municipCode: '68344', municipName: 'HATO', name: 'SANTANDER' },
  { municipCode: '85125', municipName: 'HATO COROZAL', name: 'CASANARE' },
  { municipCode: '44378', municipName: 'HATONUEVO', name: 'LA GUAJIRA' },
  { municipCode: '05347', municipName: 'HELICONIA', name: 'ANTIOQUIA' },
  { municipCode: '54347', municipName: 'HERRÁN', name: 'NORTE DE SANTANDER' },
  { municipCode: '73347', municipName: 'HERVEO', name: 'TOLIMA' },
  { municipCode: '05353', municipName: 'HISPANIA', name: 'ANTIOQUIA' },
  { municipCode: '41349', municipName: 'HOBO', name: 'HUILA' },
  { municipCode: '73349', municipName: 'HONDA', name: 'TOLIMA' },
  { municipCode: '73001', municipName: 'IBAGUÉ', name: 'TOLIMA' },
  { municipCode: '73352', municipName: 'ICONONZO', name: 'TOLIMA' },
  { municipCode: '52352', municipName: 'ILES', name: 'NARIÑO' },
  { municipCode: '52354', municipName: 'IMUÉS', name: 'NARIÑO' },
  { municipCode: '94001', municipName: 'INÍRIDA', name: 'GUAINÍA' },
  { municipCode: '19355', municipName: 'INZÁ', name: 'CAUCA' },
  { municipCode: '52356', municipName: 'IPIALES', name: 'NARIÑO' },
  { municipCode: '41357', municipName: 'ÍQUIRA', name: 'HUILA' },
  { municipCode: '41359', municipName: 'ISNOS', name: 'HUILA' },
  { municipCode: '27361', municipName: 'ISTMINA', name: 'CHOCÓ' },
  { municipCode: '05360', municipName: 'ITAGÜÍ', name: 'ANTIOQUIA' },
  { municipCode: '05361', municipName: 'ITUANGO', name: 'ANTIOQUIA' },
  { municipCode: '15362', municipName: 'IZA', name: 'BOYACÁ' },
  { municipCode: '19364', municipName: 'JAMBALÓ', name: 'CAUCA' },
  { municipCode: '76364', municipName: 'JAmunicipNameDÍ', name: 'VALLE DEL CAUCA' },
  { municipCode: '05364', municipName: 'JARDÍN', name: 'ANTIOQUIA' },
  { municipCode: '15367', municipName: 'JENESANO', name: 'BOYACÁ' },
  { municipCode: '05368', municipName: 'JERICÓ', name: 'ANTIOQUIA' },
  { municipCode: '15368', municipName: 'JERICÓ', name: 'BOYACÁ' },
  { municipCode: '25368', municipName: 'JERUSALÉN', name: 'CUNDINAMARCA' },
  { municipCode: '68368', municipName: 'JESÚS MARÍA', name: 'SANTANDER' },
  { municipCode: '68370', municipName: 'JORDÁN', name: 'SANTANDER' },
  { municipCode: '08372', municipName: 'JUAN DE ACOSTA', name: 'ATLÁNTICO' },
  { municipCode: '25372', municipName: 'JUNÍN', name: 'CUNDINAMARCA' },
  { municipCode: '27372', municipName: 'JURADÓ', name: 'CHOCÓ' },
  { municipCode: '23350', municipName: 'LA APARTADA', name: 'CÓRDOBA' },
  { municipCode: '41378', municipName: 'LA ARGENTINA', name: 'HUILA' },
  { municipCode: '68377', municipName: 'LA BELLEZA', name: 'SANTANDER' },
  { municipCode: '25377', municipName: 'LA CALERA', name: 'CUNDINAMARCA' },
  { municipCode: '15380', municipName: 'LA CAPILLA', name: 'BOYACÁ' },
  { municipCode: '05376', municipName: 'LA CEJA', name: 'ANTIOQUIA' },
  { municipCode: '66383', municipName: 'LA CELIA', name: 'RISARALDA' },
  { municipCode: '91405', municipName: 'LA CHORRERA', name: 'AMAZONAS' },
  { municipCode: '52378', municipName: 'LA CRUZ', name: 'NARIÑO' },
  { municipCode: '76377', municipName: 'LA CUMBRE', name: 'VALLE DEL CAUCA' },
  { municipCode: '17380', municipName: 'LA DORADA', name: 'CALDAS' },
  { municipCode: '54385', municipName: 'LA ESPERANZA', name: 'NORTE DE SANTANDER' },
  { municipCode: '05380', municipName: 'LA ESTRELLA', name: 'ANTIOQUIA' },
  { municipCode: '52381', municipName: 'LA FLORIDA', name: 'NARIÑO' },
  { municipCode: '20383', municipName: 'LA GLORIA', name: 'CESAR' },
  { municipCode: '94885', municipName: 'LA GUADALUPE', name: 'GUAINÍA' },
  { municipCode: '20400', municipName: 'LA JAGUA DE IBIRICO', name: 'CESAR' },
  { municipCode: '44420', municipName: 'LA JAGUA DEL PILAR', name: 'LA GUAJIRA' },
  { municipCode: '52385', municipName: 'LA LLANADA', name: 'NARIÑO' },
  { municipCode: '50350', municipName: 'LA MACARENA', name: 'META' },
  { municipCode: '17388', municipName: 'LA MERCED', name: 'CALDAS' },
  { municipCode: '25386', municipName: 'LA MESA', name: 'CUNDINAMARCA' },
  { municipCode: '18410', municipName: 'LA MONTAÑITA', name: 'CAQUETÁ' },
  { municipCode: '25394', municipName: 'LA PALMA', name: 'CUNDINAMARCA' },
  { municipCode: '20621', municipName: 'LA PAZ', name: 'CESAR' },
  { municipCode: '68397', municipName: 'LA PAZ', name: 'SANTANDER' },
  { municipCode: '91407', municipName: 'LA PEDRERA', name: 'AMAZONAS' },
  { municipCode: '25398', municipName: 'LA PEÑA', name: 'CUNDINAMARCA' },
  { municipCode: '05390', municipName: 'LA PINTADA', name: 'ANTIOQUIA' },
  { municipCode: '41396', municipName: 'LA PLATA', name: 'HUILA' },
  { municipCode: '54398', municipName: 'LA PLAYA', name: 'NORTE DE SANTANDER' },
  { municipCode: '99524', municipName: 'LA PRIMAVERA', name: 'VICHADA' },
  { municipCode: '85136', municipName: 'LA SALINA', name: 'CASANARE' },
  { municipCode: '19392', municipName: 'LA SIERRA', name: 'CAUCA' },
  { municipCode: '63401', municipName: 'LA TEBAIDA', name: 'QUINDÍO' },
  { municipCode: '52390', municipName: 'LA TOLA', name: 'NARIÑO' },
  { municipCode: '05400', municipName: 'LA UNIÓN', name: 'ANTIOQUIA' },
  { municipCode: '52399', municipName: 'LA UNIÓN', name: 'NARIÑO' },
  { municipCode: '70400', municipName: 'LA UNIÓN', name: 'SUCRE' },
  { municipCode: '76400', municipName: 'LA UNIÓN', name: 'VALLE DEL CAUCA' },
  { municipCode: '15403', municipName: 'LA UVITA', name: 'BOYACÁ' },
  { municipCode: '19397', municipName: 'LA VEGA', name: 'CAUCA' },
  { municipCode: '25402', municipName: 'LA VEGA', name: 'CUNDINAMARCA' },
  { municipCode: '91430', municipName: 'LA VICTORIA', name: 'AMAZONAS' },
  { municipCode: '15401', municipName: 'LA VICTORIA', name: 'BOYACÁ' },
  { municipCode: '76403', municipName: 'LA VICTORIA', name: 'VALLE DEL CAUCA' },
  { municipCode: '66400', municipName: 'LA VIRGINIA', name: 'RISARALDA' },
  { municipCode: '54377', municipName: 'LABATECA', name: 'NORTE DE SANTANDER' },
  { municipCode: '15377', municipName: 'LABRANZAGRANDE', name: 'BOYACÁ' },
  { municipCode: '68385', municipName: 'LANDÁZURI', name: 'SANTANDER' },
  { municipCode: '68406', municipName: 'LEBRIJA', name: 'SANTANDER' },
  { municipCode: '52405', municipName: 'LEIVA', name: 'NARIÑO' },
  { municipCode: '50400', municipName: 'LEJANÍAS', name: 'META' },
  { municipCode: '25407', municipName: 'LENGUAZAQUE', name: 'CUNDINAMARCA' },
  { municipCode: '73408', municipName: 'LÉRIDA', name: 'TOLIMA' },
  { municipCode: '91001', municipName: 'LETICIA', name: 'AMAZONAS' },
  { municipCode: '73411', municipName: 'LÍBANO', name: 'TOLIMA' },
  { municipCode: '05411', municipName: 'LIBORINA', name: 'ANTIOQUIA' },
  { municipCode: '52411', municipName: 'LINARES', name: 'NARIÑO' },
  { municipCode: '27413', municipName: 'LLORÓ', name: 'CHOCÓ' },
  { municipCode: '19418', municipName: 'LÓPEZ DE MICAY', name: 'CAUCA' },
  { municipCode: '23417', municipName: 'LORICA', name: 'CÓRDOBA' },
  { municipCode: '52418', municipName: 'LOS ANDES', name: 'NARIÑO' },
  { municipCode: '23419', municipName: 'LOS CÓRDOBAS', name: 'CÓRDOBA' },
  { municipCode: '70418', municipName: 'LOS PALMITOS', name: 'SUCRE' },
  { municipCode: '54405', municipName: 'LOS PATIOS', name: 'NORTE DE SANTANDER' },
  { municipCode: '68418', municipName: 'LOS SANTOS', name: 'SANTANDER' },
  { municipCode: '54418', municipName: 'LOURDES', name: 'NORTE DE SANTANDER' },
  { municipCode: '08421', municipName: 'LURUACO', name: 'ATLÁNTICO' },
  { municipCode: '15425', municipName: 'MACANAL', name: 'BOYACÁ' },
  { municipCode: '68425', municipName: 'MACARAVITA', name: 'SANTANDER' },
  { municipCode: '05425', municipName: 'MACEO', name: 'ANTIOQUIA' },
  { municipCode: '25426', municipName: 'MACHETÁ', name: 'CUNDINAMARCA' },
  { municipCode: '25430', municipName: 'MADRID', name: 'CUNDINAMARCA' },
  { municipCode: '13430', municipName: 'MAGANGUÉ', name: 'BOLÍVAR' },
  { municipCode: '52427', municipName: 'MAGÜÍ', name: 'NARIÑO' },
  { municipCode: '13433', municipName: 'MAHATES', name: 'BOLÍVAR' },
  { municipCode: '44430', municipName: 'MAICAO', name: 'LA GUAJIRA' },
  { municipCode: '70429', municipName: 'MAJAGUAL', name: 'SUCRE' },
  { municipCode: '68432', municipName: 'MÁLAGA', name: 'SANTANDER' },
  { municipCode: '08433', municipName: 'MALAMBO', name: 'ATLÁNTICO' },
  { municipCode: '52435', municipName: 'MALLAMA', name: 'NARIÑO' },
  { municipCode: '08436', municipName: 'MANATÍ', name: 'ATLÁNTICO' },
  { municipCode: '44560', municipName: 'MANAURE', name: 'LA GUAJIRA' },
  { municipCode: '20443', municipName: 'MANAURE BALCÓN DEL CESAR', name: 'CESAR' },
  { municipCode: '85139', municipName: 'MANÍ', name: 'CASANARE' },
  { municipCode: '17001', municipName: 'MANIZALES', name: 'CALDAS' },
  { municipCode: '25436', municipName: 'MANTA', name: 'CUNDINAMARCA' },
  { municipCode: '17433', municipName: 'MANZANARES', name: 'CALDAS' },
  { municipCode: '50325', municipName: 'MAPIRIPÁN', name: 'META' },
  { municipCode: '13440', municipName: 'MARGARITA', name: 'BOLÍVAR' },
  { municipCode: '13442', municipName: 'MARÍA LA BAJA', name: 'BOLÍVAR' },
  { municipCode: '05440', municipName: 'MARINILLA', name: 'ANTIOQUIA' },
  { municipCode: '15442', municipName: 'MARIPÍ', name: 'BOYACÁ' },
  { municipCode: '17442', municipName: 'MARMATO', name: 'CALDAS' },
  { municipCode: '17444', municipName: 'MARQUETALIA', name: 'CALDAS' },
  { municipCode: '66440', municipName: 'MARSELLA', name: 'RISARALDA' },
  { municipCode: '17446', municipName: 'MARULANDA', name: 'CALDAS' },
  { municipCode: '68444', municipName: 'MATANZA', name: 'SANTANDER' },
  { municipCode: '05001', municipName: 'MEDELLÍN', name: 'ANTIOQUIA' },
  { municipCode: '25438', municipName: 'MEDINA', name: 'CUNDINAMARCA' },
  { municipCode: '27425', municipName: 'MEDIO ATRATO', name: 'CHOCÓ' },
  { municipCode: '27430', municipName: 'MEDIO BAUDÓ', name: 'CHOCÓ' },
  { municipCode: '27450', municipName: 'MEDIO SAN JUAN', name: 'CHOCÓ' },
  { municipCode: '73449', municipName: 'MELGAR', name: 'TOLIMA' },
  { municipCode: '19450', municipName: 'MERCADERES', name: 'CAUCA' },
  { municipCode: '50330', municipName: 'MESETAS', name: 'META' },
  { municipCode: '18460', municipName: 'MILÁN', name: 'CAQUETÁ' },
  { municipCode: '15455', municipName: 'MIRAFLORES', name: 'BOYACÁ' },
  { municipCode: '95200', municipName: 'MIRAFLORES', name: 'GUAVIARE' },
  { municipCode: '19455', municipName: 'MIRANDA', name: 'CAUCA' },
  { municipCode: '91460', municipName: 'MIRITÍ – PARANÁ', name: 'AMAZONAS' },
  { municipCode: '66456', municipName: 'MISTRATÓ', name: 'RISARALDA' },
  { municipCode: '97001', municipName: 'MITÚ', name: 'VAUPÉS' },
  { municipCode: '86001', municipName: 'MOCOA', name: 'PUTUMAYO' },
  { municipCode: '68464', municipName: 'MOGOTES', name: 'SANTANDER' },
  { municipCode: '68468', municipName: 'MOLAGAVITA', name: 'SANTANDER' },
  { municipCode: '23464', municipName: 'MOMIL', name: 'CÓRDOBA' },
  { municipCode: '15464', municipName: 'MONGUA', name: 'BOYACÁ' },
  { municipCode: '15466', municipName: 'MONGUÍ', name: 'BOYACÁ' },
  { municipCode: '15469', municipName: 'MONIQUIRÁ', name: 'BOYACÁ' },
  { municipCode: '05467', municipName: 'MONTEBELLO', name: 'ANTIOQUIA' },
  { municipCode: '13458', municipName: 'MONTECRISTO', name: 'BOLÍVAR' },
  { municipCode: '23466', municipName: 'MONTELÍBANO', name: 'CÓRDOBA' },
  { municipCode: '63470', municipName: 'MONTENEGRO', name: 'QUINDÍO' },
  { municipCode: '23001', municipName: 'MONTERÍA', name: 'CÓRDOBA' },
  { municipCode: '85162', municipName: 'MONTERREY', name: 'CASANARE' },
  { municipCode: '23500', municipName: 'MOÑITOS', name: 'CÓRDOBA' },
  { municipCode: '13473', municipName: 'MORALES', name: 'BOLÍVAR' },
  { municipCode: '19473', municipName: 'MORALES', name: 'CAUCA' },
  { municipCode: '18479', municipName: 'MORELIA', name: 'CAQUETÁ' },
  { municipCode: '94888', municipName: 'MORICHAL', name: 'GUAINÍA' },
  { municipCode: '70473', municipName: 'MORROA', name: 'SUCRE' },
  { municipCode: '25473', municipName: 'MOSQUERA', name: 'CUNDINAMARCA' },
  { municipCode: '52473', municipName: 'MOSQUERA', name: 'NARIÑO' },
  { municipCode: '15476', municipName: 'MOTAVITA', name: 'BOYACÁ' },
  { municipCode: '73461', municipName: 'MURILLO', name: 'TOLIMA' },
  { municipCode: '05475', municipName: 'MURINDÓ', name: 'ANTIOQUIA' },
  { municipCode: '05480', municipName: 'MUTATÁ', name: 'ANTIOQUIA' },
  { municipCode: '54480', municipName: 'MUTISCUA', name: 'NORTE DE SANTANDER' },
  { municipCode: '15480', municipName: 'MUZO', name: 'BOYACÁ' },
  { municipCode: '05483', municipName: 'NARIÑO', name: 'ANTIOQUIA' },
  { municipCode: '25483', municipName: 'NARIÑO', name: 'CUNDINAMARCA' },
  { municipCode: '52480', municipName: 'NARIÑO', name: 'NARIÑO' },
  { municipCode: '41483', municipName: 'NÁTAGA', name: 'HUILA' },
  { municipCode: '73483', municipName: 'NATAGAIMA', name: 'TOLIMA' },
  { municipCode: '05495', municipName: 'NECHÍ', name: 'ANTIOQUIA' },
  { municipCode: '05490', municipName: 'NECOCLÍ', name: 'ANTIOQUIA' },
  { municipCode: '17486', municipName: 'NEIRA', name: 'CALDAS' },
  { municipCode: '41001', municipName: 'NEIVA', name: 'HUILA' },
  { municipCode: '25486', municipName: 'NEMOCÓN', name: 'CUNDINAMARCA' },
  { municipCode: '25488', municipName: 'NILO', name: 'CUNDINAMARCA' },
  { municipCode: '25489', municipName: 'NIMAIMA', name: 'CUNDINAMARCA' },
  { municipCode: '15491', municipName: 'NOBSA', name: 'BOYACÁ' },
  { municipCode: '25491', municipName: 'NOCAIMA', name: 'CUNDINAMARCA' },
  { municipCode: '17495', municipName: 'NORCASIA', name: 'CALDAS' },
  { municipCode: '13490', municipName: 'NOROSÍ', name: 'BOLÍVAR' },
  { municipCode: '27491', municipName: 'NÓVITA', name: 'CHOCÓ' },
  { municipCode: '47460', municipName: 'NUEVA GRANADA', name: 'MAGDALENA' },
  { municipCode: '15494', municipName: 'NUEVO COLÓN', name: 'BOYACÁ' },
  { municipCode: '85225', municipName: 'NUNCHÍA', name: 'CASANARE' },
  { municipCode: '27495', municipName: 'NUQUÍ', name: 'CHOCÓ' },
  { municipCode: '76497', municipName: 'OBANDO', name: 'VALLE DEL CAUCA' },
  { municipCode: '68498', municipName: 'OCAMONTE', name: 'SANTANDER' },
  { municipCode: '54498', municipName: 'OCAÑA', name: 'NORTE DE SANTANDER' },
  { municipCode: '68500', municipName: 'OIBA', name: 'SANTANDER' },
  { municipCode: '15500', municipName: 'OICATÁ', name: 'BOYACÁ' },
  { municipCode: '05501', municipName: 'OLAYA', name: 'ANTIOQUIA' },
  { municipCode: '52490', municipName: 'OLAYA HERRERA', name: 'NARIÑO' },
  { municipCode: '68502', municipName: 'ONZAGA', name: 'SANTANDER' },
  { municipCode: '41503', municipName: 'OPORAPA', name: 'HUILA' },
  { municipCode: '86320', municipName: 'ORITO', name: 'PUTUMAYO' },
  { municipCode: '85230', municipName: 'OROCUÉ', name: 'CASANARE' },
  { municipCode: '73504', municipName: 'ORTEGA', name: 'TOLIMA' },
  { municipCode: '52506', municipName: 'OSPINA', name: 'NARIÑO' },
  { municipCode: '15507', municipName: 'OTANCHE', name: 'BOYACÁ' },
  { municipCode: '70508', municipName: 'OVEJAS', name: 'SUCRE' },
  { municipCode: '15511', municipName: 'PACHAVITA', name: 'BOYACÁ' },
  { municipCode: '25513', municipName: 'PACHO', name: 'CUNDINAMARCA' },
  { municipCode: '97511', municipName: 'PACOA', name: 'VAUPÉS' },
  { municipCode: '17513', municipName: 'PÁCORA', name: 'CALDAS' },
  { municipCode: '19513', municipName: 'PADILLA', name: 'CAUCA' },
  { municipCode: '15514', municipName: 'PÁEZ', name: 'BOYACÁ' },
  { municipCode: '19517', municipName: 'PÁEZ', name: 'CAUCA' },
  { municipCode: '41518', municipName: 'PAICOL', name: 'HUILA' },
  { municipCode: '20517', municipName: 'PAILITAS', name: 'CESAR' },
  { municipCode: '25518', municipName: 'PAIME', name: 'CUNDINAMARCA' },
  { municipCode: '15516', municipName: 'PAIPA', name: 'BOYACÁ' },
  { municipCode: '15518', municipName: 'PAJARITO', name: 'BOYACÁ' },
  { municipCode: '41524', municipName: 'PALERMO', name: 'HUILA' },
  { municipCode: '17524', municipName: 'PALESTINA', name: 'CALDAS' },
  { municipCode: '41530', municipName: 'PALESTINA', name: 'HUILA' },
  { municipCode: '68522', municipName: 'PALMAR', name: 'SANTANDER' },
  { municipCode: '08520', municipName: 'PALMAR DE VARELA', name: 'ATLÁNTICO' },
  { municipCode: '68524', municipName: 'PALMAS DEL SOCORRO', name: 'SANTANDER' },
  { municipCode: '76520', municipName: 'PALMIRA', name: 'VALLE DEL CAUCA' },
  { municipCode: '70523', municipName: 'PALMITO', name: 'SUCRE' },
  { municipCode: '73520', municipName: 'PALOCABILDO', name: 'TOLIMA' },
  { municipCode: '54518', municipName: 'PAMPLONA', name: 'NORTE DE SANTANDER' },
  { municipCode: '54520', municipName: 'PAMPLONITA', name: 'NORTE DE SANTANDER' },
  { municipCode: '94887', municipName: 'PANA PANA', name: 'GUAINÍA' },
  { municipCode: '25524', municipName: 'PANDI', name: 'CUNDINAMARCA' },
  { municipCode: '15522', municipName: 'PANQUEBA', name: 'BOYACÁ' },
  { municipCode: '97777', municipName: 'PAPUNAHUA', name: 'VAUPÉS' },
  { municipCode: '68533', municipName: 'PÁRAMO', name: 'SANTANDER' },
  { municipCode: '25530', municipName: 'PARATEBUENO', name: 'CUNDINAMARCA' },
  { municipCode: '25535', municipName: 'PASCA', name: 'CUNDINAMARCA' },
  { municipCode: '52001', municipName: 'PASTO', name: 'NARIÑO' },
  { municipCode: '19532', municipName: 'PATÍA', name: 'CAUCA' },
  { municipCode: '15531', municipName: 'PAUNA', name: 'BOYACÁ' },
  { municipCode: '15533', municipName: 'PAYA', name: 'BOYACÁ' },
  { municipCode: '85250', municipName: 'PAZ DE ARIPORO', name: 'CASANARE' },
  { municipCode: '15537', municipName: 'PAZ DE RÍO', name: 'BOYACÁ' },
  { municipCode: '47541', municipName: 'PEDRAZA', name: 'MAGDALENA' },
  { municipCode: '20550', municipName: 'PELAYA', name: 'CESAR' },
  { municipCode: '17541', municipName: 'PENSILVANIA', name: 'CALDAS' },
  { municipCode: '05541', municipName: 'PEÑOL', name: 'ANTIOQUIA' },
  { municipCode: '05543', municipName: 'PEQUE', name: 'ANTIOQUIA' },
  { municipCode: '66001', municipName: 'PEREIRA', name: 'RISARALDA' },
  { municipCode: '15542', municipName: 'PESCA', name: 'BOYACÁ' },
  { municipCode: '19533', municipName: 'PIAMONTE', name: 'CAUCA' },
  { municipCode: '68547', municipName: 'PIEDECUESTA', name: 'SANTANDER' },
  { municipCode: '73547', municipName: 'PIEDRAS', name: 'TOLIMA' },
  { municipCode: '19548', municipName: 'PIENDAMÓ – TUNÍA', name: 'CAUCA' },
  { municipCode: '63548', municipName: 'PIJAO', name: 'QUINDÍO' },
  { municipCode: '47545', municipName: 'PIJIÑO DEL CARMEN', name: 'MAGDALENA' },
  { municipCode: '68549', municipName: 'PINCHOTE', name: 'SANTANDER' },
  { municipCode: '13549', municipName: 'PINILLOS', name: 'BOLÍVAR' },
  { municipCode: '08549', municipName: 'PIOJÓ', name: 'ATLÁNTICO' },
  { municipCode: '15550', municipName: 'PISBA', name: 'BOYACÁ' },
  { municipCode: '41548', municipName: 'PITAL', name: 'HUILA' },
  { municipCode: '41551', municipName: 'PITALITO', name: 'HUILA' },
  { municipCode: '47551', municipName: 'PIVIJAY', name: 'MAGDALENA' },
  { municipCode: '73555', municipName: 'PLANADAS', name: 'TOLIMA' },
  { municipCode: '23555', municipName: 'PLANETA RICA', name: 'CÓRDOBA' },
  { municipCode: '47555', municipName: 'PLATO', name: 'MAGDALENA' },
  { municipCode: '52540', municipName: 'POLICARPA', name: 'NARIÑO' },
  { municipCode: '08558', municipName: 'POLONUEVO', name: 'ATLÁNTICO' },
  { municipCode: '08560', municipName: 'PONEDERA', name: 'ATLÁNTICO' },
  { municipCode: '19001', municipName: 'POPAYÁN', name: 'CAUCA' },
  { municipCode: '85263', municipName: 'PORE', name: 'CASANARE' },
  { municipCode: '52560', municipName: 'POTOSÍ', name: 'NARIÑO' },
  { municipCode: '76563', municipName: 'PRADERA', name: 'VALLE DEL CAUCA' },
  { municipCode: '73563', municipName: 'PRADO', name: 'TOLIMA' },
  { municipCode: '88564', municipName: 'PROVIDENCIA', name: 'ARCHIPIÉLAGO DE SAN ANDRÉS. PROVIDENCIA Y SANTA CATALINA' },
  { municipCode: '52565', municipName: 'PROVIDENCIA', name: 'NARIÑO' },
  { municipCode: '20570', municipName: 'PUEBLO BELLO', name: 'CESAR' },
  { municipCode: '23570', municipName: 'PUEBLO NUEVO', name: 'CÓRDOBA' },
  { municipCode: '66572', municipName: 'PUEBLO RICO', name: 'RISARALDA' },
  { municipCode: '05576', municipName: 'PUEBLORRICO', name: 'ANTIOQUIA' },
  { municipCode: '47570', municipName: 'PUEBLOVIEJO', name: 'MAGDALENA' },
  { municipCode: '68572', municipName: 'PUENTE NACIONAL', name: 'SANTANDER' },
  { municipCode: '52573', municipName: 'PUERRES', name: 'NARIÑO' },
  { municipCode: '91530', municipName: 'PUERTO ALEGRÍA', name: 'AMAZONAS' },
  { municipCode: '91536', municipName: 'PUERTO ARICA', name: 'AMAZONAS' },
  { municipCode: '86568', municipName: 'PUERTO ASÍS', name: 'PUTUMAYO' },
  { municipCode: '05579', municipName: 'PUERTO BERRÍO', name: 'ANTIOQUIA' },
  { municipCode: '15572', municipName: 'PUERTO BOYACÁ', name: 'BOYACÁ' },
  { municipCode: '86569', municipName: 'PUERTO CAICEDO', name: 'PUTUMAYO' },
  { municipCode: '99001', municipName: 'PUERTO CARREÑO', name: 'VICHADA' },
  { municipCode: '08573', municipName: 'PUERTO COLOMBIA', name: 'ATLÁNTICO' },
  { municipCode: '94884', municipName: 'PUERTO COLOMBIA', name: 'GUAINÍA' },
  { municipCode: '50450', municipName: 'PUERTO CONCORDIA', name: 'META' },
  { municipCode: '23574', municipName: 'PUERTO ESCONDIDO', name: 'CÓRDOBA' },
  { municipCode: '50568', municipName: 'PUERTO GAITÁN', name: 'META' },
  { municipCode: '86571', municipName: 'PUERTO GUZMÁN', name: 'PUTUMAYO' },
  { municipCode: '86573', municipName: 'PUERTO LEGUÍZAMO', name: 'PUTUMAYO' },
  { municipCode: '23580', municipName: 'PUERTO LIBERTADOR', name: 'CÓRDOBA' },
  { municipCode: '50577', municipName: 'PUERTO LLERAS', name: 'META' },
  { municipCode: '50573', municipName: 'PUERTO LÓPEZ', name: 'META' },
  { municipCode: '05585', municipName: 'PUERTO NARE', name: 'ANTIOQUIA' },
  { municipCode: '91540', municipName: 'PUERTO NARIÑO', name: 'AMAZONAS' },
  { municipCode: '68573', municipName: 'PUERTO PARRA', name: 'SANTANDER' },
  { municipCode: '18592', municipName: 'PUERTO RICO', name: 'CAQUETÁ' },
  { municipCode: '50590', municipName: 'PUERTO RICO', name: 'META' },
  { municipCode: '81591', municipName: 'PUERTO RONDÓN', name: 'ARAUCA' },
  { municipCode: '25572', municipName: 'PUERTO SALGAR', name: 'CUNDINAMARCA' },
  { municipCode: '91669', municipName: 'PUERTO SANTANDER', name: 'AMAZONAS' },
  { municipCode: '54553', municipName: 'PUERTO SANTANDER', name: 'NORTE DE SANTANDER' },
  { municipCode: '19573', municipName: 'PUERTO TEJADA', name: 'CAUCA' },
  { municipCode: '05591', municipName: 'PUERTO TRIUNFO', name: 'ANTIOQUIA' },
  { municipCode: '68575', municipName: 'PUERTO WILCHES', name: 'SANTANDER' },
  { municipCode: '25580', municipName: 'PULÍ', name: 'CUNDINAMARCA' },
  { municipCode: '52585', municipName: 'PUPIALES', name: 'NARIÑO' },
  { municipCode: '19585', municipName: 'PURACÉ', name: 'CAUCA' },
  { municipCode: '73585', municipName: 'PURIFICACIÓN', name: 'TOLIMA' },
  { municipCode: '23586', municipName: 'PURÍSIMA DE LA CONCEPCIÓN', name: 'CÓRDOBA' },
  { municipCode: '25592', municipName: 'QUEBRADANEGRA', name: 'CUNDINAMARCA' },
  { municipCode: '25594', municipName: 'QUETAME', name: 'CUNDINAMARCA' },
  { municipCode: '27001', municipName: 'QUIBDÓ', name: 'CHOCÓ' },
  { municipCode: '63594', municipName: 'QUIMBAYA', name: 'QUINDÍO' },
  { municipCode: '66594', municipName: 'QUINCHÍA', name: 'RISARALDA' },
  { municipCode: '15580', municipName: 'QUÍPAMA', name: 'BOYACÁ' },
  { municipCode: '25596', municipName: 'QUIPILE', name: 'CUNDINAMARCA' },
  { municipCode: '54599', municipName: 'RAGONVALIA', name: 'NORTE DE SANTANDER' },
  { municipCode: '15599', municipName: 'RAMIRIQUÍ', name: 'BOYACÁ' },
  { municipCode: '15600', municipName: 'RÁQUIRA', name: 'BOYACÁ' },
  { municipCode: '85279', municipName: 'RECETOR', name: 'CASANARE' },
  { municipCode: '13580', municipName: 'REGIDOR', name: 'BOLÍVAR' },
  { municipCode: '05604', municipName: 'REMEDIOS', name: 'ANTIOQUIA' },
  { municipCode: '47605', municipName: 'REMOLINO', name: 'MAGDALENA' },
  { municipCode: '08606', municipName: 'REPELÓN', name: 'ATLÁNTICO' },
  { municipCode: '50606', municipName: 'RESTREPO', name: 'META' },
  { municipCode: '76606', municipName: 'RESTREPO', name: 'VALLE DEL CAUCA' },
  { municipCode: '05607', municipName: 'RETIRO', name: 'ANTIOQUIA' },
  { municipCode: '25612', municipName: 'RICAURTE', name: 'CUNDINAMARCA' },
  { municipCode: '52612', municipName: 'RICAURTE', name: 'NARIÑO' },
  { municipCode: '20614', municipName: 'RÍO DE ORO', name: 'CESAR' },
  { municipCode: '27580', municipName: 'RÍO IRÓ', name: 'CHOCÓ' },
  { municipCode: '27600', municipName: 'RÍO QUITO', name: 'CHOCÓ' },
  { municipCode: '13600', municipName: 'RÍO VIEJO', name: 'BOLÍVAR' },
  { municipCode: '73616', municipName: 'RIOBLANCO', name: 'TOLIMA' },
  { municipCode: '76616', municipName: 'RIOFRÍO', name: 'VALLE DEL CAUCA' },
  { municipCode: '44001', municipName: 'RIOHACHA', name: 'LA GUAJIRA' },
  { municipCode: '05615', municipName: 'RIONEGRO', name: 'ANTIOQUIA' },
  { municipCode: '68615', municipName: 'RIONEGRO', name: 'SANTANDER' },
  { municipCode: '17614', municipName: 'RIOSUCIO', name: 'CALDAS' },
  { municipCode: '27615', municipName: 'RIOSUCIO', name: 'CHOCÓ' },
  { municipCode: '17616', municipName: 'RISARALDA', name: 'CALDAS' },
  { municipCode: '41615', municipName: 'RIVERA', name: 'HUILA' },
  { municipCode: '52621', municipName: 'ROBERTO PAYÁN', name: 'NARIÑO' },
  { municipCode: '76622', municipName: 'ROLDANILLO', name: 'VALLE DEL CAUCA' },
  { municipCode: '73622', municipName: 'RONCESVALLES', name: 'TOLIMA' },
  { municipCode: '15621', municipName: 'RONDÓN', name: 'BOYACÁ' },
  { municipCode: '19622', municipName: 'ROSAS', name: 'CAUCA' },
  { municipCode: '73624', municipName: 'ROVIRA', name: 'TOLIMA' },
  { municipCode: '68655', municipName: 'SABANA DE TORRES', name: 'SANTANDER' },
  { municipCode: '08634', municipName: 'SABANAGRANDE', name: 'ATLÁNTICO' },
  { municipCode: '05628', municipName: 'SABANALARGA', name: 'ANTIOQUIA' },
  { municipCode: '08638', municipName: 'SABANALARGA', name: 'ATLÁNTICO' },
  { municipCode: '85300', municipName: 'SABANALARGA', name: 'CASANARE' },
  { municipCode: '47660', municipName: 'SABANAS DE SAN ÁNGEL', name: 'MAGDALENA' },
  { municipCode: '05631', municipName: 'SABANETA', name: 'ANTIOQUIA' },
  { municipCode: '15632', municipName: 'SABOYÁ', name: 'BOYACÁ' },
  { municipCode: '85315', municipName: 'SÁCAMA', name: 'CASANARE' },
  { municipCode: '15638', municipName: 'SÁCHICA', name: 'BOYACÁ' },
  { municipCode: '23660', municipName: 'SAHAGÚN', name: 'CÓRDOBA' },
  { municipCode: '41660', municipName: 'SALADOBLANCO', name: 'HUILA' },
  { municipCode: '17653', municipName: 'SALAMINA', name: 'CALDAS' },
  { municipCode: '47675', municipName: 'SALAMINA', name: 'MAGDALENA' },
  { municipCode: '54660', municipName: 'SALAZAR', name: 'NORTE DE SANTANDER' },
  { municipCode: '73671', municipName: 'SALDAÑA', name: 'TOLIMA' },
  { municipCode: '63690', municipName: 'SALENTO', name: 'QUINDÍO' },
  { municipCode: '05642', municipName: 'SALGAR', name: 'ANTIOQUIA' },
  { municipCode: '15646', municipName: 'SAMACÁ', name: 'BOYACÁ' },
  { municipCode: '17662', municipName: 'SAMANÁ', name: 'CALDAS' },
  { municipCode: '52678', municipName: 'SAMANIEGO', name: 'NARIÑO' },
  { municipCode: '70670', municipName: 'SAMPUÉS', name: 'SUCRE' },
  { municipCode: '41668', municipName: 'SAN AGUSTÍN', name: 'HUILA' },
  { municipCode: '20710', municipName: 'SAN ALBERTO', name: 'CESAR' },
  { municipCode: '88001', municipName: 'SAN ANDRÉS', name: 'ARCHIPIÉLAGO DE SAN ANDRÉS. PROVIDENCIA Y SANTA CATALINA' },
  { municipCode: '68669', municipName: 'SAN ANDRÉS', name: 'SANTANDER' },
  { municipCode: '05647', municipName: 'SAN ANDRÉS DE CUERQUÍA', name: 'ANTIOQUIA' },
  { municipCode: '23670', municipName: 'SAN ANDRÉS DE SOTAVENTO', name: 'CÓRDOBA' },
  { municipCode: '52835', municipName: 'SAN ANDRÉS DE TUMACO', name: 'NARIÑO' },
  { municipCode: '23672', municipName: 'SAN ANTERO', name: 'CÓRDOBA' },
  { municipCode: '73675', municipName: 'SAN ANTONIO', name: 'TOLIMA' },
  { municipCode: '25645', municipName: 'SAN ANTONIO DEL TEQUENDAMA', name: 'CUNDINAMARCA' },
  { municipCode: '68673', municipName: 'SAN BENITO', name: 'SANTANDER' },
  { municipCode: '70678', municipName: 'SAN BENITO ABAD', name: 'SUCRE' },
  { municipCode: '25649', municipName: 'SAN BERNARDO', name: 'CUNDINAMARCA' },
  { municipCode: '52685', municipName: 'SAN BERNARDO', name: 'NARIÑO' },
  { municipCode: '23675', municipName: 'SAN BERNARDO DEL VIENTO', name: 'CÓRDOBA' },
  { municipCode: '54670', municipName: 'SAN CALIXTO', name: 'NORTE DE SANTANDER' },
  { municipCode: '05649', municipName: 'SAN CARLOS', name: 'ANTIOQUIA' },
  { municipCode: '23678', municipName: 'SAN CARLOS', name: 'CÓRDOBA' },
  { municipCode: '50680', municipName: 'SAN CARLOS DE GUAROA', name: 'META' },
  { municipCode: '25653', municipName: 'SAN CAYETANO', name: 'CUNDINAMARCA' },
  { municipCode: '54673', municipName: 'SAN CAYETANO', name: 'NORTE DE SANTANDER' },
  { municipCode: '13620', municipName: 'SAN CRISTÓBAL', name: 'BOLÍVAR' },
  { municipCode: '20750', municipName: 'SAN DIEGO', name: 'CESAR' },
  { municipCode: '15660', municipName: 'SAN EDUARDO', name: 'BOYACÁ' },
  { municipCode: '13647', municipName: 'SAN ESTANISLAO', name: 'BOLÍVAR' },
  { municipCode: '94883', municipName: 'SAN FELIPE', name: 'GUAINÍA' },
  { municipCode: '13650', municipName: 'SAN FERNANDO', name: 'BOLÍVAR' },
  { municipCode: '05652', municipName: 'SAN FRANCISCO', name: 'ANTIOQUIA' },
  { municipCode: '25658', municipName: 'SAN FRANCISCO', name: 'CUNDINAMARCA' },
  { municipCode: '86755', municipName: 'SAN FRANCISCO', name: 'PUTUMAYO' },
  { municipCode: '68679', municipName: 'SAN GIL', name: 'SANTANDER' },
  { municipCode: '13654', municipName: 'SAN JACINTO', name: 'BOLÍVAR' },
  { municipCode: '13655', municipName: 'SAN JACINTO DEL CAUCA', name: 'BOLÍVAR' },
  { municipCode: '05656', municipName: 'SAN JERÓNIMO', name: 'ANTIOQUIA' },
  { municipCode: '68682', municipName: 'SAN JOAQUÍN', name: 'SANTANDER' },
  { municipCode: '17665', municipName: 'SAN JOSÉ', name: 'CALDAS' },
  { municipCode: '54001', municipName: 'SAN JOSÉ DE CÚCUTA', name: 'NORTE DE SANTANDER' },
  { municipCode: '05658', municipName: 'SAN JOSÉ DE LA MONTAÑA', name: 'ANTIOQUIA' },
  { municipCode: '68684', municipName: 'SAN JOSÉ DE MIRANDA', name: 'SANTANDER' },
  { municipCode: '15664', municipName: 'SAN JOSÉ DE PARE', name: 'BOYACÁ' },
  { municipCode: '70823', municipName: 'SAN JOSÉ DE TOLUVIEJO', name: 'SUCRE' },
  { municipCode: '23682', municipName: 'SAN JOSÉ DE URÉ', name: 'CÓRDOBA' },
  { municipCode: '18610', municipName: 'SAN JOSÉ DEL FRAGUA', name: 'CAQUETÁ' },
  { municipCode: '95001', municipName: 'SAN JOSÉ DEL GUAVIARE', name: 'GUAVIARE' },
  { municipCode: '27660', municipName: 'SAN JOSÉ DEL PALMAR', name: 'CHOCÓ' },
  { municipCode: '50683', municipName: 'SAN JUAN DE ARAMA', name: 'META' },
  { municipCode: '70702', municipName: 'SAN JUAN DE BETULIA', name: 'SUCRE' },
  { municipCode: '25662', municipName: 'SAN JUAN DE RIOSECO', name: 'CUNDINAMARCA' },
  { municipCode: '05659', municipName: 'SAN JUAN DE URABÁ', name: 'ANTIOQUIA' },
  { municipCode: '44650', municipName: 'SAN JUAN DEL CESAR', name: 'LA GUAJIRA' },
  { municipCode: '13657', municipName: 'SAN JUAN NEPOMUCENO', name: 'BOLÍVAR' },
  { municipCode: '50686', municipName: 'SAN JUANITO', name: 'META' },
  { municipCode: '52687', municipName: 'SAN LORENZO', name: 'NARIÑO' },
  { municipCode: '05660', municipName: 'SAN LUIS', name: 'ANTIOQUIA' },
  { municipCode: '73678', municipName: 'SAN LUIS', name: 'TOLIMA' },
  { municipCode: '15667', municipName: 'SAN LUIS DE GACENO', name: 'BOYACÁ' },
  { municipCode: '85325', municipName: 'SAN LUIS DE PALENQUE', name: 'CASANARE' },
  { municipCode: '70742', municipName: 'SAN LUIS DE SINCÉ', name: 'SUCRE' },
  { municipCode: '70708', municipName: 'SAN MARCOS', name: 'SUCRE' },
  { municipCode: '20770', municipName: 'SAN MARTÍN', name: 'CESAR' },
  { municipCode: '50689', municipName: 'SAN MARTÍN', name: 'META' },
  { municipCode: '13667', municipName: 'SAN MARTÍN DE LOBA', name: 'BOLÍVAR' },
  { municipCode: '15673', municipName: 'SAN MATEO', name: 'BOYACÁ' },
  { municipCode: '86757', municipName: 'SAN MIGUEL', name: 'PUTUMAYO' },
  { municipCode: '68686', municipName: 'SAN MIGUEL', name: 'SANTANDER' },
  { municipCode: '15676', municipName: 'SAN MIGUEL DE SEMA', name: 'BOYACÁ' },
  { municipCode: '70713', municipName: 'SAN ONOFRE', name: 'SUCRE' },
  { municipCode: '13670', municipName: 'SAN PABLO', name: 'BOLÍVAR' },
  { municipCode: '52693', municipName: 'SAN PABLO', name: 'NARIÑO' },
  { municipCode: '15681', municipName: 'SAN PABLO DE BORBUR', name: 'BOYACÁ' },
  { municipCode: '70717', municipName: 'SAN PEDRO', name: 'SUCRE' },
  { municipCode: '76670', municipName: 'SAN PEDRO', name: 'VALLE DEL CAUCA' },
  { municipCode: '52694', municipName: 'SAN PEDRO DE CARTAGO', name: 'NARIÑO' },
  { municipCode: '05664', municipName: 'SAN PEDRO DE LOS MILAGROS', name: 'ANTIOQUIA' },
  { municipCode: '05665', municipName: 'SAN PEDRO DE URABÁ', name: 'ANTIOQUIA' },
  { municipCode: '23686', municipName: 'SAN PELAYO', name: 'CÓRDOBA' },
  { municipCode: '05667', municipName: 'SAN RAFAEL', name: 'ANTIOQUIA' },
  { municipCode: '05670', municipName: 'SAN ROQUE', name: 'ANTIOQUIA' },
  { municipCode: '19693', municipName: 'SAN SEBASTIÁN', name: 'CAUCA' },
  { municipCode: '47692', municipName: 'SAN SEBASTIÁN DE BUENAVISTA', name: 'MAGDALENA' },
  { municipCode: '73443', municipName: 'SAN SEBASTIÁN DE MARIQUITA', name: 'TOLIMA' },
  { municipCode: '68689', municipName: 'SAN VICENTE DE CHUCURÍ', name: 'SANTANDER' },
  { municipCode: '18753', municipName: 'SAN VICENTE DEL CAGUÁN', name: 'CAQUETÁ' },
  { municipCode: '05674', municipName: 'SAN VICENTE FERRER', name: 'ANTIOQUIA' },
  { municipCode: '47703', municipName: 'SAN ZENÓN', name: 'MAGDALENA' },
  { municipCode: '52683', municipName: 'SANDONÁ', name: 'NARIÑO' },
  { municipCode: '47707', municipName: 'SANTA ANA', name: 'MAGDALENA' },
  { municipCode: '05679', municipName: 'SANTA BÁRBARA', name: 'ANTIOQUIA' },
  { municipCode: '52696', municipName: 'SANTA BÁRBARA', name: 'NARIÑO' },
  { municipCode: '68705', municipName: 'SANTA BÁRBARA', name: 'SANTANDER' },
  { municipCode: '47720', municipName: 'SANTA BÁRBARA DE PINTO', name: 'MAGDALENA' },
  { municipCode: '13673', municipName: 'SANTA CATALINA', name: 'BOLÍVAR' },
  { municipCode: '13468', municipName: 'SANTA CRUZ DE MOMPOX', name: 'BOLÍVAR' },
  { municipCode: '05042', municipName: 'SANTA FÉ DE ANTIOQUIA', name: 'ANTIOQUIA' },
  { municipCode: '68720', municipName: 'SANTA HELENA DEL OPÓN', name: 'SANTANDER' },
  { municipCode: '73686', municipName: 'SANTA ISABEL', name: 'TOLIMA' },
  { municipCode: '08675', municipName: 'SANTA LUCÍA', name: 'ATLÁNTICO' },
  { municipCode: '15690', municipName: 'SANTA MARÍA', name: 'BOYACÁ' },
  { municipCode: '41676', municipName: 'SANTA MARÍA', name: 'HUILA' },
  { municipCode: '47001', municipName: 'SANTA MARTA', name: 'MAGDALENA' },
  { municipCode: '13683', municipName: 'SANTA ROSA', name: 'BOLÍVAR' },
  { municipCode: '19701', municipName: 'SANTA ROSA', name: 'CAUCA' },
  { municipCode: '66682', municipName: 'SANTA ROSA DE CABAL', name: 'RISARALDA' },
  { municipCode: '05686', municipName: 'SANTA ROSA DE OSOS', name: 'ANTIOQUIA' },
  { municipCode: '15693', municipName: 'SANTA ROSA DE VITERBO', name: 'BOYACÁ' },
  { municipCode: '13688', municipName: 'SANTA ROSA DEL SUR', name: 'BOLÍVAR' },
  { municipCode: '99624', municipName: 'SANTA ROSALÍA', name: 'VICHADA' },
  { municipCode: '15696', municipName: 'SANTA SOFÍA', name: 'BOYACÁ' },
  { municipCode: '52699', municipName: 'SANTACRUZ', name: 'NARIÑO' },
  { municipCode: '15686', municipName: 'SANTANA', name: 'BOYACÁ' },
  { municipCode: '19698', municipName: 'SANTANDER DE QUILICHAO', name: 'CAUCA' },
  { municipCode: '54680', municipName: 'SANTIAGO', name: 'NORTE DE SANTANDER' },
  { municipCode: '86760', municipName: 'SANTIAGO', name: 'PUTUMAYO' },
  { municipCode: '70820', municipName: 'SANTIAGO DE TOLÚ', name: 'SUCRE' },
  { municipCode: '05690', municipName: 'SANTO DOMINGO', name: 'ANTIOQUIA' },
  { municipCode: '08685', municipName: 'SANTO TOMÁS', name: 'ATLÁNTICO' },
  { municipCode: '66687', municipName: 'SANTUARIO', name: 'RISARALDA' },
  { municipCode: '52720', municipName: 'SAPUYES', name: 'NARIÑO' },
  { municipCode: '81736', municipName: 'SARAVENA', name: 'ARAUCA' },
  { municipCode: '54720', municipName: 'SARDINATA', name: 'NORTE DE SANTANDER' },
  { municipCode: '25718', municipName: 'SASAIMA', name: 'CUNDINAMARCA' },
  { municipCode: '15720', municipName: 'SATIVANORTE', name: 'BOYACÁ' },
  { municipCode: '15723', municipName: 'SATIVASUR', name: 'BOYACÁ' },
  { municipCode: '05736', municipName: 'SEGOVIA', name: 'ANTIOQUIA' },
  { municipCode: '25736', municipName: 'SESQUILÉ', name: 'CUNDINAMARCA' },
  { municipCode: '76736', municipName: 'SEVILLA', name: 'VALLE DEL CAUCA' },
  { municipCode: '15740', municipName: 'SIACHOQUE', name: 'BOYACÁ' },
  { municipCode: '25740', municipName: 'SIBATÉ', name: 'CUNDINAMARCA' },
  { municipCode: '86749', municipName: 'SIBUNDOY', name: 'PUTUMAYO' },
  { municipCode: '54743', municipName: 'SILOS', name: 'NORTE DE SANTANDER' },
  { municipCode: '25743', municipName: 'SILVANIA', name: 'CUNDINAMARCA' },
  { municipCode: '19743', municipName: 'SILVIA', name: 'CAUCA' },
  { municipCode: '68745', municipName: 'SIMACOTA', name: 'SANTANDER' },
  { municipCode: '25745', municipName: 'SIMIJACA', name: 'CUNDINAMARCA' },
  { municipCode: '13744', municipName: 'SIMITÍ', name: 'BOLÍVAR' },
  { municipCode: '70001', municipName: 'SINCELEJO', name: 'SUCRE' },
  { municipCode: '27745', municipName: 'SIPÍ', name: 'CHOCÓ' },
  { municipCode: '47745', municipName: 'SITIONUEVO', name: 'MAGDALENA' },
  { municipCode: '25754', municipName: 'SOACHA', name: 'CUNDINAMARCA' },
  { municipCode: '15753', municipName: 'SOATÁ', name: 'BOYACÁ' },
  { municipCode: '15757', municipName: 'SOCHA', name: 'BOYACÁ' },
  { municipCode: '68755', municipName: 'SOCORRO', name: 'SANTANDER' },
  { municipCode: '15755', municipName: 'SOCOTÁ', name: 'BOYACÁ' },
  { municipCode: '15759', municipName: 'SOGAMOSO', name: 'BOYACÁ' },
  { municipCode: '18756', municipName: 'SOLANO', name: 'CAQUETÁ' },
  { municipCode: '08758', municipName: 'SOLEDAD', name: 'ATLÁNTICO' },
  { municipCode: '18785', municipName: 'SOLITA', name: 'CAQUETÁ' },
  { municipCode: '15761', municipName: 'SOMONDOCO', name: 'BOYACÁ' },
  { municipCode: '05756', municipName: 'SONSÓN', name: 'ANTIOQUIA' },
  { municipCode: '05761', municipName: 'SOPETRÁN', name: 'ANTIOQUIA' },
  { municipCode: '13760', municipName: 'SOPLAVIENTO', name: 'BOLÍVAR' },
  { municipCode: '25758', municipName: 'SOPÓ', name: 'CUNDINAMARCA' },
  { municipCode: '15762', municipName: 'SORA', name: 'BOYACÁ' },
  { municipCode: '15764', municipName: 'SORACÁ', name: 'BOYACÁ' },
  { municipCode: '15763', municipName: 'SOTAQUIRÁ', name: 'BOYACÁ' },
  { municipCode: '19760', municipName: 'SOTARÁ PAISPAMBA', name: 'CAUCA' },
  { municipCode: '68770', municipName: 'SUAITA', name: 'SANTANDER' },
  { municipCode: '08770', municipName: 'SUAN', name: 'ATLÁNTICO' },
  { municipCode: '19780', municipName: 'SUÁREZ', name: 'CAUCA' },
  { municipCode: '73770', municipName: 'SUÁREZ', name: 'TOLIMA' },
  { municipCode: '41770', municipName: 'SUAZA', name: 'HUILA' },
  { municipCode: '25769', municipName: 'SUBACHOQUE', name: 'CUNDINAMARCA' },
  { municipCode: '19785', municipName: 'SUCRE', name: 'CAUCA' },
  { municipCode: '68773', municipName: 'SUCRE', name: 'SANTANDER' },
  { municipCode: '70771', municipName: 'SUCRE', name: 'SUCRE' },
  { municipCode: '25772', municipName: 'SUESCA', name: 'CUNDINAMARCA' },
  { municipCode: '25777', municipName: 'SUPATÁ', name: 'CUNDINAMARCA' },
  { municipCode: '17777', municipName: 'SUPÍA', name: 'CALDAS' },
  { municipCode: '68780', municipName: 'SURATÁ', name: 'SANTANDER' },
  { municipCode: '25779', municipName: 'SUSA', name: 'CUNDINAMARCA' },
  { municipCode: '15774', municipName: 'SUSACÓN', name: 'BOYACÁ' },
  { municipCode: '15776', municipName: 'SUTAMARCHÁN', name: 'BOYACÁ' },
  { municipCode: '25781', municipName: 'SUTATAUSA', name: 'CUNDINAMARCA' },
  { municipCode: '15778', municipName: 'SUTATENZA', name: 'BOYACÁ' },
  { municipCode: '25785', municipName: 'TABIO', name: 'CUNDINAMARCA' },
  { municipCode: '27787', municipName: 'TADÓ', name: 'CHOCÓ' },
  { municipCode: '13780', municipName: 'TALAIGUA NUEVO', name: 'BOLÍVAR' },
  { municipCode: '20787', municipName: 'TAMALAMEQUE', name: 'CESAR' },
  { municipCode: '85400', municipName: 'TÁMARA', name: 'CASANARE' },
  { municipCode: '81794', municipName: 'TAME', name: 'ARAUCA' },
  { municipCode: '05789', municipName: 'TÁMESIS', name: 'ANTIOQUIA' },
  { municipCode: '52786', municipName: 'TAMINANGO', name: 'NARIÑO' },
  { municipCode: '52788', municipName: 'TANGUA', name: 'NARIÑO' },
  { municipCode: '97666', municipName: 'TARAIRA', name: 'VAUPÉS' },
  { municipCode: '91798', municipName: 'TARAPACÁ', name: 'AMAZONAS' },
  { municipCode: '05790', municipName: 'TARAZÁ', name: 'ANTIOQUIA' },
  { municipCode: '41791', municipName: 'TARQUI', name: 'HUILA' },
  { municipCode: '05792', municipName: 'TARSO', name: 'ANTIOQUIA' },
  { municipCode: '15790', municipName: 'TASCO', name: 'BOYACÁ' },
  { municipCode: '85410', municipName: 'TAURAMENA', name: 'CASANARE' },
  { municipCode: '25793', municipName: 'TAUSA', name: 'CUNDINAMARCA' },
  { municipCode: '41799', municipName: 'TELLO', name: 'HUILA' },
  { municipCode: '25797', municipName: 'TENA', name: 'CUNDINAMARCA' },
  { municipCode: '47798', municipName: 'TENERIFE', name: 'MAGDALENA' },
  { municipCode: '25799', municipName: 'TENJO', name: 'CUNDINAMARCA' },
  { municipCode: '15798', municipName: 'TENZA', name: 'BOYACÁ' },
  { municipCode: '54800', municipName: 'TEORAMA', name: 'NORTE DE SANTANDER' },
  { municipCode: '41801', municipName: 'TERUEL', name: 'HUILA' },
  { municipCode: '41797', municipName: 'TESALIA', name: 'HUILA' },
  { municipCode: '25805', municipName: 'TIBACUY', name: 'CUNDINAMARCA' },
  { municipCode: '15804', municipName: 'TIBANÁ', name: 'BOYACÁ' },
  { municipCode: '15806', municipName: 'TIBASOSA', name: 'BOYACÁ' },
  { municipCode: '25807', municipName: 'TIBIRITA', name: 'CUNDINAMARCA' },
  { municipCode: '54810', municipName: 'TIBÚ', name: 'NORTE DE SANTANDER' },
  { municipCode: '23807', municipName: 'TIERRALTA', name: 'CÓRDOBA' },
  { municipCode: '41807', municipName: 'TIMANÁ', name: 'HUILA' },
  { municipCode: '19807', municipName: 'TIMBÍO', name: 'CAUCA' },
  { municipCode: '19809', municipName: 'TIMBIQUÍ', name: 'CAUCA' },
  { municipCode: '15808', municipName: 'TINJACÁ', name: 'BOYACÁ' },
  { municipCode: '15810', municipName: 'TIPACOQUE', name: 'BOYACÁ' },
  { municipCode: '13810', municipName: 'TIQUISIO', name: 'BOLÍVAR' },
  { municipCode: '05809', municipName: 'TITIRIBÍ', name: 'ANTIOQUIA' },
  { municipCode: '15814', municipName: 'TOCA', name: 'BOYACÁ' },
  { municipCode: '25815', municipName: 'TOCAIMA', name: 'CUNDINAMARCA' },
  { municipCode: '25817', municipName: 'TOCANCIPÁ', name: 'CUNDINAMARCA' },
  { municipCode: '15816', municipName: 'TOGÜÍ', name: 'BOYACÁ' },
  { municipCode: '05819', municipName: 'TOLEDO', name: 'ANTIOQUIA' },
  { municipCode: '54820', municipName: 'TOLEDO', name: 'NORTE DE SANTANDER' },
  { municipCode: '68820', municipName: 'TONA', name: 'SANTANDER' },
  { municipCode: '15820', municipName: 'TÓPAGA', name: 'BOYACÁ' },
  { municipCode: '25823', municipName: 'TOPAIPÍ', name: 'CUNDINAMARCA' },
  { municipCode: '19821', municipName: 'TORIBÍO', name: 'CAUCA' },
  { municipCode: '76823', municipName: 'TORO', name: 'VALLE DEL CAUCA' },
  { municipCode: '15822', municipName: 'TOTA', name: 'BOYACÁ' },
  { municipCode: '19824', municipName: 'TOTORÓ', name: 'CAUCA' },
  { municipCode: '85430', municipName: 'TRINIDAD', name: 'CASANARE' },
  { municipCode: '76828', municipName: 'TRUJILLO', name: 'VALLE DEL CAUCA' },
  { municipCode: '08832', municipName: 'TUBARÁ', name: 'ATLÁNTICO' },
  { municipCode: '23815', municipName: 'TUCHÍN', name: 'CÓRDOBA' },
  { municipCode: '76834', municipName: 'TULUÁ', name: 'VALLE DEL CAUCA' },
  { municipCode: '15001', municipName: 'TUNJA', name: 'BOYACÁ' },
  { municipCode: '15832', municipName: 'TUNUNGUÁ', name: 'BOYACÁ' },
  { municipCode: '52838', municipName: 'TÚQUERRES', name: 'NARIÑO' },
  { municipCode: '13836', municipName: 'TURBACO', name: 'BOLÍVAR' },
  { municipCode: '13838', municipName: 'TURBANÁ', name: 'BOLÍVAR' },
  { municipCode: '05837', municipName: 'TURBO', name: 'ANTIOQUIA' },
  { municipCode: '15835', municipName: 'TURMEQUÉ', name: 'BOYACÁ' },
  { municipCode: '15837', municipName: 'TUTA', name: 'BOYACÁ' },
  { municipCode: '15839', municipName: 'TUTAZÁ', name: 'BOYACÁ' },
  { municipCode: '25839', municipName: 'UBALÁ', name: 'CUNDINAMARCA' },
  { municipCode: '25841', municipName: 'UBAQUE', name: 'CUNDINAMARCA' },
  { municipCode: '76845', municipName: 'ULLOA', name: 'VALLE DEL CAUCA' },
  { municipCode: '15842', municipName: 'ÚMBITA', name: 'BOYACÁ' },
  { municipCode: '25845', municipName: 'UNE', name: 'CUNDINAMARCA' },
  { municipCode: '27800', municipName: 'UNGUÍA', name: 'CHOCÓ' },
  { municipCode: '27810', municipName: 'UNIÓN PANAMERICANA', name: 'CHOCÓ' },
  { municipCode: '05842', municipName: 'URAMITA', name: 'ANTIOQUIA' },
  { municipCode: '50370', municipName: 'URIBE', name: 'META' },
  { municipCode: '44847', municipName: 'URIBIA', name: 'LA GUAJIRA' },
  { municipCode: '05847', municipName: 'URRAO', name: 'ANTIOQUIA' },
  { municipCode: '44855', municipName: 'URUMITA', name: 'LA GUAJIRA' },
  { municipCode: '08849', municipName: 'USIACURÍ', name: 'ATLÁNTICO' },
  { municipCode: '25851', municipName: 'ÚTICA', name: 'CUNDINAMARCA' },
  { municipCode: '05854', municipName: 'VALDIVIA', name: 'ANTIOQUIA' },
  { municipCode: '23855', municipName: 'VALENCIA', name: 'CÓRDOBA' },
  { municipCode: '68855', municipName: 'VALLE DE SAN JOSÉ', name: 'SANTANDER' },
  { municipCode: '73854', municipName: 'VALLE DE SAN JUAN', name: 'TOLIMA' },
  { municipCode: '86865', municipName: 'VALLE DEL GUAMUEZ', name: 'PUTUMAYO' },
  { municipCode: '20001', municipName: 'VALLEDUPAR', name: 'CESAR' },
  { municipCode: '05856', municipName: 'VALPARAÍSO', name: 'ANTIOQUIA' },
  { municipCode: '18860', municipName: 'VALPARAÍSO', name: 'CAQUETÁ' },
  { municipCode: '05858', municipName: 'VEGACHÍ', name: 'ANTIOQUIA' },
  { municipCode: '68861', municipName: 'VÉLEZ', name: 'SANTANDER' },
  { municipCode: '73861', municipName: 'VENADILLO', name: 'TOLIMA' },
  { municipCode: '05861', municipName: 'VENECIA', name: 'ANTIOQUIA' },
  { municipCode: '25506', municipName: 'VENECIA', name: 'CUNDINAMARCA' },
  { municipCode: '15861', municipName: 'VENTAQUEMADA', name: 'BOYACÁ' },
  { municipCode: '25862', municipName: 'VERGARA', name: 'CUNDINAMARCA' },
  { municipCode: '76863', municipName: 'VERSALLES', name: 'VALLE DEL CAUCA' },
  { municipCode: '68867', municipName: 'VETAS', name: 'SANTANDER' },
  { municipCode: '25867', municipName: 'VIANÍ', name: 'CUNDINAMARCA' },
  { municipCode: '17867', municipName: 'VICTORIA', name: 'CALDAS' },
  { municipCode: '05873', municipName: 'VIGÍA DEL FUERTE', name: 'ANTIOQUIA' },
  { municipCode: '76869', municipName: 'VIJES', name: 'VALLE DEL CAUCA' },
  { municipCode: '54871', municipName: 'VILLA CARO', name: 'NORTE DE SANTANDER' },
  { municipCode: '15407', municipName: 'VILLA DE LEYVA', name: 'BOYACÁ' },
  { municipCode: '25843', municipName: 'VILLA DE SAN DIEGO DE UBATÉ', name: 'CUNDINAMARCA' },
  { municipCode: '54874', municipName: 'VILLA DEL ROSARIO', name: 'NORTE DE SANTANDER' },
  { municipCode: '19845', municipName: 'VILLA RICA', name: 'CAUCA' },
  { municipCode: '86885', municipName: 'VILLAGARZÓN', name: 'PUTUMAYO' },
  { municipCode: '25871', municipName: 'VILLAGÓMEZ', name: 'CUNDINAMARCA' },
  { municipCode: '73870', municipName: 'VILLAHERMOSA', name: 'TOLIMA' },
  { municipCode: '17873', municipName: 'VILLAMARÍA', name: 'CALDAS' },
  { municipCode: '13873', municipName: 'VILLANUEVA', name: 'BOLÍVAR' },
  { municipCode: '85440', municipName: 'VILLANUEVA', name: 'CASANARE' },
  { municipCode: '44874', municipName: 'VILLANUEVA', name: 'LA GUAJIRA' },
  { municipCode: '68872', municipName: 'VILLANUEVA', name: 'SANTANDER' },
  { municipCode: '25873', municipName: 'VILLAPINZÓN', name: 'CUNDINAMARCA' },
  { municipCode: '73873', municipName: 'VILLARRICA', name: 'TOLIMA' },
  { municipCode: '50001', municipName: 'VILLAVICENCIO', name: 'META' },
  { municipCode: '41872', municipName: 'VILLAVIEJA', name: 'HUILA' },
  { municipCode: '25875', municipName: 'VILLETA', name: 'CUNDINAMARCA' },
  { municipCode: '25878', municipName: 'VIOTÁ', name: 'CUNDINAMARCA' },
  { municipCode: '15879', municipName: 'VIRACACHÁ', name: 'BOYACÁ' },
  { municipCode: '50711', municipName: 'VISTAHERMOSA', name: 'META' },
  { municipCode: '17877', municipName: 'VITERBO', name: 'CALDAS' },
  { municipCode: '25885', municipName: 'YACOPÍ', name: 'CUNDINAMARCA' },
  { municipCode: '52885', municipName: 'YACUANQUER', name: 'NARIÑO' },
  { municipCode: '41885', municipName: 'YAGUARÁ', name: 'HUILA' },
  { municipCode: '05885', municipName: 'YALÍ', name: 'ANTIOQUIA' },
  { municipCode: '05887', municipName: 'YARUMAL', name: 'ANTIOQUIA' },
  { municipCode: '97889', municipName: 'YAVARATÉ', name: 'VAUPÉS' },
  { municipCode: '05890', municipName: 'YOLOMBÓ', name: 'ANTIOQUIA' },
  { municipCode: '05893', municipName: 'YONDÓ', name: 'ANTIOQUIA' },
  { municipCode: '85001', municipName: 'YOPAL', name: 'CASANARE' },
  { municipCode: '76890', municipName: 'YOTOCO', name: 'VALLE DEL CAUCA' },
  { municipCode: '76892', municipName: 'YUMBO', name: 'VALLE DEL CAUCA' },
  { municipCode: '13894', municipName: 'ZAMBRANO', name: 'BOLÍVAR' },
  { municipCode: '68895', municipName: 'ZAPATOCA', name: 'SANTANDER' },
  { municipCode: '47960', municipName: 'ZAPAYÁN', name: 'MAGDALENA' },
  { municipCode: '05895', municipName: 'ZARAGOZA', name: 'ANTIOQUIA' },
  { municipCode: '76895', municipName: 'ZARZAL', name: 'VALLE DEL CAUCA' },
  { municipCode: '15897', municipName: 'ZETAQUIRA', name: 'BOYACÁ' },
  { municipCode: '25898', municipName: 'ZIPACÓN', name: 'CUNDINAMARCA' },
  { municipCode: '25899', municipName: 'ZIPAQUIRÁ', name: 'CUNDINAMARCA' },
  { municipCode: '47980', municipName: 'ZONA BANANERA', name: 'MAGDALENA' }
];
